INSERT OR IGNORE INTO vocabulary (word, meaning, example, example_vi, phonetic, part_of_speech, image_key, category)
VALUES
  ('invoice', 'hóa đơn', 'Please attach the invoice to your email.', 'Vui lòng đính kèm hóa đơn vào email của bạn.', '/ˈɪn.vɔɪs/', 'n.', 'invoice', 'TOEIC'),
  ('applicant', 'ứng viên', 'Each applicant must submit a résumé by Friday.', 'Mỗi ứng viên phải nộp sơ yếu lý lịch trước thứ Sáu.', '/ˈæp.lɪ.kənt/', 'n.', 'applicant', 'TOEIC'),
  ('deadline', 'hạn chót', 'The deadline for the report is next Monday.', 'Hạn chót nộp báo cáo là thứ Hai tuần sau.', '/ˈded.laɪn/', 'n.', 'deadline', 'TOEIC'),
  ('conference', 'hội nghị', 'She will speak at an international conference in May.', 'Cô ấy sẽ phát biểu tại một hội nghị quốc tế vào tháng Năm.', '/ˈkɑːn.fər.əns/', 'n.', 'conference', 'TOEIC'),
  ('shipment', 'lô hàng', 'The shipment will arrive at the warehouse tomorrow.', 'Lô hàng sẽ đến kho vào ngày mai.', '/ˈʃɪp.mənt/', 'n.', 'shipment', 'TOEIC'),
  ('budget', 'ngân sách', 'We need to reduce the marketing budget this quarter.', 'Chúng ta cần cắt giảm ngân sách marketing quý này.', '/ˈbʌdʒ.ɪt/', 'n.', 'budget', 'TOEIC'),
  ('employee', 'nhân viên', 'Every employee receives a complimentary lunch on Fridays.', 'Mỗi nhân viên được ăn trưa miễn phí vào thứ Sáu.', '/ɪmˈplɔɪ.iː/', 'n.', 'employee', 'TOEIC'),
  ('reservation', 'đặt chỗ', 'I made a reservation at the hotel near headquarters.', 'Tôi đã đặt phòng tại khách sạn gần trụ sở.', '/ˌrez.ərˈveɪ.ʃn/', 'n.', 'reservation', 'TOEIC'),
  ('inventory', 'hàng tồn kho', 'Please update the inventory before the store opens.', 'Vui lòng cập nhật hàng tồn kho trước khi cửa hàng mở cửa.', '/ˈɪn.vən.tɔː.ri/', 'n.', 'inventory', 'TOEIC'),
  ('memo', 'bản ghi nhớ', 'The manager sent a memo about the new dress code.', 'Quản lý đã gửi bản ghi nhớ về quy định trang phục mới.', '/ˈmem.oʊ/', 'n.', 'memo', 'TOEIC'),
  ('headquarters', 'trụ sở', 'Our headquarters is located downtown.', 'Trụ sở của chúng tôi nằm ở trung tâm thành phố.', '/ˈhedˌkwɔːr.tərz/', 'n.', 'headquarters', 'TOEIC'),
  ('itinerary', 'lịch trình', 'The travel itinerary includes two client meetings.', 'Lịch trình chuyến đi gồm hai cuộc họp với khách hàng.', '/aɪˈtɪn.ə.rer.i/', 'n.', 'itinerary', 'TOEIC'),
  ('occupancy', 'tỷ lệ lấp đầy', 'Hotel occupancy increased during the conference.', 'Tỷ lệ lấp đầy khách sạn tăng trong thời gian hội nghị.', '/ˈɑː.kjə.pən.si/', 'n.', 'occupancy', 'TOEIC'),
  ('complimentary', 'miễn phí (tặng kèm)', 'Guests receive a complimentary breakfast each morning.', 'Khách được dùng bữa sáng miễn phí mỗi sáng.', '/ˌkɑːm.plɪˈmen.tər.i/', 'adj.', 'complimentary', 'TOEIC'),
  ('authorize', 'ủy quyền / cho phép', 'Only the director can authorize this payment.', 'Chỉ giám đốc mới được ủy quyền khoản thanh toán này.', '/ˈɔː.θə.raɪz/', 'v.', 'authorize', 'TOEIC'),
  ('brochure', 'tờ rơi / brochure', 'Please take a brochure from the reception desk.', 'Xin hãy lấy một tờ brochure ở quầy lễ tân.', '/broʊˈʃʊr/', 'n.', 'brochure', 'TOEIC'),
  ('receipt', 'biên lai', 'Keep the receipt in case you need a refund.', 'Hãy giữ biên lai phòng khi bạn cần hoàn tiền.', '/ɹɪsˈit/', 'n.', 'invoice', 'TOEIC'),
  ('expense', 'chi phí', 'Travel expenses must be reported by Friday.', 'Chi phí đi lại phải được báo cáo trước thứ Sáu.', '/ɪkspˈɛns/', 'n.', 'invoice', 'TOEIC'),
  ('revenue', 'doanh thu', 'Online sales increased the company''s revenue.', 'Bán hàng trực tuyến làm tăng doanh thu của công ty.', '/ɹˈɛvənˌu/', 'n.', 'invoice', 'TOEIC'),
  ('profit', 'lợi nhuận', 'The store made a small profit last month.', 'Cửa hàng có lợi nhuận nhỏ vào tháng trước.', '/pɹˈɑfət/', 'n.', 'invoice', 'TOEIC'),
  ('loss', 'thua lỗ', 'The factory reported a loss after the storm.', 'Nhà máy báo lỗ sau cơn bão.', '/lˈɔs/', 'n.', 'invoice', 'TOEIC'),
  ('deduct', 'khấu trừ', 'The company will deduct tax from your paycheck.', 'Công ty sẽ khấu trừ thuế từ phiếu lương của bạn.', '/dɪdˈʌkt/', 'v.', 'invoice', 'TOEIC'),
  ('refund', 'hoàn tiền', 'Customers may request a refund within 14 days.', 'Khách có thể yêu cầu hoàn tiền trong vòng 14 ngày.', '/ɹɪfˈʌnd/', 'n.', 'invoice', 'TOEIC'),
  ('overdue', 'quá hạn', 'This invoice is overdue and must be paid today.', 'Hóa đơn này đã quá hạn và phải thanh toán hôm nay.', '/ˈoʊvɚdˈu/', 'adj.', 'invoice', 'TOEIC'),
  ('quotation', 'báo giá', 'Please send a quotation for 200 office chairs.', 'Vui lòng gửi báo giá cho 200 ghế văn phòng.', '/kwoʊtˈeɪʃən/', 'n.', 'invoice', 'TOEIC'),
  ('estimate', 'ước tính', 'The repair estimate is higher than we expected.', 'Ước tính chi phí sửa chữa cao hơn chúng tôi nghĩ.', '/ˈɛstɨmɨt/', 'n.', 'invoice', 'TOEIC'),
  ('transaction', 'giao dịch', 'Each transaction is recorded in the accounting system.', 'Mỗi giao dịch được ghi vào hệ thống kế toán.', '/tɹænzˈækʃən/', 'n.', 'invoice', 'TOEIC'),
  ('fee', 'phí', 'There is a small fee for late registration.', 'Có một khoản phí nhỏ nếu đăng ký muộn.', '/fˈi/', 'n.', 'invoice', 'TOEIC'),
  ('charge', 'khoản thu phí', 'The hotel added a service charge to the bill.', 'Khách sạn cộng phí dịch vụ vào hóa đơn.', '/t͡ʃɑːd͡ʒ/', 'n.', 'invoice', 'TOEIC'),
  ('discount', 'giảm giá', 'Members receive a 10 percent discount on all items.', 'Thành viên được giảm 10 phần trăm cho mọi mặt hàng.', '/dɪskˈaʊnt/', 'n.', 'invoice', 'TOEIC'),
  ('reimbursement', 'hoàn trả chi phí', 'Submit your tickets to receive reimbursement.', 'Nộp vé của bạn để được hoàn trả chi phí.', '/ˌɹiː.ɪmˈbɜːs.mənt/', 'n.', 'invoice', 'TOEIC'),
  ('accountant', 'kế toán', 'The accountant will review the annual report.', 'Kế toán sẽ rà soát báo cáo thường niên.', '/əkˈaʊntənt/', 'n.', 'invoice', 'TOEIC'),
  ('audit', 'kiểm toán', 'An external audit will begin next Monday.', 'Một cuộc kiểm toán độc lập sẽ bắt đầu vào thứ Hai tuần sau.', '/ɔː.dɪt/', 'n.', 'invoice', 'TOEIC'),
  ('fiscal', 'thuộc tài khóa', 'The fiscal year ends on December 31.', 'Năm tài khóa kết thúc vào ngày 31 tháng 12.', '/fˈɪskəl/', 'adj.', 'invoice', 'TOEIC'),
  ('tax', 'thuế', 'Sales tax is included in the listed price.', 'Thuế bán hàng đã được tính trong giá niêm yết.', '/tæks/', 'n.', 'invoice', 'TOEIC'),
  ('tariff', 'thuế quan', 'The new tariff will raise the cost of imported steel.', 'Thuế quan mới sẽ làm tăng giá thép nhập khẩu.', '/tˈɛɹəf/', 'n.', 'invoice', 'TOEIC'),
  ('ledger', 'sổ cái', 'Please enter this payment in the ledger.', 'Vui lòng ghi khoản thanh toán này vào sổ cái.', '/lˈɛdʒɚ/', 'n.', 'invoice', 'TOEIC'),
  ('payable', 'phải trả', 'All invoices are payable within 30 days.', 'Mọi hóa đơn phải được thanh toán trong 30 ngày.', '/pˈeɪəbəl/', 'adj.', 'invoice', 'TOEIC'),
  ('receivable', 'khoản phải thu', 'Accounts receivable rose after the holiday season.', 'Khoản phải thu tăng sau mùa lễ.', '/ɹɪsˈivəbəl/', 'n.', 'invoice', 'TOEIC'),
  ('statement', 'sao kê', 'Your monthly bank statement arrives by email.', 'Sao kê ngân hàng hàng tháng được gửi qua email.', '/stˈeɪtmənt/', 'n.', 'invoice', 'TOEIC'),
  ('balance', 'số dư', 'The account balance is lower than last week.', 'Số dư tài khoản thấp hơn tuần trước.', '/ˈbæləns/', 'n.', 'budget', 'TOEIC'),
  ('deposit', 'tiền đặt cọc', 'A deposit of 50 dollars holds the meeting room.', 'Khoản đặt cọc 50 đô la giữ chỗ phòng họp.', '/dɪˈpɒzɪt/', 'n.', 'budget', 'TOEIC'),
  ('withdraw', 'rút tiền', 'You can withdraw cash from any partner bank.', 'Bạn có thể rút tiền mặt tại bất kỳ ngân hàng đối tác nào.', '/wɪðˈdɹɔː/', 'v.', 'budget', 'TOEIC'),
  ('interest', 'lãi suất', 'The loan carries a low interest rate.', 'Khoản vay có lãi suất thấp.', '/ˈɪntəɹɪst/', 'n.', 'budget', 'TOEIC'),
  ('loan', 'khoản vay', 'The bank approved a loan for new equipment.', 'Ngân hàng đã duyệt khoản vay để mua thiết bị mới.', '/lˈoʊn/', 'n.', 'budget', 'TOEIC'),
  ('mortgage', 'khoản thế chấp nhà', 'They applied for a mortgage on the new office.', 'Họ nộp hồ sơ thế chấp cho văn phòng mới.', '/mˈɔɹɡədʒ/', 'n.', 'budget', 'TOEIC'),
  ('dividend', 'cổ tức', 'Shareholders will receive a dividend in June.', 'Cổ đông sẽ nhận cổ tức vào tháng Sáu.', '/dˈɪvɪdˌɛnd/', 'n.', 'budget', 'TOEIC'),
  ('capital', 'vốn', 'The startup needs more capital to expand.', 'Công ty khởi nghiệp cần thêm vốn để mở rộng.', '/ˈkæp.ɪ.təl/', 'n.', 'budget', 'TOEIC'),
  ('investment', 'khoản đầu tư', 'This investment should grow over five years.', 'Khoản đầu tư này sẽ tăng trong năm năm.', '/ɪnˈvɛsmənt/', 'n.', 'budget', 'TOEIC'),
  ('shareholder', 'cổ đông', 'Each shareholder will vote at the annual meeting.', 'Mỗi cổ đông sẽ bỏ phiếu tại cuộc họp thường niên.', '/ʃˈɛɹhˌoʊldɚ/', 'n.', 'budget', 'TOEIC'),
  ('stock', 'cổ phiếu', 'Company stock rose after the product launch.', 'Cổ phiếu công ty tăng sau khi ra mắt sản phẩm.', '/stˈɑk/', 'n.', 'budget', 'TOEIC'),
  ('bond', 'trái phiếu', 'The city issued a bond to repair the bridge.', 'Thành phố phát hành trái phiếu để sửa cầu.', '/bɒnd/', 'n.', 'budget', 'TOEIC'),
  ('merger', 'sáp nhập', 'The merger of the two banks will take six months.', 'Việc sáp nhập hai ngân hàng sẽ mất sáu tháng.', '/mˈɝdʒɚ/', 'n.', 'budget', 'TOEIC'),
  ('acquisition', 'thâu tóm / mua lại', 'The acquisition added three factories to the group.', 'Thương vụ mua lại bổ sung ba nhà máy cho tập đoàn.', '/ˌækwəzˈɪʃən/', 'n.', 'budget', 'TOEIC'),
  ('asset', 'tài sản', 'The warehouse is the company''s largest asset.', 'Kho hàng là tài sản lớn nhất của công ty.', '/ˈæsˌɛt/', 'n.', 'budget', 'TOEIC'),
  ('liability', 'nợ phải trả', 'Long-term liability appears on the balance sheet.', 'Nợ dài hạn xuất hiện trên bảng cân đối kế toán.', '/laɪəˈbɪlɪti/', 'n.', 'budget', 'TOEIC'),
  ('equity', 'vốn chủ sở hữu', 'Owners'' equity increased after the profitable year.', 'Vốn chủ sở hữu tăng sau năm có lãi.', '/ˈɛk.wɪ.ti/', 'n.', 'budget', 'TOEIC'),
  ('payroll', 'bảng lương', 'Payroll is processed every other Friday.', 'Bảng lương được xử lý vào thứ Sáu cách tuần.', '/pˈeɪɹˌoʊl/', 'n.', 'budget', 'TOEIC'),
  ('pension', 'lương hưu', 'Employees join the pension plan after one year.', 'Nhân viên tham gia quỹ lương hưu sau một năm.', '/pˈɛnʃən/', 'n.', 'budget', 'TOEIC'),
  ('compensation', 'thù lao', 'Total compensation includes salary and health insurance.', 'Tổng thù lao gồm lương và bảo hiểm y tế.', '/ˌkɒmpɛnˈseɪʃən/', 'n.', 'budget', 'TOEIC'),
  ('bonus', 'tiền thưởng', 'The sales team earned a year-end bonus.', 'Nhóm bán hàng nhận thưởng cuối năm.', '/ˈbəʊ.nəs/', 'n.', 'budget', 'TOEIC'),
  ('allowance', 'trợ cấp', 'Staff receive a monthly travel allowance.', 'Nhân viên nhận trợ cấp đi lại hàng tháng.', '/əˈlaʊəns/', 'n.', 'budget', 'TOEIC'),
  ('subsidy', 'trợ cấp (nhà nước)', 'The factory received a subsidy for cleaner energy.', 'Nhà máy nhận trợ cấp cho năng lượng sạch hơn.', '/ˈsʌbsɨdi/', 'n.', 'budget', 'TOEIC'),
  ('grant', 'khoản tài trợ', 'The city awarded a grant for job training.', 'Thành phố cấp khoản tài trợ cho đào tạo việc làm.', '/ɡɹɑːnt/', 'n.', 'budget', 'TOEIC'),
  ('fund', 'quỹ', 'The emergency fund covers unexpected repairs.', 'Quỹ khẩn cấp chi cho các sửa chữa bất ngờ.', '/ˈfʌnd/', 'n.', 'budget', 'TOEIC'),
  ('surplus', 'thặng dư', 'The department ended the year with a surplus.', 'Phòng ban kết thúc năm với thặng dư.', '/ˈsɜːpləs/', 'n.', 'budget', 'TOEIC'),
  ('deficit', 'thâm hụt', 'A budget deficit forced the city to cut overtime.', 'Thâm hụt ngân sách buộc thành phố cắt giờ làm thêm.', '/ˈdɛfɪsɪt/', 'n.', 'budget', 'TOEIC'),
  ('bankrupt', 'phá sản', 'The airline went bankrupt after fuel prices rose.', 'Hãng hàng không phá sản sau khi giá nhiên liệu tăng.', '/ˈbæŋ.kɹəpt/', 'adj.', 'budget', 'TOEIC'),
  ('lucrative', 'sinh lợi', 'Online courses became a lucrative side business.', 'Khóa học trực tuyến trở thành việc phụ sinh lợi.', '/lˈukɹətɪv/', 'adj.', 'budget', 'TOEIC'),
  ('economical', 'tiết kiệm', 'This printer is more economical than the old model.', 'Máy in này tiết kiệm hơn mẫu cũ.', '/ˌɛkəˈnɒmɪkəl/', 'adj.', 'budget', 'TOEIC'),
  ('affordable', 'vừa túi tiền', 'The hotel offers affordable rooms near the airport.', 'Khách sạn có phòng vừa túi tiền gần sân bay.', '/əfˈɔɹdəbəl/', 'adj.', 'budget', 'TOEIC'),
  ('costly', 'tốn kém', 'A delayed shipment can be a costly mistake.', 'Lô hàng chậm có thể là sai lầm tốn kém.', '/kˈɑstli/', 'adj.', 'budget', 'TOEIC'),
  ('currency', 'tiền tệ', 'Please pay in local currency at the front desk.', 'Vui lòng thanh toán bằng tiền địa phương tại quầy lễ tân.', '/kˈɝənsi/', 'n.', 'budget', 'TOEIC'),
  ('exchange', 'tỷ giá / đổi tiền', 'The exchange rate is posted in the lobby.', 'Tỷ giá được niêm yết ở sảnh.', '/ɛksˈtʃeɪndʒ/', 'n.', 'budget', 'TOEIC'),
  ('wholesale', 'bán sỉ', 'Wholesale prices are lower than retail prices.', 'Giá sỉ thấp hơn giá bán lẻ.', '/ˈhoʊlseɪl/', 'adj.', 'budget', 'TOEIC'),
  ('retail', 'bán lẻ', 'Retail sales usually rise in December.', 'Doanh số bán lẻ thường tăng vào tháng 12.', '/ɹˈitˌeɪl/', 'n.', 'budget', 'TOEIC'),
  ('bargain', 'món hời', 'This printer is a bargain at the sale price.', 'Máy in này là món hời với giá khuyến mãi.', '/bˈɑɹɡən/', 'n.', 'budget', 'TOEIC'),
  ('quarterly', 'hàng quý', 'Managers submit a quarterly sales report.', 'Quản lý nộp báo cáo doanh số hàng quý.', '/kwˈɔɹtɚli/', 'adj.', 'budget', 'TOEIC'),
  ('annually', 'hàng năm', 'The safety course is required annually.', 'Khóa an toàn phải học hàng năm.', '/ˈænjuəli/', 'adv.', 'deadline', 'TOEIC'),
  ('postpone', 'hoãn', 'We will postpone the meeting until Thursday.', 'Chúng tôi sẽ hoãn cuộc họp đến thứ Năm.', '/poʊstˈpoʊn/', 'v.', 'deadline', 'TOEIC'),
  ('expire', 'hết hạn', 'Your membership will expire at the end of May.', 'Thẻ thành viên sẽ hết hạn vào cuối tháng Năm.', '/ɪkspˈaɪɹ/', 'v.', 'deadline', 'TOEIC'),
  ('extend', 'gia hạn / kéo dài', 'The client asked us to extend the contract.', 'Khách hàng nhờ chúng tôi gia hạn hợp đồng.', '/ɛkˈstɛnd/', 'v.', 'deadline', 'TOEIC'),
  ('renew', 'gia hạn lại', 'Please renew your parking permit before Friday.', 'Vui lòng gia hạn thẻ gửi xe trước thứ Sáu.', '/ɹɪnˈu/', 'v.', 'deadline', 'TOEIC'),
  ('schedule', 'lịch', 'The train schedule is posted at the station.', 'Lịch tàu được dán tại ga.', '/skˈɛdʒʊl/', 'n.', 'deadline', 'TOEIC'),
  ('promptly', 'ngay lập tức / đúng giờ', 'Please reply promptly to the client''s email.', 'Vui lòng trả lời email khách hàng ngay.', '/pɹˈɑmptli/', 'adv.', 'deadline', 'TOEIC'),
  ('immediately', 'ngay lập tức', 'Call the supervisor immediately if a machine stops.', 'Gọi quản sát ngay nếu máy dừng.', '/əˈmiːdi.ətli/', 'adv.', 'deadline', 'TOEIC'),
  ('currently', 'hiện nay', 'The position is currently open to internal staff.', 'Vị trí hiện đang mở cho nhân viên nội bộ.', '/kˈɝəntli/', 'adv.', 'deadline', 'TOEIC'),
  ('recently', 'gần đây', 'The company recently opened a branch in Da Nang.', 'Công ty gần đây mở chi nhánh ở Đà Nẵng.', '/ˈɹiːsəntli/', 'adv.', 'deadline', 'TOEIC'),
  ('duration', 'thời lượng', 'The workshop has a duration of three hours.', 'Hội thảo kéo dài ba giờ.', '/dˈʊɹˈeɪʃən/', 'n.', 'deadline', 'TOEIC'),
  ('period', 'giai đoạn', 'The trial period lasts 30 days.', 'Giai đoạn dùng thử kéo dài 30 ngày.', '/pˈɪɹiəd/', 'n.', 'deadline', 'TOEIC'),
  ('extension', 'sự gia hạn', 'We were given a two-week extension on the report.', 'Chúng tôi được gia hạn báo cáo thêm hai tuần.', '/ɪkˈstɛnʃən/', 'n.', 'deadline', 'TOEIC'),
  ('adjourn', 'tạm nghỉ (cuộc họp)', 'The chair voted to adjourn the meeting at noon.', 'Chủ tọa biểu quyết tạm nghỉ cuộc họp lúc trưa.', '/ədʒˈɝn/', 'v.', 'deadline', 'TOEIC'),
  ('urgent', 'khẩn cấp', 'This is an urgent request from the legal team.', 'Đây là yêu cầu khẩn từ nhóm pháp chế.', '/ˈɝdʒənt/', 'adj.', 'deadline', 'TOEIC'),
  ('timely', 'đúng lúc', 'Timely delivery keeps our customers satisfied.', 'Giao hàng đúng lúc giúp khách hài lòng.', '/tˈaɪmli/', 'adj.', 'deadline', 'TOEIC'),
  ('tentative', 'tạm thời / chưa chốt', 'Friday is a tentative date for the launch.', 'Thứ Sáu là ngày dự kiến cho buổi ra mắt.', '/tˈɛntətɪv/', 'adj.', 'deadline', 'TOEIC'),
  ('shortly', 'chẳng bao lâu nữa', 'The next bus will arrive shortly.', 'Chuyến xe buýt tiếp theo sẽ đến chẳng bao lâu nữa.', '/ʃˈɔɹtli/', 'adv.', 'deadline', 'TOEIC'),
  ('meanwhile', 'trong lúc đó', 'Meanwhile, please wait in the lobby.', 'Trong lúc đó, vui lòng chờ ở sảnh.', '/mˈinwˌaɪl/', 'adv.', 'deadline', 'TOEIC'),
  ('resume', 'sơ yếu lý lịch', 'Please attach your résumé to the application form.', 'Vui lòng đính kèm sơ yếu lý lịch vào đơn ứng tuyển.', '/ˈrez.ə.meɪ/', 'n.', 'applicant', 'TOEIC'),
  ('interview', 'phỏng vấn', 'Her interview is scheduled for 9 a.m. tomorrow.', 'Buổi phỏng vấn của cô ấy lúc 9 giờ sáng mai.', '/ˈɪntɚvjˌu/', 'n.', 'applicant', 'TOEIC'),
  ('recruit', 'tuyển dụng', 'The firm will recruit five engineers this spring.', 'Công ty sẽ tuyển năm kỹ sư vào mùa xuân này.', '/ɹɪˈkɹuːt/', 'v.', 'applicant', 'TOEIC'),
  ('hire', 'thuê / tuyển', 'We hope to hire a receptionist next week.', 'Chúng tôi hy vọng tuyển lễ tân vào tuần tới.', '/haɪə/', 'v.', 'applicant', 'TOEIC'),
  ('resign', 'từ chức', 'He will resign from the board in March.', 'Ông ấy sẽ từ chức khỏi hội đồng vào tháng Ba.', '/ɹɪzˈaɪn/', 'v.', 'applicant', 'TOEIC'),
  ('retire', 'nghỉ hưu', 'She plans to retire after 30 years at the bank.', 'Cô ấy định nghỉ hưu sau 30 năm làm ở ngân hàng.', '/ɹɪtˈaɪɹ/', 'v.', 'applicant', 'TOEIC'),
  ('promote', 'thăng chức', 'The company will promote two supervisors in June.', 'Công ty sẽ thăng chức hai quản sát vào tháng Sáu.', '/pɹəˈməʊt/', 'v.', 'applicant', 'TOEIC'),
  ('intern', 'thực tập sinh', 'The intern is learning how to file invoices.', 'Thực tập sinh đang học cách lưu hóa đơn.', '/ˈɪntɚn/', 'n.', 'applicant', 'TOEIC'),
  ('trainee', 'nhân viên tập sự', 'Each trainee shadows a senior technician.', 'Mỗi nhân viên tập sự theo kèm một kỹ thuật viên kỳ cựu.', '/tɹˈeɪnˈi/', 'n.', 'applicant', 'TOEIC'),
  ('vacancy', 'vị trí trống', 'There is a vacancy in the accounting department.', 'Có một vị trí trống ở phòng kế toán.', '/vˈeɪkənsi/', 'n.', 'applicant', 'TOEIC'),
  ('qualification', 'bằng cấp / năng lực', 'This job requires a qualification in accounting.', 'Công việc này yêu cầu bằng kế toán.', '/kwˌɑləfəkˈeɪʃən/', 'n.', 'applicant', 'TOEIC'),
  ('reference', 'người tham chiếu', 'Please provide two professional references.', 'Vui lòng cung cấp hai người tham chiếu nghề nghiệp.', '/ɹˈɛfɚəns/', 'n.', 'applicant', 'TOEIC'),
  ('recommendation', 'thư giới thiệu', 'Her manager wrote a strong recommendation.', 'Quản lý của cô ấy viết thư giới thiệu tốt.', '/ɹˌɛkəməndˈeɪʃən/', 'n.', 'applicant', 'TOEIC'),
  ('orientation', 'hướng dẫn nhập việc', 'New staff attend orientation on Monday morning.', 'Nhân viên mới tham gia hướng dẫn nhập việc sáng thứ Hai.', '/ˌɔɹiɛntˈeɪʃən/', 'n.', 'applicant', 'TOEIC'),
  ('probation', 'thử việc', 'The probation period lasts three months.', 'Thời gian thử việc kéo dài ba tháng.', '/pɹoʊbˈeɪʃən/', 'n.', 'applicant', 'TOEIC'),
  ('evaluate', 'đánh giá', 'Supervisors evaluate performance twice a year.', 'Quản sát đánh giá hiệu suất hai lần mỗi năm.', '/ɨˈvaljʊeɪt/', 'v.', 'applicant', 'TOEIC'),
  ('appraisal', 'đánh giá nhân sự', 'Your annual appraisal is on Thursday.', 'Buổi đánh giá năm của bạn vào thứ Năm.', '/əˈpɹeɪzəl/', 'n.', 'applicant', 'TOEIC'),
  ('candidate', 'ứng cử viên', 'The strongest candidate has hotel experience.', 'Ứng viên mạnh nhất có kinh nghiệm khách sạn.', '/ˈkæn.dɪdət/', 'n.', 'applicant', 'TOEIC'),
  ('credential', 'chứng chỉ / giấy tờ năng lực', 'Please bring a copy of your teaching credential.', 'Vui lòng mang bản sao chứng chỉ giảng dạy.', '/kɹɪdˈɛnʃəl/', 'n.', 'applicant', 'TOEIC'),
  ('supervisor', 'người giám sát', 'Ask your supervisor before changing the shift.', 'Hãy hỏi người giám sát trước khi đổi ca.', '/ˈsuːpɚˌvaɪzɚ/', 'n.', 'employee', 'TOEIC'),
  ('colleague', 'đồng nghiệp', 'Please copy your colleague on the email.', 'Vui lòng gửi kèm đồng nghiệp vào email.', '/ˈkɒliːɡ/', 'n.', 'employee', 'TOEIC'),
  ('personnel', 'nhân sự', 'All personnel must wear a badge in the factory.', 'Mọi nhân sự phải đeo thẻ trong nhà máy.', '/ˌpɝː.səˈnel/', 'n.', 'employee', 'TOEIC'),
  ('staff', 'nhân viên (tập thể)', 'The hotel staff were polite and efficient.', 'Nhân viên khách sạn lịch sự và làm việc nhanh.', '/ˈstæf/', 'n.', 'employee', 'TOEIC'),
  ('workforce', 'lực lượng lao động', 'The workforce grew after the new plant opened.', 'Lực lượng lao động tăng sau khi nhà máy mới mở.', '/wˈɝkfˌɔɹs/', 'n.', 'employee', 'TOEIC'),
  ('occupation', 'nghề nghiệp', 'Please state your occupation on the form.', 'Vui lòng ghi nghề nghiệp trên mẫu đơn.', '/ˌɑkjəpˈeɪʃən/', 'n.', 'employee', 'TOEIC'),
  ('career', 'sự nghiệp', 'She built a career in international sales.', 'Cô ấy gây dựng sự nghiệp trong bán hàng quốc tế.', '/kəˈɹɪə/', 'n.', 'employee', 'TOEIC'),
  ('salary', 'lương tháng', 'The starting salary is listed in the offer letter.', 'Mức lương khởi điểm được ghi trong thư mời nhận việc.', '/ˈsælɚi/', 'n.', 'employee', 'TOEIC'),
  ('wage', 'tiền công', 'Hourly wages increase after six months.', 'Tiền công theo giờ tăng sau sáu tháng.', '/weɪd͡ʒ/', 'n.', 'employee', 'TOEIC'),
  ('overtime', 'giờ làm thêm', 'Overtime must be approved by a manager.', 'Giờ làm thêm phải được quản lý phê duyệt.', '/ˈoʊvɚˌtaɪm/', 'n.', 'employee', 'TOEIC'),
  ('shift', 'ca làm', 'The night shift begins at 10 p.m.', 'Ca đêm bắt đầu lúc 10 giờ tối.', '/ʃɪft/', 'n.', 'employee', 'TOEIC'),
  ('commute', 'đi làm (đi về)', 'Many staff commute by train from the suburbs.', 'Nhiều nhân viên đi làm bằng tàu từ ngoại ô.', '/kəˈmjuːt/', 'v.', 'employee', 'TOEIC'),
  ('layoff', 'sa thải hàng loạt', 'The factory announced a layoff of 40 workers.', 'Nhà máy thông báo sa thải 40 công nhân.', '/lˈeɪˌɔf/', 'n.', 'employee', 'TOEIC'),
  ('downsize', 'tinh giản biên chế', 'The office will downsize after the merger.', 'Văn phòng sẽ tinh giản biên chế sau sáp nhập.', '/ˈdaʊnsaɪz/', 'v.', 'employee', 'TOEIC'),
  ('union', 'công đoàn', 'The union will vote on the new contract.', 'Công đoàn sẽ bỏ phiếu về hợp đồng mới.', '/ˈjuːnjən/', 'n.', 'employee', 'TOEIC'),
  ('benefit', 'phúc lợi', 'Health benefits begin on the first day of work.', 'Phúc lợi y tế bắt đầu từ ngày làm việc đầu tiên.', '/ˈbɛn.ɪ.fɪt/', 'n.', 'employee', 'TOEIC'),
  ('insurance', 'bảo hiểm', 'Travel insurance is included with the ticket.', 'Bảo hiểm du lịch đã gồm trong vé.', '/ɪn.ˈʃɔː.ɹəns/', 'n.', 'employee', 'TOEIC'),
  ('teamwork', 'làm việc nhóm', 'Good teamwork helped us finish before the deadline.', 'Làm việc nhóm tốt giúp chúng tôi xong trước hạn.', '/tˈimwˌɝk/', 'n.', 'employee', 'TOEIC'),
  ('collaboration', 'hợp tác', 'The project requires collaboration between two teams.', 'Dự án cần sự hợp tác giữa hai nhóm.', '/kəlˌæbɚˈeɪʃən/', 'n.', 'employee', 'TOEIC'),
  ('delegate', 'ủy thác công việc', 'Managers should delegate routine tasks.', 'Quản lý nên ủy thác các việc thường ngày.', '/dˈɛləɡˌeɪt/', 'v.', 'employee', 'TOEIC'),
  ('assign', 'giao việc', 'The lead will assign rooms to each guest.', 'Trưởng nhóm sẽ giao phòng cho từng khách.', '/əˈsaɪn/', 'v.', 'employee', 'TOEIC'),
  ('transfer', 'điều chuyển', 'She asked to transfer to the Seoul office.', 'Cô ấy xin điều chuyển sang văn phòng Seoul.', '/ˈtɹænzfɜː/', 'v.', 'employee', 'TOEIC'),
  ('dismiss', 'sa thải', 'The firm may dismiss staff who break safety rules.', 'Công ty có thể sa thải người vi phạm quy định an toàn.', '/dɪsmˈɪs/', 'v.', 'employee', 'TOEIC'),
  ('agenda', 'chương trình nghị sự', 'The agenda lists three items for discussion.', 'Chương trình nghị sự liệt kê ba mục cần thảo luận.', '/ədʒˈɛndə/', 'n.', 'conference', 'TOEIC'),
  ('minutes', 'biên bản cuộc họp', 'Please email the minutes after the meeting.', 'Vui lòng gửi biên bản sau cuộc họp.', '/mˈɪnəts/', 'n.', 'conference', 'TOEIC'),
  ('attend', 'tham dự', 'All managers must attend the safety briefing.', 'Mọi quản lý phải tham dự buổi phổ biến an toàn.', '/əˈtɛnd/', 'v.', 'conference', 'TOEIC'),
  ('participant', 'người tham dự', 'Each participant will receive a name badge.', 'Mỗi người tham dự sẽ nhận thẻ tên.', '/pɑɹtˈɪsəpənt/', 'n.', 'conference', 'TOEIC'),
  ('presenter', 'người thuyết trình', 'The presenter will answer questions at the end.', 'Người thuyết trình sẽ trả lời câu hỏi lúc cuối.', '/pɹˈɛzəntɚ/', 'n.', 'conference', 'TOEIC'),
  ('seminar', 'hội thảo chuyên đề', 'The tax seminar is open to small business owners.', 'Hội thảo thuế mở cho chủ doanh nghiệp nhỏ.', '/sˈɛmənˌɑɹ/', 'n.', 'conference', 'TOEIC'),
  ('workshop', 'buổi tập huấn', 'The design workshop lasts all afternoon.', 'Buổi tập huấn thiết kế kéo dài cả buổi chiều.', '/ˈwɜːk.ʃɒp/', 'n.', 'conference', 'TOEIC'),
  ('convention', 'đại hội / hội nghị ngành', 'The travel convention draws thousands of buyers.', 'Hội nghị du lịch thu hút hàng nghìn người mua.', '/kənvˈɛnʃən/', 'n.', 'conference', 'TOEIC'),
  ('exhibition', 'triển lãm', 'The furniture exhibition opens on Tuesday.', 'Triển lãm nội thất mở cửa vào thứ Ba.', '/ɛksɪˈbɪʃən/', 'n.', 'conference', 'TOEIC'),
  ('booth', 'gian hàng', 'Our booth is next to the main entrance.', 'Gian hàng của chúng tôi cạnh cửa chính.', '/buːð/', 'n.', 'conference', 'TOEIC'),
  ('announcement', 'thông báo', 'The announcement about the delay was posted online.', 'Thông báo về sự chậm trễ được đăng trực tuyến.', '/əˈnaʊns.mɛnt/', 'n.', 'conference', 'TOEIC'),
  ('propose', 'đề xuất', 'I propose that we hire a second receptionist.', 'Tôi đề xuất chúng ta thuê thêm một lễ tân.', '/pɹəˈpəʊz/', 'v.', 'conference', 'TOEIC'),
  ('suggest', 'gợi ý', 'The consultant suggested a shorter meeting.', 'Tư vấn viên gợi ý cuộc họp ngắn hơn.', '/sədʒˈɛst/', 'v.', 'conference', 'TOEIC'),
  ('recommend', 'khuyên dùng / giới thiệu', 'We recommend booking a table in advance.', 'Chúng tôi khuyên nên đặt bàn trước.', '/ɹˌɛkəmˈɛnd/', 'v.', 'conference', 'TOEIC'),
  ('approve', 'phê duyệt', 'The director must approve all travel requests.', 'Giám đốc phải phê duyệt mọi đề nghị đi công tác.', '/əpɹˈuv/', 'v.', 'conference', 'TOEIC'),
  ('reject', 'từ chối', 'The committee rejected the first design.', 'Ủy ban đã từ chối thiết kế đầu tiên.', '/ɹɪdʒˈɛkt/', 'v.', 'conference', 'TOEIC'),
  ('decline', 'từ chối (lịch sự)', 'She declined the invitation because of a conflict.', 'Cô ấy từ chối lời mời vì trùng lịch.', '/dɪˈklaɪn/', 'v.', 'conference', 'TOEIC'),
  ('accept', 'chấp nhận', 'Please accept our apology for the late delivery.', 'Xin hãy chấp nhận lời xin lỗi về việc giao hàng muộn.', '/æksˈɛpt/', 'v.', 'conference', 'TOEIC'),
  ('consider', 'cân nhắc', 'We will consider your offer this week.', 'Chúng tôi sẽ cân nhắc đề nghị của bạn trong tuần này.', '/kənˈsɪdə/', 'v.', 'conference', 'TOEIC'),
  ('review', 'xem xét lại', 'Please review the contract before you sign.', 'Vui lòng xem xét hợp đồng trước khi ký.', '/ɹɪˈvjuː/', 'v.', 'conference', 'TOEIC'),
  ('revise', 'sửa lại', 'The writer will revise the brochure tonight.', 'Người viết sẽ sửa lại tờ brochure tối nay.', '/ɹɪvˈaɪz/', 'v.', 'conference', 'TOEIC'),
  ('amend', 'sửa đổi (văn bản)', 'The board voted to amend the policy.', 'Hội đồng biểu quyết sửa đổi chính sách.', '/əˈmɛnd/', 'v.', 'conference', 'TOEIC'),
  ('draft', 'bản nháp', 'The first draft of the report is ready.', 'Bản nháp đầu của báo cáo đã xong.', '/dɹæft/', 'n.', 'conference', 'TOEIC'),
  ('submit', 'nộp', 'Please submit your timesheet by 5 p.m.', 'Vui lòng nộp bảng chấm công trước 5 giờ chiều.', '/səbˈmɪt/', 'v.', 'conference', 'TOEIC'),
  ('lecture', 'bài giảng', 'The guest lecture begins at 2 p.m.', 'Bài giảng khách mời bắt đầu lúc 2 giờ chiều.', '/lˈɛktʃɚ/', 'n.', 'conference', 'TOEIC'),
  ('facilitate', 'điều phối / tạo điều kiện', 'A trained host will facilitate the discussion.', 'Người dẫn đã được đào tạo sẽ điều phối thảo luận.', '/fəsˈɪlətˌeɪt/', 'v.', 'conference', 'TOEIC'),
  ('correspondence', 'thư từ', 'Please keep all client correspondence in this folder.', 'Vui lòng lưu mọi thư từ khách hàng trong thư mục này.', '/ˌkɒɹɪˈspɒndəns/', 'n.', 'memo', 'TOEIC'),
  ('enclose', 'đính kèm (trong thư)', 'We enclose a copy of the signed contract.', 'Chúng tôi đính kèm bản hợp đồng đã ký.', '/ɪnklˈoʊz/', 'v.', 'memo', 'TOEIC'),
  ('attach', 'đính kèm (file)', 'Please attach the spreadsheet to your reply.', 'Vui lòng đính kèm bảng tính vào thư trả lời.', '/ətˈætʃ/', 'v.', 'memo', 'TOEIC'),
  ('forward', 'chuyển tiếp', 'Forward the complaint to the customer service team.', 'Chuyển tiếp khiếu nại đến nhóm chăm sóc khách hàng.', '/ˈfoːwəd/', 'v.', 'memo', 'TOEIC'),
  ('reply', 'trả lời', 'I will reply to the vendor this afternoon.', 'Tôi sẽ trả lời nhà cung cấp chiều nay.', '/ɹɪˈplaɪ/', 'v.', 'memo', 'TOEIC'),
  ('inquire', 'hỏi thông tin', 'Call this number to inquire about vacancies.', 'Gọi số này để hỏi về vị trí trống.', '/ˌɪnkwˈaɪɹ/', 'v.', 'memo', 'TOEIC'),
  ('confirm', 'xác nhận', 'Please confirm your attendance by Wednesday.', 'Vui lòng xác nhận tham dự trước thứ Tư.', '/kənˈfɜːm/', 'v.', 'memo', 'TOEIC'),
  ('notify', 'thông báo cho', 'We will notify you when the package ships.', 'Chúng tôi sẽ thông báo khi kiện hàng được gửi.', '/nˈoʊtəfˌaɪ/', 'v.', 'memo', 'TOEIC'),
  ('remind', 'nhắc', 'This email is to remind you of tomorrow''s call.', 'Email này để nhắc bạn về cuộc gọi ngày mai.', '/ɹimˈaɪnd/', 'v.', 'memo', 'TOEIC'),
  ('request', 'yêu cầu', 'Guests may request a late checkout.', 'Khách có thể yêu cầu trả phòng muộn.', '/ɹɪˈkwɛst/', 'v.', 'memo', 'TOEIC'),
  ('require', 'đòi hỏi', 'This position requires two years of experience.', 'Vị trí này đòi hỏi hai năm kinh nghiệm.', '/ɹˌikwˈaɪɚ/', 'v.', 'memo', 'TOEIC'),
  ('document', 'tài liệu', 'Please sign the document in blue ink.', 'Vui lòng ký tài liệu bằng mực xanh.', '/ˈdɒkjʊmənt/', 'n.', 'memo', 'TOEIC'),
  ('report', 'báo cáo', 'The safety report lists three minor injuries.', 'Báo cáo an toàn nêu ba chấn thương nhẹ.', '/ɹəˈpoːt/', 'n.', 'memo', 'TOEIC'),
  ('survey', 'khảo sát', 'Please complete the customer survey after checkout.', 'Vui lòng hoàn thành khảo sát khách hàng sau khi trả phòng.', '/sɚvˈeɪ/', 'n.', 'memo', 'TOEIC'),
  ('questionnaire', 'bảng câu hỏi', 'The questionnaire takes about five minutes.', 'Bảng câu hỏi mất khoảng năm phút.', '/kwˌɛstʃənˈɛɹ/', 'n.', 'memo', 'TOEIC'),
  ('statistics', 'số liệu thống kê', 'The statistics show a rise in online orders.', 'Số liệu thống kê cho thấy đơn hàng trực tuyến tăng.', '/stətˈɪstɪks/', 'n.', 'memo', 'TOEIC'),
  ('chart', 'biểu đồ', 'This chart compares sales in four cities.', 'Biểu đồ này so sánh doanh số ở bốn thành phố.', '/tʃɑːt/', 'n.', 'memo', 'TOEIC'),
  ('graph', 'đồ thị', 'The graph shows a drop in energy use.', 'Đồ thị cho thấy mức dùng năng lượng giảm.', '/ɡɹæf/', 'n.', 'memo', 'TOEIC'),
  ('archive', 'lưu trữ', 'Please archive last year''s invoices.', 'Vui lòng lưu trữ hóa đơn năm ngoái.', '/ˈɑɹkˌaɪv/', 'v.', 'memo', 'TOEIC'),
  ('circular', 'thông tư / thư ngỏ', 'A circular was sent to every department.', 'Một thông tư đã được gửi tới mọi phòng ban.', '/sˈɝkjəlɚ/', 'n.', 'memo', 'TOEIC'),
  ('bulletin', 'bản tin', 'Check the staff bulletin for holiday hours.', 'Xem bản tin nhân viên để biết giờ lễ.', '/bˈʊlɪtən/', 'n.', 'memo', 'TOEIC'),
  ('notice', 'thông báo niêm yết', 'A notice on the door lists the new hours.', 'Tờ thông báo trên cửa ghi giờ mới.', '/nˈoʊtəs/', 'n.', 'memo', 'TOEIC'),
  ('department', 'phòng ban', 'The shipping department closes at 6 p.m.', 'Phòng vận chuyển đóng lúc 6 giờ chiều.', '/dɪpˈɑɹtmənt/', 'n.', 'headquarters', 'TOEIC'),
  ('division', 'khối / bộ phận', 'The electronics division moved to a new building.', 'Khối điện tử chuyển sang tòa nhà mới.', '/dɪˈvɪʒən/', 'n.', 'headquarters', 'TOEIC'),
  ('branch', 'chi nhánh', 'The bank will open a branch near the university.', 'Ngân hàng sẽ mở chi nhánh gần trường đại học.', '/bɹˈæntʃ/', 'n.', 'headquarters', 'TOEIC'),
  ('subsidiary', 'công ty con', 'The Japanese subsidiary reports to headquarters.', 'Công ty con tại Nhật báo cáo về trụ sở.', '/səbsˈɪdiˌɛɹi/', 'n.', 'headquarters', 'TOEIC'),
  ('affiliate', 'công ty liên kết', 'Our affiliate in Singapore handles regional sales.', 'Công ty liên kết ở Singapore phụ trách bán hàng khu vực.', '/əˈfɪl.i.et/', 'n.', 'headquarters', 'TOEIC'),
  ('client', 'khách hàng (dịch vụ)', 'The client asked for a revised proposal.', 'Khách hàng yêu cầu đề xuất đã chỉnh sửa.', '/klˈaɪənt/', 'n.', 'headquarters', 'TOEIC'),
  ('customer', 'khách hàng (mua hàng)', 'Every customer receives a printed receipt.', 'Mỗi khách hàng nhận biên lai in.', '/kˈʌstəmɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('supplier', 'nhà cung cấp', 'Our main supplier is based in Busan.', 'Nhà cung cấp chính của chúng tôi ở Busan.', '/səplˈaɪɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('vendor', 'nhà bán hàng', 'Please compare prices from three vendors.', 'Vui lòng so giá từ ba nhà bán.', '/vˈɛndɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('contractor', 'nhà thầu', 'The contractor will finish the lobby in June.', 'Nhà thầu sẽ xong sảnh vào tháng Sáu.', '/kˈɑntɹˌæktɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('consultant', 'tư vấn viên', 'A consultant reviewed our hiring process.', 'Một tư vấn viên đã rà soát quy trình tuyển dụng.', '/kənˈsʌltənt/', 'n.', 'headquarters', 'TOEIC'),
  ('executive', 'giám đốc điều hành', 'Senior executives will attend the dinner.', 'Các giám đốc cấp cao sẽ dự bữa tối.', '/ɪɡzˈɛkjətɪv/', 'n.', 'headquarters', 'TOEIC'),
  ('director', 'giám đốc', 'The finance director signed the budget.', 'Giám đốc tài chính đã ký ngân sách.', '/dɚˈɛktɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('manager', 'quản lý', 'Ask the duty manager if the room is ready.', 'Hỏi quản lý trực ca nếu phòng đã sẵn sàng.', '/mˈænədʒɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('assistant', 'trợ lý', 'The assistant booked the flights this morning.', 'Trợ lý đã đặt vé máy bay sáng nay.', '/əsˈɪstənt/', 'n.', 'headquarters', 'TOEIC'),
  ('secretary', 'thư ký', 'The secretary keeps the meeting calendar.', 'Thư ký giữ lịch họp.', '/ˈsɛk.ɹə.tɹi/', 'n.', 'headquarters', 'TOEIC'),
  ('clerk', 'nhân viên văn phòng', 'The clerk stamped the forms at the counter.', 'Nhân viên đóng dấu các mẫu đơn tại quầy.', '/klɐːk/', 'n.', 'headquarters', 'TOEIC'),
  ('receptionist', 'lễ tân', 'The receptionist will print your visitor badge.', 'Lễ tân sẽ in thẻ khách cho bạn.', '/ɹɪˈsɛpʃənɪst/', 'n.', 'headquarters', 'TOEIC'),
  ('cubicle', 'vách làm việc', 'Her cubicle is next to the copy machine.', 'Vách làm việc của cô ấy cạnh máy photocopy.', '/ˈkjubɪkəl/', 'n.', 'headquarters', 'TOEIC'),
  ('lobby', 'sảnh', 'Please wait in the lobby until your name is called.', 'Vui lòng chờ ở sảnh đến khi được gọi tên.', '/lˈɑbi/', 'n.', 'headquarters', 'TOEIC'),
  ('facility', 'cơ sở / nhà xưởng', 'The new facility can store 2,000 pallets.', 'Cơ sở mới chứa được 2.000 palet.', '/fəˈsɪlɪti/', 'n.', 'headquarters', 'TOEIC'),
  ('factory', 'nhà máy', 'The factory runs two shifts on weekdays.', 'Nhà máy chạy hai ca vào ngày thường.', '/fˈæktɚi/', 'n.', 'headquarters', 'TOEIC'),
  ('plant', 'nhà máy sản xuất', 'The chemical plant is closed for maintenance.', 'Nhà máy hóa chất đóng cửa để bảo trì.', '/plænt/', 'n.', 'headquarters', 'TOEIC'),
  ('corporation', 'tập đoàn', 'The corporation employs 8,000 people worldwide.', 'Tập đoàn thuê 8.000 người trên toàn cầu.', '/kˌɔɹpɚˈeɪʃən/', 'n.', 'headquarters', 'TOEIC'),
  ('enterprise', 'doanh nghiệp', 'Small enterprises can apply for the grant.', 'Doanh nghiệp nhỏ có thể xin khoản tài trợ.', '/ˈɛntɚˌpɹaɪz/', 'n.', 'headquarters', 'TOEIC'),
  ('warehouse', 'kho hàng', 'The warehouse is located near the port.', 'Kho hàng nằm gần cảng.', '/wˈɛɹhˌaʊs/', 'n.', 'shipment', 'TOEIC'),
  ('cargo', 'hàng hóa vận chuyển', 'The cargo was damaged during the storm.', 'Hàng hóa bị hư trong cơn bão.', '/kˈɑɹɡˌoʊ/', 'n.', 'shipment', 'TOEIC'),
  ('freight', 'cước vận tải', 'Freight costs rose after fuel prices increased.', 'Cước vận tải tăng sau khi giá nhiên liệu tăng.', '/fɹˈeɪt/', 'n.', 'shipment', 'TOEIC'),
  ('packing', 'đóng gói', 'Packing materials are stored in aisle B.', 'Vật liệu đóng gói được để ở lối B.', '/pˈækɪŋ/', 'n.', 'shipment', 'TOEIC'),
  ('carton', 'thùng carton', 'Each carton holds 24 bottles.', 'Mỗi thùng carton chứa 24 chai.', '/ˈkɑːtn̩/', 'n.', 'shipment', 'TOEIC'),
  ('pallet', 'palet', 'Please stack the boxes on a wooden pallet.', 'Vui lòng xếp thùng lên palet gỗ.', '/ˈpælət/', 'n.', 'shipment', 'TOEIC'),
  ('container', 'container', 'The container will leave the port on Friday.', 'Container sẽ rời cảng vào thứ Sáu.', '/kənˈteɪnə/', 'n.', 'shipment', 'TOEIC'),
  ('dock', 'bến tàu / bến xe tải', 'Trucks must wait at dock 4 for unloading.', 'Xe tải phải chờ ở bến 4 để dỡ hàng.', '/dˈɑk/', 'n.', 'shipment', 'TOEIC'),
  ('harbor', 'bến cảng', 'Fog delayed ships entering the harbor.', 'Sương mù làm chậm tàu vào bến cảng.', '/hˈɑɹbɚ/', 'n.', 'shipment', 'TOEIC'),
  ('port', 'cảng', 'The goods will clear customs at this port.', 'Hàng sẽ thông quan tại cảng này.', '/pɔːt/', 'n.', 'shipment', 'TOEIC'),
  ('customs', 'hải quan', 'Customs officers inspected the shipment.', 'Nhân viên hải quan đã kiểm tra lô hàng.', '/kˈʌstəmz/', 'n.', 'shipment', 'TOEIC'),
  ('inspect', 'kiểm tra', 'Technicians inspect every machine before shipping.', 'Kỹ thuật viên kiểm tra mọi máy trước khi gửi.', '/ˌɪnspˈɛkt/', 'v.', 'shipment', 'TOEIC'),
  ('arrive', 'đến', 'The overnight train will arrive at 6:40 a.m.', 'Chuyến tàu đêm sẽ đến lúc 6:40 sáng.', '/ɚˈaɪv/', 'v.', 'shipment', 'TOEIC'),
  ('depart', 'khởi hành', 'Buses depart from gate 12 every hour.', 'Xe buýt khởi hành từ cổng 12 mỗi giờ.', '/dɪˈpɑːt/', 'v.', 'shipment', 'TOEIC'),
  ('destination', 'điểm đến', 'Tokyo is the final destination of this flight.', 'Tokyo là điểm đến cuối của chuyến bay này.', '/dɛstɪˈneɪʃən/', 'n.', 'shipment', 'TOEIC'),
  ('origin', 'nơi xuất phát', 'The form asks for the origin of the goods.', 'Mẫu đơn hỏi nơi xuất phát của hàng.', '/ˈɔɹədʒən/', 'n.', 'shipment', 'TOEIC'),
  ('route', 'tuyến đường', 'This bus route stops near headquarters.', 'Tuyến xe buýt này dừng gần trụ sở.', '/ɹˈut/', 'n.', 'shipment', 'TOEIC'),
  ('carrier', 'hãng vận chuyển', 'Our carrier will pick up the pallets at noon.', 'Hãng vận chuyển sẽ lấy palet lúc trưa.', '/ˈkæ.ɹɪ.ə/', 'n.', 'shipment', 'TOEIC'),
  ('courier', 'chuyển phát nhanh', 'A courier delivered the contract this morning.', 'Chuyển phát nhanh đã giao hợp đồng sáng nay.', '/kˈɝiɚ/', 'n.', 'shipment', 'TOEIC'),
  ('deliver', 'giao hàng', 'We deliver office supplies within 24 hours.', 'Chúng tôi giao văn phòng phẩm trong 24 giờ.', '/dɪlˈɪvɚ/', 'v.', 'shipment', 'TOEIC'),
  ('consignment', 'lô hàng gửi', 'The consignment includes spare parts and manuals.', 'Lô hàng gửi gồm phụ tùng và sách hướng dẫn.', '/kənsˈaɪnmənt/', 'n.', 'shipment', 'TOEIC'),
  ('tracking', 'mã theo dõi', 'Use the tracking number to check delivery.', 'Dùng mã theo dõi để kiểm tra giao hàng.', '/tɹˈækɪŋ/', 'n.', 'shipment', 'TOEIC'),
  ('barcode', 'mã vạch', 'Scan the barcode to add the item to inventory.', 'Quét mã vạch để thêm mặt hàng vào tồn kho.', '/ˈbɑːr.koʊd/', 'n.', 'shipment', 'TOEIC'),
  ('load', 'chất hàng', 'Workers will load the truck after lunch.', 'Công nhân sẽ chất hàng lên xe sau bữa trưa.', '/lˈoʊd/', 'v.', 'shipment', 'TOEIC'),
  ('unload', 'dỡ hàng', 'Please unload the boxes at the back door.', 'Vui lòng dỡ thùng ở cửa sau.', '/ənlˈoʊd/', 'v.', 'shipment', 'TOEIC'),
  ('transit', 'trung chuyển', 'The package is still in transit.', 'Kiện hàng vẫn đang trung chuyển.', '/tɹˈænzɪt/', 'n.', 'shipment', 'TOEIC'),
  ('bulk', 'hàng số lượng lớn', 'Rice is shipped in bulk, not in cartons.', 'Gạo được gửi số lượng lớn, không đóng thùng.', '/bˈʌlk/', 'n.', 'shipment', 'TOEIC'),
  ('fragile', 'dễ vỡ', 'Mark the crate as fragile before shipping.', 'Ghi dễ vỡ trên thùng trước khi gửi.', '/ˈfɹædʒaɪl/', 'adj.', 'shipment', 'TOEIC'),
  ('perishable', 'dễ hỏng', 'Perishable food must stay in a cold truck.', 'Thực phẩm dễ hỏng phải để trên xe lạnh.', '/pˈɛɹɪʃəbəl/', 'adj.', 'shipment', 'TOEIC'),
  ('assemble', 'lắp ráp', 'Workers assemble the chairs on the second floor.', 'Công nhân lắp ráp ghế ở tầng hai.', '/əsˈɛmbəl/', 'v.', 'inventory', 'TOEIC'),
  ('manufacture', 'sản xuất', 'The plant can manufacture 500 units a day.', 'Nhà máy sản xuất được 500 chiếc mỗi ngày.', '/mˌænjəfˈæktʃɚ/', 'v.', 'inventory', 'TOEIC'),
  ('equipment', 'thiết bị', 'Safety equipment is required in this area.', 'Khu vực này bắt buộc dùng thiết bị an toàn.', '/ɪkwˈɪpmənt/', 'n.', 'inventory', 'TOEIC'),
  ('machinery', 'máy móc', 'The machinery will be replaced next year.', 'Máy móc sẽ được thay vào năm tới.', '/məʃˈinɚi/', 'n.', 'inventory', 'TOEIC'),
  ('defective', 'bị lỗi', 'Return any defective item within 30 days.', 'Trả lại mặt hàng lỗi trong vòng 30 ngày.', '/dɪfˈɛktɪv/', 'adj.', 'inventory', 'TOEIC'),
  ('warranty', 'bảo hành', 'The printer has a two-year warranty.', 'Máy in có bảo hành hai năm.', '/wˈɔɹənti/', 'n.', 'inventory', 'TOEIC'),
  ('guarantee', 'bảo đảm', 'The store offers a 90-day money-back guarantee.', 'Cửa hàng cam kết hoàn tiền trong 90 ngày.', '/ɡˌɛɹəntˈi/', 'n.', 'inventory', 'TOEIC'),
  ('maintenance', 'bảo trì', 'The elevator is closed for maintenance.', 'Thang máy đóng để bảo trì.', '/mˈeɪntənəns/', 'n.', 'inventory', 'TOEIC'),
  ('repair', 'sửa chữa', 'The repair will take two business days.', 'Việc sửa chữa mất hai ngày làm việc.', '/ɹɪpˈɛɹ/', 'n.', 'inventory', 'TOEIC'),
  ('replace', 'thay thế', 'We will replace the broken chair at no charge.', 'Chúng tôi sẽ thay ghế hỏng miễn phí.', '/ɹˌiplˈeɪs/', 'v.', 'inventory', 'TOEIC'),
  ('recycle', 'tái chế', 'Please recycle paper in the blue bin.', 'Vui lòng tái chế giấy ở thùng xanh.', '/ɹisˈaɪkəl/', 'v.', 'inventory', 'TOEIC'),
  ('dispose', 'vứt bỏ', 'Do not dispose of batteries in regular trash.', 'Không vứt pin vào rác thường.', '/dɪspˈoʊz/', 'v.', 'inventory', 'TOEIC'),
  ('material', 'nguyên liệu', 'Raw material arrived from the supplier today.', 'Nguyên liệu thô đến từ nhà cung cấp hôm nay.', '/məˈtɪəɹɪəl/', 'n.', 'inventory', 'TOEIC'),
  ('supply', 'nguồn cung', 'A shortage of supply delayed production.', 'Thiếu nguồn cung làm chậm sản xuất.', '/səplˈaɪ/', 'n.', 'inventory', 'TOEIC'),
  ('shortage', 'tình trạng thiếu', 'There is a shortage of trained nurses.', 'Đang thiếu y tá được đào tạo.', '/ʃˈɔɹtədʒ/', 'n.', 'inventory', 'TOEIC'),
  ('handle', 'xử lý / cầm nắm', 'Please handle glass bottles with care.', 'Vui lòng cầm chai thủy tinh cẩn thận.', '/hˈændəl/', 'v.', 'inventory', 'TOEIC'),
  ('spare', 'dự phòng', 'Keep a spare key at the front desk.', 'Giữ chìa khóa dự phòng ở quầy lễ tân.', '/spˈɛɹ/', 'adj.', 'inventory', 'TOEIC'),
  ('accommodation', 'chỗ ở', 'The city has limited accommodation during the festival.', 'Thành phố thiếu chỗ ở trong dịp lễ hội.', '/əkˌɑmədˈeɪʃən/', 'n.', 'reservation', 'TOEIC'),
  ('lodging', 'chỗ trọ', 'Lodging is included in the conference fee.', 'Chỗ trọ đã gồm trong phí hội nghị.', '/lˈɑdʒɪŋ/', 'n.', 'reservation', 'TOEIC'),
  ('suite', 'phòng suite', 'The suite has a meeting table and a kitchen.', 'Phòng suite có bàn họp và bếp.', '/swiːt/', 'n.', 'reservation', 'TOEIC'),
  ('vacant', 'còn trống', 'Two rooms are still vacant on the third floor.', 'Hai phòng tầng ba vẫn còn trống.', '/vˈeɪkənt/', 'adj.', 'reservation', 'TOEIC'),
  ('available', 'còn chỗ / có sẵn', 'The 3 p.m. tour is no longer available.', 'Tour 3 giờ chiều không còn chỗ.', '/əvˈeɪləbəl/', 'adj.', 'reservation', 'TOEIC'),
  ('luggage', 'hành lý', 'Please leave your luggage with the porter.', 'Vui lòng để hành lý cho nhân viên khuân vác.', '/lˈʌɡədʒ/', 'n.', 'reservation', 'TOEIC'),
  ('hospitality', 'lòng mến khách', 'The hotel is known for warm hospitality.', 'Khách sạn nổi tiếng vì lòng mến khách.', '/hˌɑspətˈæləti/', 'n.', 'reservation', 'TOEIC'),
  ('amenity', 'tiện nghi', 'Each room includes a coffee amenity kit.', 'Mỗi phòng có bộ tiện nghi pha cà phê.', '/əˈmiːnəti/', 'n.', 'reservation', 'TOEIC'),
  ('concierge', 'nhân viên hỗ trợ khách', 'The concierge can book a taxi to the airport.', 'Nhân viên hỗ trợ có thể đặt taxi ra sân bay.', '/ˌkɒn.siˈɛə̯ʒ/', 'n.', 'reservation', 'TOEIC'),
  ('housekeeping', 'bộ phận buồng phòng', 'Housekeeping will clean the room after 2 p.m.', 'Buồng phòng sẽ dọn phòng sau 2 giờ chiều.', '/hˈaʊskˌipɪŋ/', 'n.', 'reservation', 'TOEIC'),
  ('banquet', 'tiệc lớn', 'The awards banquet starts at 7 p.m.', 'Tiệc trao giải bắt đầu lúc 7 giờ tối.', '/bˈæŋkwət/', 'n.', 'reservation', 'TOEIC'),
  ('catering', 'dịch vụ ăn uống', 'Catering for 80 guests has already been arranged.', 'Dịch vụ ăn uống cho 80 khách đã được sắp xếp.', '/kˈeɪtɚɪŋ/', 'n.', 'reservation', 'TOEIC'),
  ('buffet', 'tiệc buffet', 'Breakfast is served as a buffet until 10 a.m.', 'Bữa sáng buffet phục vụ đến 10 giờ sáng.', '/bˈʌfət/', 'n.', 'reservation', 'TOEIC'),
  ('beverage', 'đồ uống', 'Hot beverages are free in the waiting lounge.', 'Đồ uống nóng miễn phí ở phòng chờ.', '/bˈɛvɚɪdʒ/', 'n.', 'complimentary', 'TOEIC'),
  ('appetizer', 'món khai vị', 'The chef recommends the soup as an appetizer.', 'Bếp trưởng gợi ý món súp làm khai vị.', '/ˈæpətˌaɪzɚ/', 'n.', 'complimentary', 'TOEIC'),
  ('dessert', 'món tráng miệng', 'Dessert is served after the main course.', 'Món tráng miệng được phục vụ sau món chính.', '/dɪzˈɝt/', 'n.', 'complimentary', 'TOEIC'),
  ('gratuity', 'tiền tip', 'An 18 percent gratuity is added for groups of six.', 'Nhóm từ sáu người bị cộng 18 phần trăm tiền tip.', '/ɡɹətˈuɪti/', 'n.', 'complimentary', 'TOEIC'),
  ('spacious', 'rộng rãi', 'The meeting hall is spacious enough for 200 seats.', 'Hội trường đủ rộng cho 200 ghế.', '/ˈspeɪʃəs/', 'adj.', 'occupancy', 'TOEIC'),
  ('renovated', 'được cải tạo', 'The renovated lobby opened last weekend.', 'Sảnh được cải tạo đã mở cửa cuối tuần trước.', '/ɹˈɛnəvˌeɪtɪd/', 'adj.', 'occupancy', 'TOEIC'),
  ('capacity', 'sức chứa', 'The hall has a capacity of 300 people.', 'Hội trường có sức chứa 300 người.', '/kəpˈæsəti/', 'n.', 'occupancy', 'TOEIC'),
  ('peak', 'cao điểm', 'Room rates are higher during peak season.', 'Giá phòng cao hơn vào mùa cao điểm.', '/pˈik/', 'adj.', 'occupancy', 'TOEIC'),
  ('refreshment', 'đồ giải khát', 'Refreshments will be served during the break.', 'Đồ giải khát sẽ được phục vụ trong giờ giải lao.', '/ɹəfɹˈɛʃmənt/', 'n.', 'complimentary', 'TOEIC'),
  ('courtesy', 'sự lịch sự / xe đưa đón miễn phí', 'A courtesy shuttle runs to the train station.', 'Xe đưa đón miễn phí chạy ra ga tàu.', '/kˈɝtəsi/', 'n.', 'complimentary', 'TOEIC'),
  ('included', 'đã bao gồm', 'Breakfast is included in the room rate.', 'Bữa sáng đã gồm trong giá phòng.', '/ˌɪnklˈudəd/', 'adj.', 'complimentary', 'TOEIC'),
  ('boarding', 'lên máy bay / lên tàu', 'Boarding begins 30 minutes before departure.', 'Lên máy bay bắt đầu 30 phút trước giờ khởi hành.', '/bˈɔɹdɪŋ/', 'n.', 'itinerary', 'TOEIC'),
  ('gate', 'cổng (sân bay)', 'The flight to Osaka leaves from gate 22.', 'Chuyến bay tới Osaka rời từ cổng 22.', '/ɡˈeɪt/', 'n.', 'itinerary', 'TOEIC'),
  ('terminal', 'nhà ga', 'International flights use terminal 2.', 'Chuyến bay quốc tế dùng nhà ga 2.', '/tˈɝmənəl/', 'n.', 'itinerary', 'TOEIC'),
  ('flight', 'chuyến bay', 'The morning flight was canceled because of fog.', 'Chuyến bay sáng bị hủy vì sương mù.', '/flˈaɪt/', 'n.', 'itinerary', 'TOEIC'),
  ('departure', 'chuyến đi / giờ khởi hành', 'The departure board shows a 20-minute delay.', 'Bảng khởi hành báo chậm 20 phút.', '/dɪpˈɑɹtʃɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('arrival', 'chuyến đến', 'Please wait in the arrival hall.', 'Vui lòng chờ ở sảnh đến.', '/ɚˈaɪvəl/', 'n.', 'itinerary', 'TOEIC'),
  ('fare', 'giá vé', 'The round-trip fare includes one checked bag.', 'Giá vé khứ hồi gồm một kiện hành lý ký gửi.', '/fˈɛɹ/', 'n.', 'itinerary', 'TOEIC'),
  ('passenger', 'hành khách', 'Each passenger must show a photo ID.', 'Mỗi hành khách phải xuất trình giấy tờ có ảnh.', '/pˈæsəndʒɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('ticket', 'vé', 'Please keep your ticket until you exit the station.', 'Vui lòng giữ vé đến khi ra khỏi ga.', '/tˈɪkət/', 'n.', 'itinerary', 'TOEIC'),
  ('passport', 'hộ chiếu', 'Your passport must be valid for six months.', 'Hộ chiếu phải còn hạn ít nhất sáu tháng.', '/pˈæspˌɔɹt/', 'n.', 'itinerary', 'TOEIC'),
  ('visa', 'thị thực', 'A tourist visa is required for this trip.', 'Chuyến đi này cần thị thực du lịch.', '/vˈizə/', 'n.', 'itinerary', 'TOEIC'),
  ('layover', 'điểm dừng nối chuyến', 'There is a two-hour layover in Seoul.', 'Có hai giờ dừng nối chuyến ở Seoul.', '/lˈeɪˌoʊvɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('aisle', 'lối đi', 'She asked for an aisle seat near the exit.', 'Cô ấy xin ghế cạnh lối đi gần cửa thoát hiểm.', '/ˈaɪl/', 'n.', 'itinerary', 'TOEIC'),
  ('sightseeing', 'tham quan', 'The afternoon is free for sightseeing.', 'Buổi chiều rảnh để tham quan.', '/sˈaɪtsˈiɪŋ/', 'n.', 'itinerary', 'TOEIC'),
  ('excursion', 'chuyến tham quan ngắn', 'The museum excursion leaves the hotel at 9 a.m.', 'Chuyến tham quan bảo tàng rời khách sạn lúc 9 giờ sáng.', '/ɪkskˈɝʒən/', 'n.', 'itinerary', 'TOEIC'),
  ('tour', 'tour', 'The walking tour of the old town lasts two hours.', 'Tour đi bộ phố cổ kéo dài hai giờ.', '/tˈʊɹ/', 'n.', 'itinerary', 'TOEIC'),
  ('souvenir', 'quà lưu niệm', 'The gift shop sells local souvenirs.', 'Cửa hàng quà bán đồ lưu niệm địa phương.', '/sˌuvənˈɪɹ/', 'n.', 'itinerary', 'TOEIC'),
  ('delay', 'sự chậm trễ', 'The delay was caused by heavy rain.', 'Sự chậm trễ do mưa lớn.', '/dɪlˈeɪ/', 'n.', 'itinerary', 'TOEIC'),
  ('connection', 'chuyến nối', 'You have 40 minutes to make your connection.', 'Bạn có 40 phút để kịp chuyến nối.', '/kənˈɛkʃən/', 'n.', 'itinerary', 'TOEIC'),
  ('permit', 'giấy phép', 'A parking permit is required in this garage.', 'Bãi xe này cần giấy phép đỗ.', '/pɚmˈɪt/', 'n.', 'authorize', 'TOEIC'),
  ('license', 'giấy phép hành nghề', 'The restaurant license must be displayed at the door.', 'Giấy phép nhà hàng phải được treo ở cửa.', '/lˈaɪsəns/', 'n.', 'authorize', 'TOEIC'),
  ('regulation', 'quy định', 'Safety regulations forbid open shoes in the plant.', 'Quy định an toàn cấm giày hở trong nhà máy.', '/ɹˌɛɡjəlˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('comply', 'tuân thủ', 'All vendors must comply with the new rules.', 'Mọi nhà bán phải tuân thủ quy định mới.', '/kəmplˈaɪ/', 'v.', 'authorize', 'TOEIC'),
  ('violate', 'vi phạm', 'Do not violate the quiet hours in the hotel.', 'Không vi phạm giờ yên lặng ở khách sạn.', '/vˈaɪəleɪt/', 'v.', 'authorize', 'TOEIC'),
  ('restrict', 'hạn chế', 'The city will restrict truck traffic downtown.', 'Thành phố sẽ hạn chế xe tải ở trung tâm.', '/ɹistɹˈɪkt/', 'v.', 'authorize', 'TOEIC'),
  ('prohibit', 'cấm', 'Signs prohibit smoking near the entrance.', 'Biển báo cấm hút thuốc gần cửa ra vào.', '/pɹoʊhˈɪbət/', 'v.', 'authorize', 'TOEIC'),
  ('eligible', 'đủ điều kiện', 'Staff with one year of service are eligible for the bonus.', 'Nhân viên làm đủ một năm mới đủ điều kiện nhận thưởng.', '/ˈɛlədʒəbəl/', 'adj.', 'authorize', 'TOEIC'),
  ('entitled', 'được hưởng', 'Full-time staff are entitled to paid leave.', 'Nhân viên toàn thời gian được hưởng nghỉ có lương.', '/ɛntˈaɪtəld/', 'adj.', 'authorize', 'TOEIC'),
  ('obligation', 'nghĩa vụ', 'The contract lists each party''s obligation.', 'Hợp đồng liệt kê nghĩa vụ của mỗi bên.', '/ˌɑbləɡˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('clause', 'điều khoản', 'Please read the cancellation clause carefully.', 'Vui lòng đọc kỹ điều khoản hủy.', '/klˈɔz/', 'n.', 'authorize', 'TOEIC'),
  ('terms', 'điều kiện hợp đồng', 'Payment terms are net 30 days.', 'Điều kiện thanh toán là 30 ngày.', '/tˈɝmz/', 'n.', 'authorize', 'TOEIC'),
  ('terminate', 'chấm dứt', 'Either side may terminate the agreement with 30 days'' notice.', 'Mỗi bên có thể chấm dứt thỏa thuận với thông báo 30 ngày.', '/tˈɝmənˌeɪt/', 'v.', 'authorize', 'TOEIC'),
  ('valid', 'còn hiệu lực', 'This coupon is valid until the end of March.', 'Phiếu này còn hiệu lực đến hết tháng Ba.', '/vˈælɪd/', 'adj.', 'authorize', 'TOEIC'),
  ('authentic', 'chính hãng / xác thực', 'Please buy authentic parts from our dealer.', 'Vui lòng mua linh kiện chính hãng từ đại lý.', '/əθˈɛntɪk/', 'adj.', 'authorize', 'TOEIC'),
  ('counterfeit', 'giả mạo', 'The store does not accept counterfeit bills.', 'Cửa hàng không nhận tiền giả.', '/kˈaʊntɚfˌɪt/', 'adj.', 'authorize', 'TOEIC'),
  ('signature', 'chữ ký', 'A manager''s signature is required on this form.', 'Mẫu này cần chữ ký của quản lý.', '/sˈɪɡnətʃɚ/', 'n.', 'authorize', 'TOEIC'),
  ('lawsuit', 'vụ kiện', 'The company settled the lawsuit last month.', 'Công ty đã hòa giải vụ kiện tháng trước.', '/lˈɔsˌut/', 'n.', 'authorize', 'TOEIC'),
  ('claim', 'yêu cầu bồi thường', 'File an insurance claim within 48 hours.', 'Nộp yêu cầu bồi thường bảo hiểm trong 48 giờ.', '/klˈeɪm/', 'n.', 'authorize', 'TOEIC'),
  ('policy', 'chính sách', 'The refund policy is printed on the receipt.', 'Chính sách hoàn tiền được in trên biên lai.', '/pˈɑləsi/', 'n.', 'authorize', 'TOEIC'),
  ('coverage', 'phạm vi bảo hiểm', 'The policy coverage includes fire and flood.', 'Phạm vi bảo hiểm gồm hỏa hoạn và lũ.', '/kˈʌvɚədʒ/', 'n.', 'authorize', 'TOEIC'),
  ('premium', 'phí bảo hiểm', 'The monthly premium will rise in January.', 'Phí bảo hiểm hàng tháng sẽ tăng vào tháng Giêng.', '/pɹˈimiəm/', 'n.', 'authorize', 'TOEIC'),
  ('deductible', 'mức tự trả', 'You pay the deductible before insurance covers the rest.', 'Bạn trả mức tự trả trước khi bảo hiểm chi phần còn lại.', '/dɪdˈʌktəbəl/', 'n.', 'authorize', 'TOEIC'),
  ('consent', 'sự đồng ý', 'Written consent is needed before we share your data.', 'Cần sự đồng ý bằng văn bản trước khi chúng tôi chia sẻ dữ liệu.', '/kənsˈɛnt/', 'n.', 'authorize', 'TOEIC'),
  ('advertise', 'quảng cáo', 'We will advertise the sale in the Sunday paper.', 'Chúng tôi sẽ quảng cáo đợt giảm giá trên báo Chủ nhật.', '/ˈædvɚtˌaɪz/', 'v.', 'brochure', 'TOEIC'),
  ('campaign', 'chiến dịch', 'The spring campaign will run for six weeks.', 'Chiến dịch mùa xuân sẽ chạy sáu tuần.', '/kæmpˈeɪn/', 'n.', 'brochure', 'TOEIC'),
  ('promotion', 'khuyến mãi', 'This promotion is valid in store only.', 'Khuyến mãi này chỉ áp dụng tại cửa hàng.', '/pɹəmˈoʊʃən/', 'n.', 'brochure', 'TOEIC'),
  ('slogan', 'khẩu hiệu', 'The new slogan appears on every poster.', 'Khẩu hiệu mới xuất hiện trên mọi poster.', '/slˈoʊɡən/', 'n.', 'brochure', 'TOEIC'),
  ('brand', 'thương hiệu', 'The brand is known for reliable printers.', 'Thương hiệu nổi tiếng với máy in bền.', '/bɹˈænd/', 'n.', 'brochure', 'TOEIC'),
  ('trademark', 'nhãn hiệu độc quyền', 'Do not copy the company''s trademark.', 'Không sao chép nhãn hiệu độc quyền của công ty.', '/tɹˈeɪdmˌɑɹk/', 'n.', 'brochure', 'TOEIC'),
  ('logo', 'biểu tượng', 'The logo must appear in the top left corner.', 'Biểu tượng phải nằm ở góc trên bên trái.', '/lˈoʊɡoʊ/', 'n.', 'brochure', 'TOEIC'),
  ('packaging', 'bao bì', 'The new packaging uses less plastic.', 'Bao bì mới dùng ít nhựa hơn.', '/pˈækɪdʒɪŋ/', 'n.', 'brochure', 'TOEIC'),
  ('consumer', 'người tiêu dùng', 'Consumers prefer products with clear labels.', 'Người tiêu dùng thích sản phẩm có nhãn rõ.', '/kənsˈumɚ/', 'n.', 'brochure', 'TOEIC'),
  ('competitor', 'đối thủ cạnh tranh', 'Our main competitor lowered its prices.', 'Đối thủ chính đã hạ giá.', '/kəmpˈɛtətɚ/', 'n.', 'brochure', 'TOEIC'),
  ('market', 'thị trường', 'The company entered the Korean market last year.', 'Công ty tiến vào thị trường Hàn Quốc năm ngoái.', '/mˈɑɹkət/', 'n.', 'brochure', 'TOEIC'),
  ('launch', 'ra mắt', 'We will launch the new phone in September.', 'Chúng tôi sẽ ra mắt điện thoại mới vào tháng Chín.', '/lˈɔntʃ/', 'v.', 'brochure', 'TOEIC'),
  ('sample', 'mẫu thử', 'Free samples are available at the booth.', 'Mẫu thử miễn phí có ở gian hàng.', '/sˈæmpəl/', 'n.', 'brochure', 'TOEIC'),
  ('catalog', 'danh mục sản phẩm', 'The spring catalog will be mailed next week.', 'Danh mục mùa xuân sẽ được gửi tuần tới.', '/kˈætəlɔɡ/', 'n.', 'brochure', 'TOEIC'),
  ('flyer', 'tờ rơi', 'Please hand a flyer to each visitor.', 'Vui lòng đưa tờ rơi cho mỗi khách.', '/flˈaɪɚ/', 'n.', 'brochure', 'TOEIC'),
  ('commercial', 'quảng cáo (TV/radio)', 'The radio commercial will air during the news.', 'Quảng cáo radio sẽ phát trong bản tin.', '/kəmˈɝʃəl/', 'n.', 'brochure', 'TOEIC'),
  ('publicity', 'truyền thông', 'The event received a lot of publicity.', 'Sự kiện được nhiều truyền thông đưa tin.', '/pəblˈɪsəti/', 'n.', 'brochure', 'TOEIC'),
  ('reputation', 'uy tín', 'The hotel has a reputation for clean rooms.', 'Khách sạn có uy tín về phòng sạch.', '/ɹˌɛpjətˈeɪʃən/', 'n.', 'brochure', 'TOEIC'),
  ('quality', 'chất lượng', 'We do not reduce quality to cut costs.', 'Chúng tôi không giảm chất lượng để cắt chi phí.', '/kwˈɑləti/', 'n.', 'brochure', 'TOEIC'),
  ('feature', 'tính năng', 'The main feature of this phone is the long battery.', 'Tính năng chính của điện thoại này là pin lâu.', '/fˈitʃɚ/', 'n.', 'brochure', 'TOEIC'),
  ('advantage', 'lợi thế', 'A downtown location is a clear advantage.', 'Vị trí trung tâm là lợi thế rõ ràng.', '/ædvˈæntɪdʒ/', 'n.', 'brochure', 'TOEIC'),
  ('drawback', 'nhược điểm', 'The only drawback is the limited parking.', 'Nhược điểm duy nhất là chỗ đỗ xe hạn chế.', '/dɹˈɔbˌæk/', 'n.', 'brochure', 'TOEIC'),
  ('trend', 'xu hướng', 'Remote work is a growing trend in this industry.', 'Làm việc từ xa là xu hướng tăng trong ngành này.', '/tɹˈɛnd/', 'n.', 'brochure', 'TOEIC'),
  ('innovative', 'đổi mới', 'The award honors innovative packaging design.', 'Giải thưởng vinh danh thiết kế bao bì đổi mới.', '/ˈɪnəvˌeɪtɪv/', 'adj.', 'brochure', 'TOEIC'),
  ('obsolete', 'lỗi thời', 'The old software is now obsolete.', 'Phần mềm cũ giờ đã lỗi thời.', '/ˈɑbsəlˌit/', 'adj.', 'brochure', 'TOEIC'),
  ('conventional', 'thông thường', 'We replaced conventional lights with LED lamps.', 'Chúng tôi thay đèn thông thường bằng đèn LED.', '/kənvˈɛnʃənəl/', 'adj.', 'brochure', 'TOEIC'),
  ('attractive', 'hấp dẫn', 'The package includes an attractive discount.', 'Gói dịch vụ gồm mức giảm giá hấp dẫn.', '/ətɹˈæktɪv/', 'adj.', 'brochure', 'TOEIC'),
  ('exclusive', 'độc quyền', 'Club members get exclusive early access.', 'Thành viên câu lạc bộ được quyền truy cập sớm độc quyền.', '/ɪksklˈusɪv/', 'adj.', 'brochure', 'TOEIC'),
  ('implement', 'triển khai', 'The office will implement a new booking system.', 'Văn phòng sẽ triển khai hệ thống đặt chỗ mới.', '/ˈɪmpləmənt/', 'v.', 'memo', 'TOEIC'),
  ('expand', 'mở rộng', 'The chain plans to expand into two more cities.', 'Chuỗi cửa hàng định mở rộng thêm hai thành phố.', '/ɪkspˈænd/', 'v.', 'headquarters', 'TOEIC'),
  ('reduce', 'giảm', 'Please reduce printing to save paper.', 'Vui lòng giảm in ấn để tiết kiệm giấy.', '/ɹədˈus/', 'v.', 'budget', 'TOEIC'),
  ('increase', 'tăng', 'Night flights will increase in July.', 'Chuyến bay đêm sẽ tăng vào tháng Bảy.', '/ˌɪnkɹˈis/', 'v.', 'itinerary', 'TOEIC'),
  ('improve', 'cải thiện', 'Training will improve customer service scores.', 'Đào tạo sẽ cải thiện điểm phục vụ khách.', '/ˌɪmpɹˈuv/', 'v.', 'employee', 'TOEIC'),
  ('operate', 'vận hành', 'The café operates from 7 a.m. to 8 p.m.', 'Quán cà phê vận hành từ 7 giờ sáng đến 8 giờ tối.', '/ˈɑpɚˌeɪt/', 'v.', 'reservation', 'TOEIC'),
  ('purchase', 'mua', 'You can purchase tickets at the kiosk.', 'Bạn có thể mua vé tại ki-ốt.', '/pˈɝtʃəs/', 'v.', 'invoice', 'TOEIC'),
  ('provide', 'cung cấp', 'The hotel will provide maps of the city.', 'Khách sạn sẽ cung cấp bản đồ thành phố.', '/pɹəvˈaɪd/', 'v.', 'reservation', 'TOEIC'),
  ('obtain', 'có được', 'You must obtain a visitor badge at reception.', 'Bạn phải lấy thẻ khách tại lễ tân.', '/əbtˈeɪn/', 'v.', 'authorize', 'TOEIC'),
  ('retain', 'giữ lại', 'Please retain your boarding pass until you exit.', 'Vui lòng giữ thẻ lên máy bay đến khi ra cửa.', '/ɹɪtˈeɪn/', 'v.', 'itinerary', 'TOEIC'),
  ('achieve', 'đạt được', 'The team achieved its sales target in May.', 'Nhóm đã đạt mục tiêu doanh số vào tháng Năm.', '/ətʃˈiv/', 'v.', 'budget', 'TOEIC'),
  ('exceed', 'vượt', 'Orders exceeded our estimate this quarter.', 'Đơn hàng vượt ước tính trong quý này.', '/ɪksˈid/', 'v.', 'budget', 'TOEIC'),
  ('fulfill', 'hoàn thành (đơn hàng)', 'We will fulfill all orders by Friday.', 'Chúng tôi sẽ hoàn thành mọi đơn trước thứ Sáu.', '/fʊlfˈɪl/', 'v.', 'shipment', 'TOEIC'),
  ('satisfy', 'làm hài lòng', 'A replacement part should satisfy the customer.', 'Linh kiện thay thế sẽ làm khách hài lòng.', '/sˈætəsfˌaɪ/', 'v.', 'inventory', 'TOEIC'),
  ('distribute', 'phân phối', 'Please distribute the agenda before the meeting.', 'Vui lòng phân phối chương trình họp trước giờ họp.', '/dɪstɹˈɪbjut/', 'v.', 'conference', 'TOEIC'),
  ('allocate', 'phân bổ', 'The board will allocate extra funds to training.', 'Hội đồng sẽ phân bổ thêm quỹ cho đào tạo.', '/ˈæləkˌeɪt/', 'v.', 'budget', 'TOEIC'),
  ('monitor', 'giám sát', 'Staff monitor the lobby cameras at night.', 'Nhân viên giám sát camera sảnh vào ban đêm.', '/mˈɑnətɚ/', 'v.', 'headquarters', 'TOEIC'),
  ('verify', 'xác minh', 'Please verify the address before shipping.', 'Vui lòng xác minh địa chỉ trước khi gửi hàng.', '/vˈɛɹəfˌaɪ/', 'v.', 'shipment', 'TOEIC'),
  ('identify', 'nhận diện', 'Guests must identify themselves at the gate.', 'Khách phải xuất trình danh tính ở cổng.', '/aɪdˈɛntəfˌaɪ/', 'v.', 'authorize', 'TOEIC'),
  ('specify', 'nêu rõ', 'Please specify the number of chairs you need.', 'Vui lòng nêu rõ số ghế bạn cần.', '/spˈɛsəfˌaɪ/', 'v.', 'memo', 'TOEIC'),
  ('indicate', 'chỉ ra', 'Arrows indicate the way to the exhibition hall.', 'Mũi tên chỉ đường tới hội trường triển lãm.', '/ˈɪndəkˌeɪt/', 'v.', 'conference', 'TOEIC'),
  ('ensure', 'đảm bảo', 'Please ensure that the door is locked.', 'Vui lòng đảm bảo cửa đã khóa.', '/ɛnʃˈʊɹ/', 'v.', 'authorize', 'TOEIC'),
  ('prevent', 'ngăn', 'Barriers prevent trucks from entering the plaza.', 'Rào chắn ngăn xe tải vào quảng trường.', '/pɹɪvˈɛnt/', 'v.', 'authorize', 'TOEIC'),
  ('avoid', 'tránh', 'Avoid calling clients during their lunch hour.', 'Tránh gọi khách trong giờ ăn trưa.', '/əvˈɔɪd/', 'v.', 'memo', 'TOEIC'),
  ('arrange', 'sắp xếp', 'I will arrange a taxi for the visiting team.', 'Tôi sẽ sắp xếp taxi cho đoàn khách.', '/ɚˈeɪndʒ/', 'v.', 'reservation', 'TOEIC'),
  ('prepare', 'chuẩn bị', 'Please prepare name cards for every guest.', 'Vui lòng chuẩn bị thẻ tên cho mọi khách.', '/pɹipˈɛɹ/', 'v.', 'conference', 'TOEIC'),
  ('complete', 'hoàn tất', 'Complete the form and leave it at the desk.', 'Hoàn tất mẫu đơn rồi để ở quầy.', '/kəmplˈit/', 'v.', 'memo', 'TOEIC'),
  ('accomplish', 'hoàn thành (nhiệm vụ)', 'We accomplished the move over the weekend.', 'Chúng tôi hoàn thành việc chuyển văn phòng trong cuối tuần.', '/əkˈɑmplɪʃ/', 'v.', 'headquarters', 'TOEIC'),
  ('perform', 'thực hiện', 'Technicians perform a safety check each morning.', 'Kỹ thuật viên thực hiện kiểm tra an toàn mỗi sáng.', '/pɚfˈɔɹm/', 'v.', 'inventory', 'TOEIC'),
  ('conduct', 'tiến hành', 'The firm will conduct interviews next week.', 'Công ty sẽ tiến hành phỏng vấn tuần tới.', '/kˈɑndəkt/', 'v.', 'applicant', 'TOEIC'),
  ('establish', 'thành lập', 'They plan to establish an office in Hanoi.', 'Họ định thành lập văn phòng ở Hà Nội.', '/ɪstˈæblɪʃ/', 'v.', 'headquarters', 'TOEIC'),
  ('introduce', 'giới thiệu', 'Let me introduce our new sales manager.', 'Xin giới thiệu quản lý bán hàng mới.', '/ˌɪntɹədˈus/', 'v.', 'employee', 'TOEIC'),
  ('announce', 'công bố', 'The airline will announce the new route tomorrow.', 'Hãng hàng không sẽ công bố tuyến mới vào ngày mai.', '/ənˈaʊns/', 'v.', 'itinerary', 'TOEIC'),
  ('negotiate', 'đàm phán', 'We will negotiate the price with the supplier.', 'Chúng tôi sẽ đàm phán giá với nhà cung cấp.', '/nəɡˈoʊʃiˌeɪt/', 'v.', 'budget', 'TOEIC'),
  ('compromise', 'sự thỏa hiệp', 'The two sides reached a compromise on overtime.', 'Hai bên đạt thỏa hiệp về giờ làm thêm.', '/kˈɑmpɹəmˌaɪz/', 'n.', 'employee', 'TOEIC'),
  ('settle', 'dàn xếp / thanh toán', 'Please settle your bill at the front desk.', 'Vui lòng thanh toán hóa đơn tại quầy lễ tân.', '/sˈɛtəl/', 'v.', 'invoice', 'TOEIC'),
  ('resolve', 'giải quyết', 'The manager resolved the complaint in one hour.', 'Quản lý giải quyết khiếu nại trong một giờ.', '/ɹizˈɑlv/', 'v.', 'employee', 'TOEIC'),
  ('coordinate', 'phối hợp', 'She will coordinate the movers and the IT team.', 'Cô ấy sẽ phối hợp đội chuyển nhà và nhóm IT.', '/koʊˈɔɹdənət/', 'v.', 'headquarters', 'TOEIC'),
  ('organize', 'tổ chức', 'The club will organize a job fair in April.', 'Câu lạc bộ sẽ tổ chức hội chợ việc làm vào tháng Tư.', '/ˈɔɹɡənˌaɪz/', 'v.', 'conference', 'TOEIC'),
  ('instruct', 'hướng dẫn', 'A trainer will instruct you on the new software.', 'Huấn luyện viên sẽ hướng dẫn bạn phần mềm mới.', '/ˌɪnstɹˈʌkt/', 'v.', 'employee', 'TOEIC'),
  ('inform', 'thông tin cho', 'Please inform reception if you will be late.', 'Vui lòng báo lễ tân nếu bạn đến muộn.', '/ˌɪnfˈɔɹm/', 'v.', 'memo', 'TOEIC'),
  ('update', 'cập nhật', 'Please update your contact details online.', 'Vui lòng cập nhật thông tin liên hệ trực tuyến.', '/əpdˈeɪt/', 'v.', 'memo', 'TOEIC'),
  ('upgrade', 'nâng cấp', 'Guests may upgrade to a suite for a small fee.', 'Khách có thể nâng cấp lên suite với phí nhỏ.', '/əpɡɹˈeɪd/', 'v.', 'reservation', 'TOEIC'),
  ('restore', 'khôi phục', 'Power was restored after two hours.', 'Điện được khôi phục sau hai giờ.', '/ɹɪstˈɔɹ/', 'v.', 'inventory', 'TOEIC'),
  ('retrieve', 'lấy lại', 'You can retrieve lost items at the information desk.', 'Bạn có thể lấy lại đồ thất lạc ở quầy thông tin.', '/ɹɪtɹˈiv/', 'v.', 'reservation', 'TOEIC'),
  ('compile', 'tổng hợp', 'Please compile the survey results by Monday.', 'Vui lòng tổng hợp kết quả khảo sát trước thứ Hai.', '/kəmpˈaɪl/', 'v.', 'memo', 'TOEIC'),
  ('summarize', 'tóm tắt', 'The last slide summarizes the main points.', 'Slide cuối tóm tắt các ý chính.', '/sˈʌmɚˌaɪz/', 'v.', 'conference', 'TOEIC'),
  ('outline', 'nêu đại cương', 'The letter outlines the new parking rules.', 'Lá thư nêu đại cương quy định đỗ xe mới.', '/ˈaʊtlˌaɪn/', 'v.', 'memo', 'TOEIC'),
  ('emphasize', 'nhấn mạnh', 'The speaker emphasized the need for safety glasses.', 'Diễn giả nhấn mạnh việc cần kính bảo hộ.', '/ˈɛmfəsˌaɪz/', 'v.', 'conference', 'TOEIC'),
  ('commit', 'cam kết', 'The city committed funds to the new terminal.', 'Thành phố cam kết quỹ cho nhà ga mới.', '/kəmˈɪt/', 'v.', 'budget', 'TOEIC'),
  ('assure', 'cam đoan', 'We assure guests that the water is safe.', 'Chúng tôi cam đoan với khách rằng nước an toàn.', '/əʃˈʊɹ/', 'v.', 'reservation', 'TOEIC'),
  ('efficient', 'hiệu quả', 'The new printer is faster and more efficient.', 'Máy in mới nhanh và hiệu quả hơn.', '/ɪfˈɪʃənt/', 'adj.', 'inventory', 'TOEIC'),
  ('reliable', 'đáng tin cậy', 'This courier is reliable for overnight delivery.', 'Hãng chuyển phát này đáng tin cho giao hàng qua đêm.', '/ɹɪlˈaɪəbəl/', 'adj.', 'shipment', 'TOEIC'),
  ('convenient', 'tiện lợi', 'The hotel is convenient for the convention center.', 'Khách sạn tiện cho trung tâm hội nghị.', '/kənvˈinjənt/', 'adj.', 'reservation', 'TOEIC'),
  ('essential', 'thiết yếu', 'A valid passport is essential for this trip.', 'Hộ chiếu còn hạn là thứ thiết yếu cho chuyến đi.', '/ɛsˈɛnʃəl/', 'adj.', 'itinerary', 'TOEIC'),
  ('mandatory', 'bắt buộc', 'A safety helmet is mandatory in the warehouse.', 'Mũ bảo hộ là bắt buộc trong kho.', '/mˈændətˌɔɹi/', 'adj.', 'authorize', 'TOEIC'),
  ('optional', 'không bắt buộc', 'The city tour is optional for conference guests.', 'Tour thành phố không bắt buộc với khách hội nghị.', '/ˈɑpʃənəl/', 'adj.', 'itinerary', 'TOEIC'),
  ('temporary', 'tạm thời', 'A temporary office is set up on the third floor.', 'Văn phòng tạm được bố trí ở tầng ba.', '/tˈɛmpɚˌɛɹi/', 'adj.', 'headquarters', 'TOEIC'),
  ('permanent', 'thường xuyên / lâu dài', 'She accepted a permanent position in accounting.', 'Cô ấy nhận vị trí chính thức ở phòng kế toán.', '/pˈɝmənənt/', 'adj.', 'applicant', 'TOEIC'),
  ('prior', 'trước đó', 'Prior experience with hotels is helpful.', 'Kinh nghiệm khách sạn trước đó sẽ hữu ích.', '/pɹˈaɪɚ/', 'adj.', 'applicant', 'TOEIC'),
  ('subsequent', 'tiếp theo', 'Subsequent meetings will be held online.', 'Các cuộc họp tiếp theo sẽ họp trực tuyến.', '/sˈʌbsəkwənt/', 'adj.', 'conference', 'TOEIC'),
  ('frequent', 'thường xuyên', 'Frequent travelers may join the loyalty club.', 'Khách đi thường xuyên có thể tham gia câu lạc bộ thành viên.', '/fɹˈikwənt/', 'adj.', 'itinerary', 'TOEIC'),
  ('adequate', 'đủ', 'Please bring an adequate number of chairs.', 'Vui lòng mang đủ số ghế.', '/ˈædəkwət/', 'adj.', 'conference', 'TOEIC'),
  ('insufficient', 'không đủ', 'There was insufficient parking for the event.', 'Chỗ đỗ xe không đủ cho sự kiện.', '/ˌɪnsəfˈɪʃənt/', 'adj.', 'occupancy', 'TOEIC'),
  ('substantial', 'đáng kể', 'The store reported a substantial rise in sales.', 'Cửa hàng báo doanh số tăng đáng kể.', '/səbstˈænʃəl/', 'adj.', 'budget', 'TOEIC'),
  ('moderate', 'vừa phải', 'Choose a hotel in the moderate price range.', 'Chọn khách sạn ở tầm giá vừa phải.', '/mˈɑdɚət/', 'adj.', 'reservation', 'TOEIC'),
  ('minimum', 'mức tối thiểu', 'The minimum order is 20 boxes.', 'Đơn hàng tối thiểu là 20 thùng.', '/mˈɪnəməm/', 'n.', 'inventory', 'TOEIC'),
  ('maximum', 'mức tối đa', 'The elevator has a maximum load of 800 kilograms.', 'Thang máy có tải tối đa 800 kg.', '/mˈæksəməm/', 'n.', 'occupancy', 'TOEIC'),
  ('approximately', 'khoảng', 'The taxi ride takes approximately 25 minutes.', 'Chuyến taxi mất khoảng 25 phút.', '/əpɹˈɑksəmətli/', 'adv.', 'itinerary', 'TOEIC'),
  ('particularly', 'đặc biệt', 'The restaurant is particularly busy on Fridays.', 'Nhà hàng đặc biệt đông vào thứ Sáu.', '/pˌɑɹtˈɪkjəlɚli/', 'adv.', 'complimentary', 'TOEIC'),
  ('successfully', 'thành công', 'The team successfully launched the new catalog.', 'Nhóm đã ra mắt danh mục mới thành công.', '/səksˈɛsfəli/', 'adv.', 'brochure', 'TOEIC'),
  ('gradually', 'dần dần', 'Prices will gradually increase over the year.', 'Giá sẽ tăng dần trong năm.', '/ɡɹˈædʒuəli/', 'adv.', 'budget', 'TOEIC'),
  ('highly', 'rất / hết sức', 'This course is highly recommended for new managers.', 'Khóa này rất được khuyên cho quản lý mới.', '/hˈaɪli/', 'adv.', 'employee', 'TOEIC'),
  ('thoroughly', 'kỹ lưỡng', 'Please check the figures thoroughly before you send them.', 'Vui lòng kiểm tra số liệu kỹ trước khi gửi.', '/θˈɝoʊli/', 'adv.', 'memo', 'TOEIC'),
  ('accordingly', 'theo đó', 'The flight was delayed; please wait accordingly.', 'Chuyến bay bị hoãn; vui lòng chờ theo đó.', '/əkˈɔɹdɪŋli/', 'adv.', 'itinerary', 'TOEIC'),
  ('therefore', 'do đó', 'The hall is full; therefore, extra chairs were added.', 'Hội trường đã đầy; do đó đã thêm ghế.', '/ðˈɛɹfˌɔɹ/', 'adv.', 'occupancy', 'TOEIC'),
  ('however', 'tuy nhiên', 'The room is small; however, it has a city view.', 'Phòng nhỏ; tuy nhiên có view thành phố.', '/hˌaʊˈɛvɚ/', 'adv.', 'reservation', 'TOEIC'),
  ('moreover', 'hơn nữa', 'The hotel is central; moreover, breakfast is included.', 'Khách sạn ở trung tâm; hơn nữa đã gồm bữa sáng.', '/mɔɹˈoʊvɚ/', 'adv.', 'complimentary', 'TOEIC'),
  ('nevertheless', 'dù vậy', 'The train was late; nevertheless, we arrived on time.', 'Tàu muộn; dù vậy chúng tôi vẫn tới đúng giờ.', '/nˌɛvɚðəlˈɛs/', 'adv.', 'deadline', 'TOEIC'),
  ('otherwise', 'nếu không', 'Please RSVP today; otherwise, we cannot hold the seat.', 'Vui lòng xác nhận hôm nay; nếu không chúng tôi không giữ chỗ.', '/ˈʌðɚwˌaɪz/', 'adv.', 'reservation', 'TOEIC');
