INSERT OR IGNORE INTO vocabulary (word, meaning, example, example_vi, phonetic, part_of_speech, image_key, category)
VALUES
  ('abide', 'tuân theo', 'Both sides must abide by the signed contract.', 'Cả hai bên phải tuân theo hợp đồng đã ký.', '/əbˈaɪd/', 'v.', 'authorize', 'TOEIC'),
  ('agreement', 'thỏa thuận', 'The agreement will take effect on Monday.', 'Thỏa thuận sẽ có hiệu lực vào thứ Hai.', '/əɡɹˈimənt/', 'n.', 'authorize', 'TOEIC'),
  ('assurance', 'sự bảo đảm', 'We need written assurance that the parts will arrive.', 'Chúng tôi cần bảo đảm bằng văn bản rằng linh kiện sẽ đến.', '/əʃˈʊɹəns/', 'n.', 'authorize', 'TOEIC'),
  ('cancellation', 'việc hủy', 'A late cancellation may incur a fee.', 'Hủy muộn có thể bị tính phí.', '/kˌænsəlˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('determine', 'xác định', 'Please determine the cause of the delay.', 'Vui lòng xác định nguyên nhân chậm trễ.', '/dətˈɝmən/', 'v.', 'deadline', 'TOEIC'),
  ('engage', 'thuê / cam kết', 'The firm will engage a lawyer for the case.', 'Công ty sẽ thuê luật sư cho vụ việc.', '/ɛnɡˈeɪdʒ/', 'v.', 'authorize', 'TOEIC'),
  ('obligate', 'ràng buộc nghĩa vụ', 'The clause does not obligate us to renew.', 'Điều khoản không ràng buộc chúng tôi phải gia hạn.', '/ˈɑbləɡˌeɪt/', 'v.', 'authorize', 'TOEIC'),
  ('party', 'bên (hợp đồng)', 'Each party must keep a signed copy.', 'Mỗi bên phải giữ một bản đã ký.', '/pˈɑɹti/', 'n.', 'authorize', 'TOEIC'),
  ('provision', 'điều khoản', 'This provision covers damage during shipping.', 'Điều khoản này gồm thiệt hại khi vận chuyển.', '/pɹəvˈɪʒən/', 'n.', 'authorize', 'TOEIC'),
  ('attract', 'thu hút', 'Bright signs attract visitors to the booth.', 'Biển sáng thu hút khách tới gian hàng.', '/ətɹˈækt/', 'v.', 'brochure', 'TOEIC'),
  ('compare', 'so sánh', 'Please compare these two printers before buying.', 'Vui lòng so sánh hai máy in này trước khi mua.', '/kəmpˈɛɹ/', 'v.', 'brochure', 'TOEIC'),
  ('competition', 'cạnh tranh', 'Competition in this market is very strong.', 'Cạnh tranh trên thị trường này rất mạnh.', '/kˌɑmpətˈɪʃən/', 'n.', 'brochure', 'TOEIC'),
  ('consume', 'tiêu thụ', 'The factory consumes less energy after the upgrade.', 'Nhà máy tiêu thụ ít năng lượng hơn sau khi nâng cấp.', '/kənsˈum/', 'v.', 'inventory', 'TOEIC'),
  ('convince', 'thuyết phục', 'The sample helped convince the buyer.', 'Mẫu thử giúp thuyết phục người mua.', '/kənvˈɪns/', 'v.', 'brochure', 'TOEIC'),
  ('inspiration', 'nguồn cảm hứng', 'The designer found inspiration in local crafts.', 'Nhà thiết kế tìm cảm hứng từ đồ thủ công địa phương.', '/ˌɪnspɚˈeɪʃən/', 'n.', 'brochure', 'TOEIC'),
  ('persuasion', 'sự thuyết phục', 'The ad relies on gentle persuasion, not pressure.', 'Quảng cáo dựa vào thuyết phục nhẹ, không ép.', '/pɚswˈeɪʒən/', 'n.', 'brochure', 'TOEIC'),
  ('productive', 'năng suất', 'The morning session was surprisingly productive.', 'Buổi sáng làm việc năng suất hơn mong đợi.', '/pɹədˈʌktɪv/', 'adj.', 'conference', 'TOEIC'),
  ('satisfaction', 'sự hài lòng', 'Customer satisfaction rose after the refund policy changed.', 'Sự hài lòng của khách tăng sau khi đổi chính sách hoàn tiền.', '/sˌætəsfˈækʃən/', 'n.', 'brochure', 'TOEIC'),
  ('characteristic', 'đặc điểm', 'Durability is a key characteristic of this brand.', 'Độ bền là đặc điểm then chốt của thương hiệu này.', '/kˌɛɹəktɚˈɪstɪk/', 'n.', 'brochure', 'TOEIC'),
  ('consequence', 'hậu quả', 'A missed deadline can have a serious consequence.', 'Bỏ lỡ hạn chót có thể gây hậu quả nghiêm trọng.', '/kˈɑnsəkwəns/', 'n.', 'deadline', 'TOEIC'),
  ('cover', 'chi trả / bao gồm', 'Does this plan cover dental care?', 'Gói này có chi trả nha khoa không?', '/kˈʌvɚ/', 'v.', 'authorize', 'TOEIC'),
  ('expiration', 'ngày hết hạn', 'Check the expiration date on the coupon.', 'Kiểm tra ngày hết hạn trên phiếu.', '/ˌɛkspɚˈeɪʃən/', 'n.', 'deadline', 'TOEIC'),
  ('frequently', 'thường xuyên', 'The printer jams frequently in humid weather.', 'Máy in kẹt giấy thường xuyên khi trời ẩm.', '/fɹˈikwəntli/', 'adv.', 'inventory', 'TOEIC'),
  ('imply', 'ám chỉ', 'The memo does not imply that jobs will be cut.', 'Bản ghi nhớ không ám chỉ sẽ cắt việc.', '/ˌɪmplˈaɪ/', 'v.', 'memo', 'TOEIC'),
  ('promise', 'lời hứa', 'We kept our promise to ship on Friday.', 'Chúng tôi giữ lời hứa gửi hàng vào thứ Sáu.', '/pɹˈɑməs/', 'n.', 'shipment', 'TOEIC'),
  ('protect', 'bảo vệ', 'Wear gloves to protect your hands.', 'Đeo găng để bảo vệ tay.', '/pɹətˈɛkt/', 'v.', 'inventory', 'TOEIC'),
  ('variety', 'sự đa dạng', 'The shop offers a variety of office chairs.', 'Cửa hàng có nhiều loại ghế văn phòng.', '/vɚˈaɪəti/', 'n.', 'brochure', 'TOEIC'),
  ('address', 'giải quyết (vấn đề)', 'The director will address safety concerns today.', 'Giám đốc sẽ giải quyết các lo ngại an toàn hôm nay.', '/ˈædɹˌɛs/', 'v.', 'conference', 'TOEIC'),
  ('demonstrate', 'trình diễn / chứng minh', 'Please demonstrate how the new scanner works.', 'Vui lòng trình diễn máy quét mới hoạt động thế nào.', '/dˈɛmənstɹˌeɪt/', 'v.', 'inventory', 'TOEIC'),
  ('develop', 'phát triển', 'The team will develop a training plan.', 'Nhóm sẽ phát triển kế hoạch đào tạo.', '/dɪvˈɛləp/', 'v.', 'employee', 'TOEIC'),
  ('gather', 'thu thập', 'Please gather the survey forms from each table.', 'Vui lòng thu thập phiếu khảo sát từ mỗi bàn.', '/ɡˈæðɚ/', 'v.', 'memo', 'TOEIC'),
  ('offer', 'đề nghị / ưu đãi', 'The limited-time offer ends on Sunday.', 'Ưu đãi có thời hạn kết thúc vào Chủ nhật.', '/ˈɔfɚ/', 'n.', 'brochure', 'TOEIC'),
  ('primarily', 'chủ yếu', 'This shop serves primarily business travelers.', 'Cửa hàng này phục vụ chủ yếu khách công tác.', '/pɹaɪmˈɛɹəli/', 'adv.', 'reservation', 'TOEIC'),
  ('risk', 'rủi ro', 'Delaying the shipment increases the risk of damage.', 'Hoãn lô hàng làm tăng rủi ro hư hỏng.', '/ɹˈɪsk/', 'n.', 'shipment', 'TOEIC'),
  ('strategy', 'chiến lược', 'Our strategy is to open smaller stores first.', 'Chiến lược của chúng tôi là mở cửa hàng nhỏ trước.', '/stɹˈætədʒi/', 'n.', 'brochure', 'TOEIC'),
  ('strong', 'mạnh', 'The company posted strong sales in March.', 'Công ty ghi nhận doanh số mạnh vào tháng Ba.', '/stɹˈɔŋ/', 'adj.', 'budget', 'TOEIC'),
  ('substitution', 'sự thay thế', 'No substitution of parts is allowed under the warranty.', 'Không được thay linh kiện khác trong thời hạn bảo hành.', '/sˌʌbstɪtˈuʃən/', 'n.', 'inventory', 'TOEIC'),
  ('accommodate', 'chứa / đáp ứng', 'The hall can accommodate 250 guests.', 'Hội trường chứa được 250 khách.', '/əkˈɑmədˌeɪt/', 'v.', 'occupancy', 'TOEIC'),
  ('arrangement', 'sự sắp xếp', 'Travel arrangements were made by the assistant.', 'Việc sắp xếp chuyến đi do trợ lý thực hiện.', '/ɚˈeɪndʒmənt/', 'n.', 'itinerary', 'TOEIC'),
  ('association', 'hiệp hội', 'She joined the local hotel association.', 'Cô ấy gia nhập hiệp hội khách sạn địa phương.', '/əsˌoʊsiˈeɪʃən/', 'n.', 'conference', 'TOEIC'),
  ('location', 'vị trí', 'A downtown location is convenient for clients.', 'Vị trí trung tâm tiện cho khách.', '/loʊkˈeɪʃən/', 'n.', 'headquarters', 'TOEIC'),
  ('overcrowded', 'quá đông', 'The lobby was overcrowded during check-in.', 'Sảnh quá đông trong giờ nhận phòng.', '/ˈoʊvɚkɹˌaʊdɪd/', 'adj.', 'occupancy', 'TOEIC'),
  ('register', 'đăng ký', 'Please register for the workshop online.', 'Vui lòng đăng ký hội thảo trực tuyến.', '/ɹˈɛdʒɪstɚ/', 'v.', 'conference', 'TOEIC'),
  ('select', 'chọn', 'Select a seat near the aisle if you prefer.', 'Chọn ghế gần lối đi nếu bạn thích.', '/səlˈɛkt/', 'v.', 'itinerary', 'TOEIC'),
  ('session', 'phiên họp / buổi', 'The afternoon session starts at 1:30.', 'Phiên chiều bắt đầu lúc 1:30.', '/sˈɛʃən/', 'n.', 'conference', 'TOEIC'),
  ('access', 'quyền truy cập', 'Staff need a badge for access to the warehouse.', 'Nhân viên cần thẻ để vào kho.', '/ˈæksˌɛs/', 'n.', 'authorize', 'TOEIC'),
  ('compatible', 'tương thích', 'This cable is compatible with the new laptop.', 'Cáp này tương thích với laptop mới.', '/kəmpˈætəbəl/', 'adj.', 'inventory', 'TOEIC'),
  ('delete', 'xóa', 'Do not delete files from the shared folder.', 'Không xóa tệp trong thư mục dùng chung.', '/dɪlˈit/', 'v.', 'memo', 'TOEIC'),
  ('display', 'trưng bày', 'Please display the new prices in the window.', 'Vui lòng trưng bày giá mới ở cửa sổ.', '/dɪsplˈeɪ/', 'v.', 'brochure', 'TOEIC'),
  ('duplicate', 'bản sao', 'Keep a duplicate of every signed form.', 'Giữ bản sao của mọi mẫu đã ký.', '/dˈupləkət/', 'n.', 'memo', 'TOEIC'),
  ('fail', 'thất bại / hỏng', 'If the printer fails, use the one on floor two.', 'Nếu máy in hỏng, dùng máy ở tầng hai.', '/fˈeɪl/', 'v.', 'inventory', 'TOEIC'),
  ('ignore', 'bỏ qua', 'Do not ignore the safety alarm.', 'Không bỏ qua chuông báo an toàn.', '/ˌɪɡnˈɔɹ/', 'v.', 'authorize', 'TOEIC'),
  ('search', 'tìm kiếm', 'You can search the catalog by product code.', 'Bạn có thể tìm trong danh mục theo mã sản phẩm.', '/sˈɝtʃ/', 'v.', 'brochure', 'TOEIC'),
  ('warning', 'cảnh báo', 'A warning light came on in the elevator.', 'Đèn cảnh báo sáng trong thang máy.', '/wˈɔɹnɪŋ/', 'n.', 'inventory', 'TOEIC'),
  ('disk', 'đĩa (lưu trữ)', 'Save a copy of the file on a backup disk.', 'Lưu bản sao tệp trên đĩa dự phòng.', '/dˈɪsk/', 'n.', 'memo', 'TOEIC'),
  ('keyboard', 'bàn phím', 'A spare keyboard is in the supply closet.', 'Bàn phím dự phòng ở tủ đồ dùng.', '/kˈibˌɔɹd/', 'n.', 'inventory', 'TOEIC'),
  ('software', 'phần mềm', 'The accounting software will be updated tonight.', 'Phần mềm kế toán sẽ được cập nhật tối nay.', '/sˈɔftwˌɛɹ/', 'n.', 'memo', 'TOEIC'),
  ('virus', 'vi-rút (máy tính)', 'Do not open attachments that may contain a virus.', 'Không mở tệp đính kèm có thể chứa vi-rút.', '/vˈaɪɹəs/', 'n.', 'memo', 'TOEIC'),
  ('attire', 'trang phục', 'Business attire is required at the dinner.', 'Bữa tối yêu cầu trang phục công sở.', '/ətˈaɪɚ/', 'n.', 'conference', 'TOEIC'),
  ('behavior', 'hành vi', 'Polite behavior is expected at the front desk.', 'Hành vi lịch sự được mong đợi ở quầy lễ tân.', '/bɪhˈeɪvjɚ/', 'n.', 'reservation', 'TOEIC'),
  ('etiquette', 'nghi thức', 'Email etiquette includes a clear subject line.', 'Nghi thức email gồm dòng chủ đề rõ.', '/ˈɛtəkət/', 'n.', 'memo', 'TOEIC'),
  ('formal', 'trang trọng', 'A formal invitation will be mailed next week.', 'Thiệp mời trang trọng sẽ được gửi tuần tới.', '/fˈɔɹməl/', 'adj.', 'conference', 'TOEIC'),
  ('informal', 'không trang trọng', 'Friday is an informal dress day in this office.', 'Thứ Sáu là ngày ăn mặc thoải mái ở văn phòng này.', '/ˌɪnfˈɔɹməl/', 'adj.', 'employee', 'TOEIC'),
  ('manners', 'phép lịch sự', 'Good manners help during client visits.', 'Phép lịch sự giúp ích khi khách đến thăm.', '/mˈænɚz/', 'n.', 'conference', 'TOEIC'),
  ('inappropriate', 'không phù hợp', 'Jeans are inappropriate for the interview.', 'Quần jeans không phù hợp cho buổi phỏng vấn.', '/ˌɪnəpɹˈoʊpɹiɪt/', 'adj.', 'applicant', 'TOEIC'),
  ('condition', 'tình trạng / điều kiện', 'The used copier is in excellent condition.', 'Máy photocopy cũ còn tình trạng rất tốt.', '/kəndˈɪʃən/', 'n.', 'inventory', 'TOEIC'),
  ('dissatisfaction', 'sự không hài lòng', 'The survey showed dissatisfaction with wait times.', 'Khảo sát cho thấy không hài lòng về thời gian chờ.', '/dˌɪsætɪsfˈækʃən/', 'n.', 'brochure', 'TOEIC'),
  ('item', 'mặt hàng', 'Each item on the invoice has a product code.', 'Mỗi mặt hàng trên hóa đơn có mã sản phẩm.', '/ˈaɪtəm/', 'n.', 'invoice', 'TOEIC'),
  ('pleasant', 'dễ chịu', 'The hotel has a pleasant garden for breakfast.', 'Khách sạn có vườn dễ chịu cho bữa sáng.', '/plˈɛzənt/', 'adj.', 'complimentary', 'TOEIC'),
  ('prefer', 'thích hơn', 'Most guests prefer a room with a city view.', 'Hầu hết khách thích phòng nhìn ra thành phố.', '/pɹəfˈɝ/', 'v.', 'reservation', 'TOEIC'),
  ('product', 'sản phẩm', 'This product is made in the local factory.', 'Sản phẩm này được làm tại nhà máy địa phương.', '/pɹˈɑdəkt/', 'n.', 'inventory', 'TOEIC'),
  ('return', 'trả lại', 'You may return unused goods within 14 days.', 'Bạn có thể trả hàng chưa dùng trong 14 ngày.', '/ɹɪtˈɝn/', 'v.', 'invoice', 'TOEIC'),
  ('receive', 'nhận', 'Did you receive the package this morning?', 'Bạn đã nhận kiện hàng sáng nay chưa?', '/ɹəsˈiv/', 'v.', 'shipment', 'TOEIC'),
  ('service', 'dịch vụ', 'Room service is available until midnight.', 'Dịch vụ phòng có đến nửa đêm.', '/sˈɝvəs/', 'n.', 'reservation', 'TOEIC'),
  ('appointment', 'cuộc hẹn', 'I have an appointment with the dentist at 3.', 'Tôi có hẹn nha sĩ lúc 3 giờ.', '/əpˈɔɪntmənt/', 'n.', 'deadline', 'TOEIC'),
  ('provider', 'nhà cung cấp dịch vụ', 'Our internet provider will visit on Tuesday.', 'Nhà cung cấp internet sẽ đến vào thứ Ba.', '/pɹəvˈaɪdɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('directory', 'danh bạ', 'The staff directory is posted near the elevator.', 'Danh bạ nhân viên được dán gần thang máy.', '/dɚˈɛktɚi/', 'n.', 'headquarters', 'TOEIC'),
  ('inexpensive', 'rẻ', 'The inn offers inexpensive rooms near the station.', 'Nhà trọ có phòng rẻ gần ga.', '/ˌɪnɪkspˈɛnsɪv/', 'adj.', 'reservation', 'TOEIC'),
  ('install', 'lắp đặt', 'Technicians will install the new phones tomorrow.', 'Kỹ thuật viên sẽ lắp điện thoại mới vào ngày mai.', '/ˌɪnstˈɔl/', 'v.', 'inventory', 'TOEIC'),
  ('necessary', 'cần thiết', 'A visitor badge is necessary after 6 p.m.', 'Thẻ khách là cần thiết sau 6 giờ tối.', '/nˈɛsəsˌɛɹi/', 'adj.', 'authorize', 'TOEIC'),
  ('periodical', 'tạp chí định kỳ', 'The library keeps every periodical for two years.', 'Thư viện giữ mỗi tạp chí định kỳ trong hai năm.', '/pˌɪɹiˈɑdɪkəl/', 'n.', 'memo', 'TOEIC'),
  ('subscribe', 'đặt mua định kỳ', 'You can subscribe to the newsletter by email.', 'Bạn có thể đặt nhận bản tin qua email.', '/səbskɹˈaɪb/', 'v.', 'brochure', 'TOEIC'),
  ('subscription', 'gói đặt mua', 'The magazine subscription includes digital access.', 'Gói tạp chí gồm quyền xem bản điện tử.', '/səbskɹˈɪpʃən/', 'n.', 'brochure', 'TOEIC'),
  ('densely', 'dày đặc', 'The factory is in a densely populated area.', 'Nhà máy nằm ở khu dân cư dày đặc.', '/dˈɛnsli/', 'adv.', 'headquarters', 'TOEIC'),
  ('congested', 'ùn tắc', 'Avoid the congested bridge during rush hour.', 'Tránh cây cầu ùn tắc giờ cao điểm.', '/kəndʒˈɛstəd/', 'adj.', 'itinerary', 'TOEIC'),
  ('haul', 'vận chuyển (hàng nặng)', 'Trucks haul steel from the port to the plant.', 'Xe tải vận chuyển thép từ cảng tới nhà máy.', '/hˈɔl/', 'v.', 'shipment', 'TOEIC'),
  ('parking', 'chỗ đỗ xe', 'Parking is free for hotel guests.', 'Khách khách sạn được đỗ xe miễn phí.', '/pˈɑɹkɪŋ/', 'n.', 'reservation', 'TOEIC'),
  ('pedestrian', 'người đi bộ', 'Pedestrians should use the marked crossing.', 'Người đi bộ nên đi qua vạch dành cho họ.', '/pədˈɛstɹiən/', 'n.', 'itinerary', 'TOEIC'),
  ('proceed', 'tiếp tục / đi tiếp', 'Please proceed to gate 9 after security.', 'Vui lòng đi tiếp tới cổng 9 sau an ninh.', '/pɹəsˈid/', 'v.', 'itinerary', 'TOEIC'),
  ('remainder', 'phần còn lại', 'Pay a deposit now and the remainder on delivery.', 'Trả cọc ngay và phần còn lại khi giao hàng.', '/ɹɪmˈeɪndɚ/', 'n.', 'invoice', 'TOEIC'),
  ('construction', 'xây dựng', 'The lobby is closed during construction.', 'Sảnh đóng trong thời gian xây dựng.', '/kənstɹˈʌkʃən/', 'n.', 'headquarters', 'TOEIC'),
  ('scanner', 'máy quét', 'Place the form face down on the scanner.', 'Đặt mẫu đơn úp xuống máy quét.', '/skˈænɚ/', 'n.', 'memo', 'TOEIC'),
  ('printer', 'máy in', 'The color printer is next to the copy room.', 'Máy in màu ở cạnh phòng photocopy.', '/pɹˈɪntɚ/', 'n.', 'inventory', 'TOEIC'),
  ('network', 'mạng', 'The office network will restart at noon.', 'Mạng văn phòng sẽ khởi động lại lúc trưa.', '/nˈɛtwˌɝk/', 'n.', 'memo', 'TOEIC'),
  ('password', 'mật khẩu', 'Do not share your password with anyone.', 'Không chia sẻ mật khẩu với ai.', '/pˈæswˌɝd/', 'n.', 'authorize', 'TOEIC'),
  ('download', 'tải xuống', 'You can download the form from our website.', 'Bạn có thể tải mẫu đơn từ trang web.', '/dˈaʊnlˌoʊd/', 'v.', 'memo', 'TOEIC'),
  ('upload', 'tải lên', 'Please upload the photos to the shared drive.', 'Vui lòng tải ảnh lên ổ dùng chung.', '/ˈʌplˌoʊd/', 'v.', 'memo', 'TOEIC'),
  ('laptop', 'máy tính xách tay', 'Bring your laptop to the training room.', 'Mang laptop tới phòng đào tạo.', '/lˈæptˌɑp/', 'n.', 'conference', 'TOEIC'),
  ('desktop', 'máy tính để bàn', 'A new desktop will be placed on each desk.', 'Mỗi bàn sẽ có một máy tính để bàn mới.', '/dˈɛsktˌɑp/', 'n.', 'headquarters', 'TOEIC'),
  ('wireless', 'không dây', 'Free wireless internet is available in the lobby.', 'Internet không dây miễn phí có ở sảnh.', '/wˈaɪɹlɪs/', 'adj.', 'reservation', 'TOEIC'),
  ('broadband', 'mạng băng thông rộng', 'The hotel upgraded to faster broadband.', 'Khách sạn đã nâng mạng băng thông rộng nhanh hơn.', '/bɹˈɔdbˌænd/', 'n.', 'reservation', 'TOEIC'),
  ('backup', 'bản sao lưu', 'Make a backup of the files before you leave.', 'Tạo bản sao lưu tệp trước khi bạn về.', '/bˈækˌʌp/', 'n.', 'memo', 'TOEIC'),
  ('crash', 'sập (máy/hệ thống)', 'If the system crashes, call the help desk.', 'Nếu hệ thống sập, gọi bộ phận hỗ trợ.', '/kɹˈæʃ/', 'v.', 'memo', 'TOEIC'),
  ('server', 'máy chủ', 'The mail server is down until 4 p.m.', 'Máy chủ thư dừng đến 4 giờ chiều.', '/sˈɝvɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('database', 'cơ sở dữ liệu', 'Customer records are stored in a secure database.', 'Hồ sơ khách được lưu trong cơ sở dữ liệu an toàn.', '/dˈeɪtəbˌeɪs/', 'n.', 'memo', 'TOEIC'),
  ('spreadsheet', 'bảng tính', 'Enter the hours in this spreadsheet.', 'Nhập số giờ vào bảng tính này.', '/spɹˈɛdʃˌit/', 'n.', 'memo', 'TOEIC'),
  ('presentation', 'bài thuyết trình', 'Her presentation on sales lasted 20 minutes.', 'Bài thuyết trình về doanh số của cô ấy dài 20 phút.', '/pɹˌɛzəntˈeɪʃən/', 'n.', 'conference', 'TOEIC'),
  ('projector', 'máy chiếu', 'Please turn off the projector after the talk.', 'Vui lòng tắt máy chiếu sau bài nói.', '/pɹədʒˈɛktɚ/', 'n.', 'conference', 'TOEIC'),
  ('photocopier', 'máy photocopy', 'The photocopier needs more paper.', 'Máy photocopy cần thêm giấy.', '/fˈoʊtoʊkˌɑpiɚ/', 'n.', 'inventory', 'TOEIC'),
  ('stapler', 'dập ghim', 'A stapler is in the top drawer.', 'Dập ghim ở ngăn kéo trên.', '/stˈeɪpəlɚ/', 'n.', 'memo', 'TOEIC'),
  ('envelope', 'phong bì', 'Put the contract in a large envelope.', 'Cho hợp đồng vào phong bì lớn.', '/ˈɛnvəlˌoʊp/', 'n.', 'memo', 'TOEIC'),
  ('postage', 'cước tem', 'Postage to overseas offices is higher.', 'Cước gửi ra văn phòng nước ngoài cao hơn.', '/pˈoʊstədʒ/', 'n.', 'shipment', 'TOEIC'),
  ('mailbox', 'hòm thư', 'Drop the keys in the mailbox if we are out.', 'Bỏ chìa vào hòm thư nếu chúng tôi vắng.', '/mˈeɪlbˌɑks/', 'n.', 'headquarters', 'TOEIC'),
  ('outgoing', 'đi ra / gửi đi', 'Outgoing mail leaves the office at 4 p.m.', 'Thư gửi đi rời văn phòng lúc 4 giờ chiều.', '/ˈaʊtɡˌoʊɪŋ/', 'adj.', 'memo', 'TOEIC'),
  ('incoming', 'đến / gửi tới', 'Incoming calls are answered at the front desk.', 'Cuộc gọi đến được lễ tân trả lời.', '/ˈɪnkˌʌmɪŋ/', 'adj.', 'reservation', 'TOEIC'),
  ('recipient', 'người nhận', 'Check the recipient''s name before you send.', 'Kiểm tra tên người nhận trước khi gửi.', '/ɹəsˈɪpiənt/', 'n.', 'memo', 'TOEIC'),
  ('sender', 'người gửi', 'The sender must include a return address.', 'Người gửi phải ghi địa chỉ trả lại.', '/sˈɛndɚ/', 'n.', 'memo', 'TOEIC'),
  ('confidential', 'mật', 'This file is confidential and must stay locked.', 'Tệp này là mật và phải khóa.', '/kˌɑnfədˈɛnʃəl/', 'adj.', 'authorize', 'TOEIC'),
  ('priority', 'mức ưu tiên', 'Safety is our first priority on the factory floor.', 'An toàn là ưu tiên hàng đầu trong nhà máy.', '/pɹaɪˈɔɹəti/', 'n.', 'inventory', 'TOEIC'),
  ('contract', 'hợp đồng', 'Please read the contract before you sign it.', 'Vui lòng đọc hợp đồng trước khi ký.', '/kˈɑntɹˌækt/', 'n.', 'authorize', 'TOEIC'),
  ('legal', 'hợp pháp / pháp lý', 'Ask the legal team about this clause.', 'Hỏi nhóm pháp chế về điều khoản này.', '/lˈiɡəl/', 'adj.', 'authorize', 'TOEIC'),
  ('illegal', 'bất hợp pháp', 'It is illegal to copy this software.', 'Sao chép phần mềm này là bất hợp pháp.', '/ˌɪlˈiɡəl/', 'adj.', 'authorize', 'TOEIC'),
  ('binding', 'ràng buộc', 'The offer is binding once both sides sign.', 'Đề nghị trở nên ràng buộc khi cả hai bên ký.', '/bˈaɪndɪŋ/', 'adj.', 'authorize', 'TOEIC'),
  ('breach', 'vi phạm (hợp đồng)', 'Late payment is a breach of the agreement.', 'Thanh toán muộn là vi phạm thỏa thuận.', '/bɹˈitʃ/', 'n.', 'authorize', 'TOEIC'),
  ('disclose', 'công bố / tiết lộ', 'We cannot disclose client names.', 'Chúng tôi không thể tiết lộ tên khách.', '/dɪsklˈoʊz/', 'v.', 'authorize', 'TOEIC'),
  ('disclosure', 'sự công bố', 'Full disclosure of fees is required by law.', 'Luật yêu cầu công bố đầy đủ các khoản phí.', '/dɪsklˈoʊʒɚ/', 'n.', 'authorize', 'TOEIC'),
  ('patent', 'bằng sáng chế', 'The company filed a patent for the new design.', 'Công ty nộp bằng sáng chế cho thiết kế mới.', '/pˈætənt/', 'n.', 'brochure', 'TOEIC'),
  ('copyright', 'bản quyền', 'Do not use photos without copyright permission.', 'Không dùng ảnh khi chưa có phép bản quyền.', '/kˈɑpiɹˌaɪt/', 'n.', 'brochure', 'TOEIC'),
  ('landlord', 'chủ nhà', 'The landlord will paint the office in May.', 'Chủ nhà sẽ sơn văn phòng vào tháng Năm.', '/lˈændlˌɔɹd/', 'n.', 'headquarters', 'TOEIC'),
  ('tenant', 'người thuê', 'Each tenant must pay rent by the fifth.', 'Mỗi người thuê phải trả tiền nhà trước ngày mùng 5.', '/tˈɛnənt/', 'n.', 'budget', 'TOEIC'),
  ('lease', 'hợp đồng thuê', 'The lease on this floor ends in December.', 'Hợp đồng thuê tầng này hết vào tháng 12.', '/lˈis/', 'n.', 'authorize', 'TOEIC'),
  ('rent', 'tiền thuê', 'Rent includes water but not electricity.', 'Tiền thuê gồm nước nhưng không gồm điện.', '/ɹˈɛnt/', 'n.', 'budget', 'TOEIC'),
  ('premises', 'mặt bằng / cơ sở', 'No smoking is allowed on the premises.', 'Cấm hút thuốc trong mặt bằng.', '/pɹˈɛməsəz/', 'n.', 'headquarters', 'TOEIC'),
  ('penalty', 'tiền phạt', 'There is a penalty for returning the car late.', 'Có tiền phạt nếu trả xe muộn.', '/pˈɛnəlti/', 'n.', 'authorize', 'TOEIC'),
  ('liable', 'chịu trách nhiệm pháp lý', 'The carrier is liable for lost cargo.', 'Hãng vận chuyển chịu trách nhiệm hàng mất.', '/lˈaɪəbəl/', 'adj.', 'shipment', 'TOEIC'),
  ('exempt', 'được miễn', 'Food products are exempt from this tax.', 'Sản phẩm thực phẩm được miễn thuế này.', '/ɪɡzˈɛmpt/', 'adj.', 'invoice', 'TOEIC'),
  ('enforce', 'thực thi', 'Guards enforce the visitor rules at the gate.', 'Bảo vệ thực thi nội quy khách ở cổng.', '/ɛnfˈɔɹs/', 'v.', 'authorize', 'TOEIC'),
  ('suspend', 'tạm dừng', 'The city will suspend night buses this week.', 'Thành phố sẽ tạm dừng xe buýt đêm tuần này.', '/səspˈɛnd/', 'v.', 'itinerary', 'TOEIC'),
  ('commence', 'bắt đầu', 'Boarding will commence at 8:40.', 'Việc lên máy bay bắt đầu lúc 8:40.', '/kəmˈɛns/', 'v.', 'itinerary', 'TOEIC'),
  ('cease', 'chấm dứt', 'Please cease using the old letterhead.', 'Vui lòng ngừng dùng tiêu đề thư cũ.', '/sˈis/', 'v.', 'memo', 'TOEIC'),
  ('attorney', 'luật sư', 'An attorney reviewed the lease yesterday.', 'Luật sư đã xem hợp đồng thuê hôm qua.', '/ətˈɝni/', 'n.', 'authorize', 'TOEIC'),
  ('witness', 'nhân chứng / người làm chứng', 'A witness must sign the last page.', 'Người làm chứng phải ký trang cuối.', '/wˈɪtnəs/', 'n.', 'authorize', 'TOEIC'),
  ('evidence', 'bằng chứng', 'Keep the photos as evidence of the damage.', 'Giữ ảnh làm bằng chứng thiệt hại.', '/ˈɛvədəns/', 'n.', 'authorize', 'TOEIC'),
  ('property', 'tài sản / bất động sản', 'Personal property should not be left in the lobby.', 'Không để tài sản cá nhân ở sảnh.', '/pɹˈɑpɚti/', 'n.', 'headquarters', 'TOEIC'),
  ('secure', 'an toàn / bảo mật', 'Keep passwords in a secure place.', 'Giữ mật khẩu ở nơi an toàn.', '/sɪkjˈʊɹ/', 'adj.', 'authorize', 'TOEIC'),
  ('security', 'an ninh', 'Security will check bags at the entrance.', 'An ninh sẽ kiểm tra túi ở cửa vào.', '/sɪkjˈʊɹəti/', 'n.', 'authorize', 'TOEIC'),
  ('apply', 'nộp đơn', 'You may apply for the opening online.', 'Bạn có thể nộp đơn vị trí trống trực tuyến.', '/əplˈaɪ/', 'v.', 'applicant', 'TOEIC'),
  ('application', 'đơn ứng tuyển', 'Incomplete applications will not be reviewed.', 'Đơn không đầy đủ sẽ không được xét.', '/ˌæpləkˈeɪʃən/', 'n.', 'applicant', 'TOEIC'),
  ('employer', 'nhà tuyển dụng', 'The employer offers flexible hours.', 'Nhà tuyển dụng cho giờ làm linh hoạt.', '/ɛmplˈɔɪɚ/', 'n.', 'employee', 'TOEIC'),
  ('employment', 'việc làm', 'Seasonal employment begins in June.', 'Việc làm theo mùa bắt đầu vào tháng Sáu.', '/ɛmplˈɔɪmənt/', 'n.', 'employee', 'TOEIC'),
  ('unemployed', 'thất nghiệp', 'The city runs a program for unemployed workers.', 'Thành phố có chương trình cho người thất nghiệp.', '/ˌʌnɛmplˈɔɪd/', 'adj.', 'applicant', 'TOEIC'),
  ('skilled', 'có tay nghề', 'We need skilled technicians for the night shift.', 'Chúng tôi cần kỹ thuật viên có tay nghề cho ca đêm.', '/skˈɪld/', 'adj.', 'employee', 'TOEIC'),
  ('expertise', 'chuyên môn', 'Her expertise in logistics saved two days.', 'Chuyên môn logistics của cô ấy tiết kiệm hai ngày.', '/ˌɛkspɚtˈiz/', 'n.', 'shipment', 'TOEIC'),
  ('proficient', 'thành thạo', 'Applicants must be proficient in English.', 'Ứng viên phải thành thạo tiếng Anh.', '/pɹɑfˈɪʃənt/', 'adj.', 'applicant', 'TOEIC'),
  ('capable', 'có năng lực', 'He is capable of leading the sales team.', 'Anh ấy có năng lực dẫn dắt nhóm bán hàng.', '/kˈeɪpəbəl/', 'adj.', 'employee', 'TOEIC'),
  ('dedicated', 'tận tâm', 'A dedicated staff member greeted every guest.', 'Một nhân viên tận tâm chào mọi khách.', '/dˈɛdəkeɪtəd/', 'adj.', 'employee', 'TOEIC'),
  ('dependable', 'đáng tin', 'We hired a dependable driver for deliveries.', 'Chúng tôi thuê tài xế đáng tin cho giao hàng.', '/dɪpˈɛndəbəl/', 'adj.', 'shipment', 'TOEIC'),
  ('diligent', 'siêng năng', 'The intern is diligent about filing papers.', 'Thực tập sinh siêng năng lưu giấy tờ.', '/dˈɪlɪdʒənt/', 'adj.', 'employee', 'TOEIC'),
  ('punctual', 'đúng giờ', 'Please be punctual for the 9 a.m. briefing.', 'Vui lòng đúng giờ buổi phổ biến 9 giờ sáng.', '/pˈʌŋktʃuəl/', 'adj.', 'deadline', 'TOEIC'),
  ('tardy', 'đi trễ', 'Three tardy arrivals will be noted in the file.', 'Ba lần đến trễ sẽ được ghi vào hồ sơ.', '/tˈɑɹdi/', 'adj.', 'deadline', 'TOEIC'),
  ('absent', 'vắng mặt', 'Two clerks were absent because of the storm.', 'Hai nhân viên vắng vì bão.', '/ˈæbsənt/', 'adj.', 'employee', 'TOEIC'),
  ('absence', 'sự vắng mặt', 'Please report your absence to the supervisor.', 'Vui lòng báo sự vắng mặt cho người giám sát.', '/ˈæbsəns/', 'n.', 'employee', 'TOEIC'),
  ('attendance', 'sự có mặt', 'Attendance at the fire drill is required.', 'Có mặt ở buổi diễn tập cháy là bắt buộc.', '/ətˈɛndəns/', 'n.', 'employee', 'TOEIC'),
  ('coworker', 'đồng nghiệp', 'Ask a coworker to cover your desk at lunch.', 'Nhờ đồng nghiệp trông bàn giúp lúc ăn trưa.', '/kˈoʊwˈɝkɚ/', 'n.', 'employee', 'TOEIC'),
  ('mentor', 'người hướng dẫn', 'A mentor will help you during the first month.', 'Người hướng dẫn sẽ giúp bạn trong tháng đầu.', '/mˈɛntˌɔɹ/', 'n.', 'employee', 'TOEIC'),
  ('apprentice', 'người học việc', 'The apprentice learned to operate the press.', 'Người học việc học vận hành máy in.', '/əpɹˈɛntəs/', 'n.', 'inventory', 'TOEIC'),
  ('veteran', 'người kỳ cựu', 'A veteran clerk trained the new cashier.', 'Nhân viên kỳ cựu đào tạo thu ngân mới.', '/vˈɛtɚən/', 'n.', 'employee', 'TOEIC'),
  ('junior', 'cấp thấp', 'The junior analyst sits on the second floor.', 'Chuyên viên phân tích cấp thấp ngồi tầng hai.', '/dʒˈunjɚ/', 'adj.', 'employee', 'TOEIC'),
  ('senior', 'cấp cao', 'Senior staff may park in the covered lot.', 'Nhân viên cấp cao được đỗ ở bãi có mái.', '/sˈinjɚ/', 'adj.', 'employee', 'TOEIC'),
  ('opening', 'vị trí tuyển', 'There is an opening for a night receptionist.', 'Có vị trí tuyển lễ tân ca đêm.', '/ˈoʊpənɪŋ/', 'n.', 'applicant', 'TOEIC'),
  ('posting', 'tin tuyển dụng', 'The job posting closes on Friday.', 'Tin tuyển dụng đóng vào thứ Sáu.', '/pˈoʊstɪŋ/', 'n.', 'applicant', 'TOEIC'),
  ('screening', 'sơ loại hồ sơ', 'Phone screening takes about 15 minutes.', 'Sơ loại qua điện thoại mất khoảng 15 phút.', '/skɹˈinɪŋ/', 'n.', 'applicant', 'TOEIC'),
  ('relocate', 'chuyển chỗ làm', 'She agreed to relocate to the Osaka branch.', 'Cô ấy đồng ý chuyển tới chi nhánh Osaka.', '/ɹˌilˈoʊkeɪt/', 'v.', 'headquarters', 'TOEIC'),
  ('relocation', 'việc chuyển chỗ', 'Relocation costs are paid by the company.', 'Chi phí chuyển chỗ do công ty trả.', '/ɹˌilˈoʊkˈeɪʃən/', 'n.', 'budget', 'TOEIC'),
  ('severance', 'trợ cấp thôi việc', 'Severance pay is based on years of service.', 'Trợ cấp thôi việc dựa trên số năm làm việc.', '/sˈɛvˌɝəns/', 'n.', 'budget', 'TOEIC'),
  ('workplace', 'nơi làm việc', 'Keep the workplace clear of boxes.', 'Giữ nơi làm việc không bị thùng chiếm lối.', '/wˈɝkplˌeɪs/', 'n.', 'headquarters', 'TOEIC'),
  ('workload', 'khối lượng công việc', 'The new software reduced our workload.', 'Phần mềm mới giảm khối lượng công việc.', '/wˈɝklˌoʊd/', 'n.', 'employee', 'TOEIC'),
  ('forecast', 'dự báo', 'The sales forecast for June looks strong.', 'Dự báo doanh số tháng Sáu trông khả quan.', '/fˈɔɹkˌæst/', 'n.', 'budget', 'TOEIC'),
  ('profitability', 'khả năng sinh lời', 'The new line improved profitability.', 'Dòng sản phẩm mới cải thiện khả năng sinh lời.', '/pɹˌɑfɪtəbˈɪlɪti/', 'n.', 'budget', 'TOEIC'),
  ('turnover', 'doanh số / biến động nhân sự', 'Staff turnover fell after the raise.', 'Biến động nhân sự giảm sau đợt tăng lương.', '/tˈɝnˌoʊvɚ/', 'n.', 'employee', 'TOEIC'),
  ('overhead', 'chi phí gián tiếp', 'Moving downtown increased our overhead.', 'Chuyển vào trung tâm làm tăng chi phí gián tiếp.', '/ˈoʊvɚhˈɛd/', 'n.', 'budget', 'TOEIC'),
  ('cash', 'tiền mặt', 'The register holds cash overnight in a safe.', 'Quầy giữ tiền mặt qua đêm trong két.', '/kˈæʃ/', 'n.', 'budget', 'TOEIC'),
  ('check', 'séc', 'Please make the check payable to the hotel.', 'Vui lòng ghi séc trả cho khách sạn.', '/tʃˈɛk/', 'n.', 'invoice', 'TOEIC'),
  ('credit', 'tín dụng', 'Your store credit expires in six months.', 'Tín dụng cửa hàng hết hạn sau sáu tháng.', '/kɹˈɛdət/', 'n.', 'invoice', 'TOEIC'),
  ('debit', 'ghi nợ', 'A debit appeared on the account this morning.', 'Một khoản ghi nợ xuất hiện trên tài khoản sáng nay.', '/dˈɛbɪt/', 'n.', 'invoice', 'TOEIC'),
  ('payment', 'khoản thanh toán', 'The final payment is due on the first.', 'Khoản thanh toán cuối hạn vào mùng 1.', '/pˈeɪmənt/', 'n.', 'invoice', 'TOEIC'),
  ('billing', 'việc lập hóa đơn', 'Billing errors should be reported at once.', 'Lỗi lập hóa đơn phải được báo ngay.', '/bˈɪlɪŋ/', 'n.', 'invoice', 'TOEIC'),
  ('bookkeeping', 'sổ sách kế toán', 'Bookkeeping is done every Friday afternoon.', 'Sổ sách được ghi mỗi chiều thứ Sáu.', '/bˈʊkkˌipɪŋ/', 'n.', 'invoice', 'TOEIC'),
  ('reconcile', 'đối chiếu sổ', 'Please reconcile the receipts with the ledger.', 'Vui lòng đối chiếu biên lai với sổ cái.', '/ɹˈɛkənsˌaɪl/', 'v.', 'invoice', 'TOEIC'),
  ('outstanding', 'chưa thanh toán / xuất sắc', 'Two invoices are still outstanding.', 'Hai hóa đơn vẫn chưa thanh toán.', '/ˌaʊtstˈændɪŋ/', 'adj.', 'invoice', 'TOEIC'),
  ('installment', 'khoản trả góp', 'You may pay in three monthly installments.', 'Bạn có thể trả góp ba tháng.', '/ˌɪnstˈɔlmənt/', 'n.', 'invoice', 'TOEIC'),
  ('down', 'tiền đặt cọc ban đầu', 'A down payment of 20 percent is required.', 'Cần đặt cọc ban đầu 20 phần trăm.', '/dˈaʊn/', 'n.', 'budget', 'TOEIC'),
  ('collateral', 'tài sản thế chấp', 'The van was used as collateral for the loan.', 'Xe tải được dùng làm tài sản thế chấp khoản vay.', '/kəlˈætɚəl/', 'n.', 'budget', 'TOEIC'),
  ('principal', 'tiền gốc', 'Pay the principal before extra interest grows.', 'Trả tiền gốc trước khi lãi tăng thêm.', '/pɹˈɪnsəpəl/', 'n.', 'budget', 'TOEIC'),
  ('lender', 'bên cho vay', 'The lender approved the small-business loan.', 'Bên cho vay đã duyệt khoản vay doanh nghiệp nhỏ.', '/lˈɛndɚ/', 'n.', 'budget', 'TOEIC'),
  ('borrower', 'bên vay', 'The borrower must show last year''s tax form.', 'Bên vay phảixuất trình tờ khai thuế năm ngoái.', '/bˈɑɹoʊɚ/', 'n.', 'budget', 'TOEIC'),
  ('creditworthy', 'đủ tín nhiệm', 'Only creditworthy buyers get this rate.', 'Chỉ người mua đủ tín nhiệm được lãi này.', '/kɹˈɛdɪtwˌɝði/', 'adj.', 'budget', 'TOEIC'),
  ('default', 'vỡ nợ', 'If you default, the equipment may be repossessed.', 'Nếu vỡ nợ, thiết bị có thể bị thu hồi.', '/dɪfˈɔlt/', 'v.', 'budget', 'TOEIC'),
  ('repossess', 'thu hồi tài sản', 'The bank may repossess the truck after 90 days.', 'Ngân hàng có thể thu hồi xe sau 90 ngày.', '/ɹˌipəzˈɛs/', 'v.', 'budget', 'TOEIC'),
  ('valuation', 'định giá', 'An independent valuation of the building is ready.', 'Bản định giá độc lập của tòa nhà đã xong.', '/væljuˈeɪʃən/', 'n.', 'budget', 'TOEIC'),
  ('auction', 'đấu giá', 'Office furniture will be sold at auction.', 'Nội thất văn phòng sẽ bán đấu giá.', '/ˈɑkʃən/', 'n.', 'inventory', 'TOEIC'),
  ('bid', 'giá dự thầu', 'The lowest bid won the cleaning contract.', 'Giá dự thầu thấp nhất thắng hợp đồng dọn dẹp.', '/bˈɪd/', 'n.', 'invoice', 'TOEIC'),
  ('tender', 'hồ sơ thầu', 'Submit the tender before noon on Monday.', 'Nộp hồ sơ thầu trước trưa thứ Hai.', '/tˈɛndɚ/', 'n.', 'invoice', 'TOEIC'),
  ('procurement', 'mua sắm', 'Procurement must approve purchases over 500 dollars.', 'Mua sắm phải duyệt đơn trên 500 đô la.', '/pɹoʊkjˈʊɹmənt/', 'n.', 'invoice', 'TOEIC'),
  ('purchaser', 'người mua', 'The purchaser asked for a longer warranty.', 'Người mua yêu cầu bảo hành dài hơn.', '/pˈɝtʃəsɚ/', 'n.', 'invoice', 'TOEIC'),
  ('markup', 'biên lợi nhuận cộng thêm', 'A 15 percent markup covers shipping.', 'Biên 15 phần trăm gồm cước vận chuyển.', '/mˈɑɹkˌʌp/', 'n.', 'budget', 'TOEIC'),
  ('margin', 'biên lợi nhuận', 'The store runs on a thin profit margin.', 'Cửa hàng chạy với biên lợi nhuận mỏng.', '/mˈɑɹdʒən/', 'n.', 'budget', 'TOEIC'),
  ('stockroom', 'kho nhỏ', 'Extra paper is in the stockroom.', 'Giấy thêm ở kho nhỏ.', '/stˈɑkɹˌum/', 'n.', 'inventory', 'TOEIC'),
  ('backorder', 'đơn chờ hàng', 'The lamp is on backorder until May.', 'Đèn đang chờ hàng đến tháng Năm.', '/ˈbæk.ɔr.dɚ/', 'n.', 'shipment', 'TOEIC'),
  ('restock', 'nhập hàng lại', 'Please restock the shelves before opening.', 'Vui lòng nhập lại kệ trước giờ mở cửa.', '/ɹistˈɑk/', 'v.', 'inventory', 'TOEIC'),
  ('replenish', 'bổ sung', 'We will replenish the first-aid kits today.', 'Chúng tôi sẽ bổ sung hộp sơ cứu hôm nay.', '/ɹiplˈɛnɪʃ/', 'v.', 'inventory', 'TOEIC'),
  ('outage', 'sự cố mất (điện/mạng)', 'A power outage stopped the packing line.', 'Mất điện làm dừng dây chuyền đóng gói.', '/ˈaʊtədʒ/', 'n.', 'inventory', 'TOEIC'),
  ('blackout', 'mất điện diện rộng', 'The blackout lasted forty minutes.', 'Đợt mất điện kéo dài bốn mươi phút.', '/blˈækˌaʊt/', 'n.', 'headquarters', 'TOEIC'),
  ('generator', 'máy phát điện', 'The backup generator starts automatically.', 'Máy phát dự phòng tự khởi động.', '/dʒˈɛnɚˌeɪtɚ/', 'n.', 'inventory', 'TOEIC'),
  ('utility', 'dịch vụ hạ tầng', 'Utility bills are paid on the tenth.', 'Hóa đơn điện nước trả vào ngày mùng 10.', '/jutˈɪləti/', 'n.', 'invoice', 'TOEIC'),
  ('electricity', 'điện', 'Electricity in the warehouse is metered separately.', 'Điện trong kho được đo riêng.', '/ɪlˌɛktɹˈɪsəti/', 'n.', 'headquarters', 'TOEIC'),
  ('plumbing', 'hệ thống ống nước', 'Plumbing repairs will close the restroom.', 'Sửa ống nước sẽ đóng nhà vệ sinh.', '/plˈʌmɪŋ/', 'n.', 'headquarters', 'TOEIC'),
  ('janitor', 'nhân viên tạp vụ', 'The janitor unlocks the building at 6 a.m.', 'Nhân viên tạp vụ mở cửa lúc 6 giờ sáng.', '/dʒˈænətɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('custodian', 'người trông coi', 'A custodian checks the lights after closing.', 'Người trông coi kiểm tra đèn sau giờ đóng.', '/kəstˈoʊdiən/', 'n.', 'headquarters', 'TOEIC'),
  ('caretaker', 'người chăm sóc tòa nhà', 'The caretaker lives on the ground floor.', 'Người chăm sóc tòa nhà ở tầng trệt.', '/kˈɛɹtˌeɪkɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('superintendent', 'quản đốc tòa nhà', 'Call the superintendent if the heat fails.', 'Gọi quản đốc nếu máy sưởi hỏng.', '/sˌupɚəntˈɛndənt/', 'n.', 'headquarters', 'TOEIC'),
  ('sublet', 'cho thuê lại', 'You may not sublet the office without consent.', 'Không được cho thuê lại văn phòng khi chưa đồng ý.', '/sˈʌblˌɛt/', 'v.', 'authorize', 'TOEIC'),
  ('renovation', 'cải tạo', 'Renovation of the café starts in August.', 'Cải tạo quán cà phê bắt đầu tháng Tám.', '/ɹˌɛnəvˈeɪʃən/', 'n.', 'occupancy', 'TOEIC'),
  ('remodel', 'sửa sang', 'They will remodel the lobby next winter.', 'Họ sẽ sửa sang sảnh vào mùa đông tới.', '/ɹimˈɑdəl/', 'v.', 'occupancy', 'TOEIC'),
  ('refurbish', 'tân trang', 'We will refurbish ten rooms this month.', 'Chúng tôi sẽ tân trang mười phòng tháng này.', '/ɹifˈɝbɪʃ/', 'v.', 'occupancy', 'TOEIC'),
  ('furnish', 'trang bị nội thất', 'The suite is furnished with a meeting table.', 'Phòng suite được trang bị bàn họp.', '/fˈɝnɪʃ/', 'v.', 'reservation', 'TOEIC'),
  ('fixture', 'đồ gắn cố định', 'Do not remove light fixtures from the wall.', 'Không tháo đèn gắn tường.', '/fˈɪkstʃɚ/', 'n.', 'inventory', 'TOEIC'),
  ('appliance', 'thiết bị gia dụng', 'Each kitchen has a new appliance set.', 'Mỗi bếp có bộ thiết bị mới.', '/əplˈaɪəns/', 'n.', 'inventory', 'TOEIC'),
  ('turndown', 'dịch vụ dọn phòng tối', 'Turndown service begins at 8 p.m.', 'Dịch vụ dọn phòng tối bắt đầu lúc 8 giờ tối.', '/tˈɝndˌaʊn/', 'n.', 'reservation', 'TOEIC'),
  ('minibar', 'tủ minibar', 'Please note minibar charges on your bill.', 'Vui lòng xem phí minibar trên hóa đơn.', '/ˈmɪn.i.bɑr/', 'n.', 'complimentary', 'TOEIC'),
  ('bathrobe', 'áo choàng tắm', 'A bathrobe hangs in the closet.', 'Áo choàng tắm treo trong tủ.', '/bˈæθɹˌoʊb/', 'n.', 'reservation', 'TOEIC'),
  ('toiletry', 'đồ vệ sinh cá nhân', 'Extra toiletries are at the front desk.', 'Đồ vệ sinh thêm có ở quầy lễ tân.', '/tˈɔɪlətɹi/', 'n.', 'complimentary', 'TOEIC'),
  ('linen', 'khăn trải / khăn vải', 'Fresh linen is delivered twice a week.', 'Khăn vải sạch được giao hai lần mỗi tuần.', '/lˈɪnən/', 'n.', 'reservation', 'TOEIC'),
  ('laundry', 'giặt là', 'Laundry bags are in the wardrobe.', 'Túi giặt là ở trong tủ áo.', '/lˈɔndɹi/', 'n.', 'reservation', 'TOEIC'),
  ('dry', 'giặt khô', 'Dry cleaning returns in 24 hours.', 'Giặt khô trả trong 24 giờ.', '/dɹˈaɪ/', 'n.', 'reservation', 'TOEIC'),
  ('ironing', 'là ủi', 'An ironing board is behind the door.', 'Cầu là ở sau cánh cửa.', '/ˈaɪɚnɪŋ/', 'n.', 'reservation', 'TOEIC'),
  ('wake', 'dịch vụ đánh thức', 'Request a wake-up call at the desk.', 'Yêu cầu đánh thức tại quầy.', '/wˈeɪk/', 'n.', 'reservation', 'TOEIC'),
  ('doorman', 'người gác cửa', 'The doorman will hail a taxi for you.', 'Người gác cửa sẽ gọi taxi giúp bạn.', '/dˈɔɹmˌæn/', 'n.', 'reservation', 'TOEIC'),
  ('bellhop', 'nhân viên khuân vác', 'A bellhop will take your bags upstairs.', 'Nhân viên khuân vác sẽ xách túi lên lầu.', '/bˈɛlhˌɑp/', 'n.', 'reservation', 'TOEIC'),
  ('porter', 'người khuân vác', 'The porter can store luggage until evening.', 'Người khuân vác có thể giữ hành lý đến tối.', '/pˈɔɹtɚ/', 'n.', 'reservation', 'TOEIC'),
  ('valet', 'nhân viên giữ xe', 'Valet parking is available at the side door.', 'Giữ xe có ở cửa bên.', '/vælˈeɪ/', 'n.', 'reservation', 'TOEIC'),
  ('carry-on', 'hành lý xách tay', 'One carry-on bag is allowed in the cabin.', 'Được mang một túi xách tay lên cabin.', '/ˈkæri.ɑn/', 'n.', 'itinerary', 'TOEIC'),
  ('checked', 'ký gửi', 'Checked bags may be collected at carousel 4.', 'Hành lý ký gửi lấy ở băng 4.', '/tʃˈɛkt/', 'adj.', 'itinerary', 'TOEIC'),
  ('overweight', 'quá cân', 'An overweight bag will incur an extra fee.', 'Túi quá cân sẽ bị phụ phí.', '/ˌoʊvɚwˈeɪt/', 'adj.', 'itinerary', 'TOEIC'),
  ('oversized', 'quá khổ', 'Oversized items must go to the oversize counter.', 'Đồ quá khổ phải ra quầy hàng cồng kềnh.', '/ˈoʊvɚsˌaɪzd/', 'adj.', 'itinerary', 'TOEIC'),
  ('turbulence', 'nhiễu động', 'The captain warned of light turbulence.', 'Cơ trưởng cảnh báo nhiễu động nhẹ.', '/tˈɝbjələns/', 'n.', 'itinerary', 'TOEIC'),
  ('jet', 'máy bay phản lực', 'The jet to Taipei leaves at dusk.', 'Máy bay phản lực đi Đài Bắc rời lúc chạng vạng.', '/dʒˈɛt/', 'n.', 'itinerary', 'TOEIC'),
  ('runway', 'đường băng', 'Fog closed the runway for an hour.', 'Sương mù đóng đường băng một giờ.', '/ɹˈʌnwˌeɪ/', 'n.', 'itinerary', 'TOEIC'),
  ('taxiway', 'đường lăn', 'The plane waited on the taxiway.', 'Máy bay chờ trên đường lăn.', '/tˈæksiweɪ/', 'n.', 'itinerary', 'TOEIC'),
  ('hangar', 'nhà chứa máy bay', 'Maintenance is done in the hangar.', 'Bảo trì được làm trong nhà chứa máy bay.', '/hˈæŋɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('cockpit', 'buồng lái', 'Only crew may enter the cockpit.', 'Chỉ phi hành đoàn được vào buồng lái.', '/kˈɑkpˌɪt/', 'n.', 'itinerary', 'TOEIC'),
  ('cabin', 'cabin', 'The cabin lights dim after takeoff.', 'Đèn cabin mờ sau khi cất cánh.', '/kˈæbən/', 'n.', 'itinerary', 'TOEIC'),
  ('takeoff', 'cất cánh', 'Please remain seated during takeoff.', 'Vui lòng ngồi yên khi cất cánh.', '/tˈeɪkˌɔf/', 'n.', 'itinerary', 'TOEIC'),
  ('landing', 'hạ cánh', 'Landing is expected at 4:10 p.m.', 'Hạ cánh dự kiến lúc 4:10 chiều.', '/lˈændɪŋ/', 'n.', 'itinerary', 'TOEIC'),
  ('altitude', 'độ cao', 'The aircraft reached cruising altitude.', 'Máy bay đạt độ cao hành trình.', '/ˈæltətˌud/', 'n.', 'itinerary', 'TOEIC'),
  ('turbine', 'tuabin', 'Engineers inspected the turbine overnight.', 'Kỹ sư kiểm tra tuabin qua đêm.', '/tˈɝbaɪn/', 'n.', 'inventory', 'TOEIC'),
  ('fuel', 'nhiên liệu', 'Fuel prices raised the airfares.', 'Giá nhiên liệu làm tăng vé máy bay.', '/fjˈuəl/', 'n.', 'itinerary', 'TOEIC'),
  ('airfare', 'giá vé máy bay', 'The cheapest airfare includes one bag.', 'Giá vé rẻ nhất gồm một kiện hành lý.', '/ˈɛɹfˌɛɹ/', 'n.', 'itinerary', 'TOEIC'),
  ('standby', 'chờ vé', 'Standby seats may open at the gate.', 'Ghế chờ vé có thể mở ở cổng.', '/stˈændbˈaɪ/', 'n.', 'itinerary', 'TOEIC'),
  ('downgrade', 'hạ hạng', 'A downgrade comes with a partial refund.', 'Hạ hạng kèm hoàn một phần tiền.', '/dˈaʊnɡɹˈeɪd/', 'n.', 'itinerary', 'TOEIC'),
  ('rebook', 'đặt lại', 'The agent will rebook you on the next flight.', 'Nhân viên sẽ đặt lại chuyến sau cho bạn.', '/ɹibˈʊk/', 'v.', 'itinerary', 'TOEIC'),
  ('reroute', 'đổi tuyến', 'Storms forced the airline to reroute planes.', 'Bão buộc hãng đổi tuyến máy bay.', '/ɹiɹˈut/', 'v.', 'itinerary', 'TOEIC'),
  ('stopover', 'điểm dừng', 'There is a one-night stopover in Doha.', 'Có một đêm dừng ở Doha.', '/stˈɑpˌoʊvɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('direct', 'bay thẳng', 'A direct flight is shorter than a connecting one.', 'Chuyến bay thẳng ngắn hơn chuyến nối.', '/dɚˈɛkt/', 'adj.', 'itinerary', 'TOEIC'),
  ('nonstop', 'không dừng', 'The nonstop service to Busan starts in July.', 'Chuyến không dừng tới Busan bắt đầu tháng Bảy.', '/nˌɑnstˈɑp/', 'adj.', 'itinerary', 'TOEIC'),
  ('charter', 'chuyến thuê bao', 'The company booked a charter for the team.', 'Công ty thuê chuyến charter cho đoàn.', '/tʃˈɑɹtɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('commuter', 'người đi làm', 'Commuters fill the 7:15 train every weekday.', 'Người đi làm đông trên tàu 7:15 ngày thường.', '/kəmjˈutɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('express', 'tàu/xe tốc hành', 'The airport express runs every 20 minutes.', 'Tàu tốc hành sân bay chạy mỗi 20 phút.', '/ɪkspɹˈɛs/', 'n.', 'itinerary', 'TOEIC'),
  ('local', 'tàu dừng nhiều ga', 'Take the local train if you need Station 8.', 'Đi tàu dừng nhiều ga nếu bạn cần ga 8.', '/lˈoʊkəl/', 'n.', 'itinerary', 'TOEIC'),
  ('platform', 'sân ga', 'Wait on platform 3 for the northbound train.', 'Chờ ở sân ga 3 cho tàu hướng bắc.', '/plˈætfˌɔɹm/', 'n.', 'itinerary', 'TOEIC'),
  ('timetable', 'bảng giờ', 'A new timetable takes effect on Monday.', 'Bảng giờ mới có hiệu lực thứ Hai.', '/tˈaɪmtˌeɪbəl/', 'n.', 'deadline', 'TOEIC'),
  ('punctuality', 'sự đúng giờ', 'Punctuality is part of the driver''s review.', 'Sự đúng giờ nằm trong đánh giá tài xế.', '/pˌʌŋktʃuˈælɪti/', 'n.', 'deadline', 'TOEIC'),
  ('detour', 'đường vòng', 'Follow the detour around the closed bridge.', 'Đi đường vòng tránh cầu đóng.', '/dɪtˈʊɹ/', 'n.', 'itinerary', 'TOEIC'),
  ('congestion', 'tình trạng ùn tắc', 'Morning congestion is worse near the port.', 'Ùn tắc sáng nặng hơn gần cảng.', '/kəndʒˈɛstʃən/', 'n.', 'shipment', 'TOEIC'),
  ('toll', 'phí cầu đường', 'The toll is paid at the booth by card.', 'Phí cầu đường trả bằng thẻ ở quầy.', '/tˈoʊl/', 'n.', 'itinerary', 'TOEIC'),
  ('zone', 'vùng', 'This ticket is valid in zone 1 and 2.', 'Vé này có hiệu lực ở vùng 1 và 2.', '/zˈoʊn/', 'n.', 'itinerary', 'TOEIC'),
  ('pass', 'vé thông hành', 'A weekly pass is cheaper for commuters.', 'Vé tuần rẻ hơn cho người đi làm.', '/pˈæs/', 'n.', 'itinerary', 'TOEIC'),
  ('token', 'jeton', 'The old subway still uses a metal token.', 'Tàu điện cũ vẫn dùng jeton kim loại.', '/tˈoʊkən/', 'n.', 'itinerary', 'TOEIC'),
  ('kiosk', 'ki-ốt', 'Buy a city map at the tourist kiosk.', 'Mua bản đồ ở ki-ốt du lịch.', '/kˈiˌɔsk/', 'n.', 'brochure', 'TOEIC'),
  ('guidebook', 'sách hướng dẫn', 'The guidebook lists quiet cafés nearby.', 'Sách hướng dẫn liệt kê quán cà phê yên gần đó.', '/ɡˈaɪdbˌʊk/', 'n.', 'itinerary', 'TOEIC'),
  ('landmark', 'địa danh', 'The clock tower is a local landmark.', 'Tháp đồng hồ là địa danh địa phương.', '/lˈændmˌɑɹk/', 'n.', 'itinerary', 'TOEIC'),
  ('attraction', 'điểm tham quan', 'The museum is the city''s top attraction.', 'Bảo tàng là điểm tham quan hàng đầu.', '/ətɹˈækʃən/', 'n.', 'itinerary', 'TOEIC'),
  ('admission', 'phí vào cửa', 'Admission is free on the first Sunday.', 'Vào cửa miễn phí Chủ nhật đầu tháng.', '/ædmˈɪʃən/', 'n.', 'brochure', 'TOEIC'),
  ('postcard', 'bưu thiếp', 'Postcards are sold at the gift counter.', 'Bưu thiếp bán ở quầy quà.', '/pˈoʊstkˌɑɹd/', 'n.', 'brochure', 'TOEIC'),
  ('rate', 'tỷ giá / mức', 'The room rate includes tax.', 'Giá phòng đã gồm thuế.', '/ɹˈeɪt/', 'n.', 'reservation', 'TOEIC'),
  ('tip', 'tiền tip', 'A 10 percent tip is customary here.', 'Tiền tip 10 phần trăm là thông lệ ở đây.', '/tˈɪp/', 'n.', 'complimentary', 'TOEIC'),
  ('tab', 'hóa đơn quán', 'Please put the coffee on my tab.', 'Làm ơn ghi cà phê vào hóa đơn của tôi.', '/tˈæb/', 'n.', 'complimentary', 'TOEIC'),
  ('split', 'chia (hóa đơn)', 'We can split the bill into three parts.', 'Chúng ta có thể chia hóa đơn làm ba.', '/splˈɪt/', 'v.', 'complimentary', 'TOEIC'),
  ('waitlist', 'danh sách chờ', 'Your name is on the waitlist for 7 p.m.', 'Tên bạn ở danh sách chờ lúc 7 giờ tối.', '/ˈweɪt.lɪst/', 'n.', 'reservation', 'TOEIC'),
  ('no-show', 'khách đặt rồi không đến', 'A no-show still counts against occupancy.', 'Khách không đến vẫn tính vào công suất.', '/ˈnoʊ.ʃoʊ/', 'n.', 'occupancy', 'TOEIC'),
  ('overbook', 'đặt quá số chỗ', 'Airlines sometimes overbook popular flights.', 'Hãng đôi khi đặt quá chỗ chuyến đông.', '/ˈoʊvɚbˌʊk/', 'v.', 'itinerary', 'TOEIC'),
  ('walk-in', 'khách vãng lai', 'Walk-in guests may wait for a canceled table.', 'Khách vãng lai có thể chờ bàn bị hủy.', '/ˈwɔk.ɪn/', 'n.', 'reservation', 'TOEIC'),
  ('hostess', 'người dẫn chỗ', 'The hostess will seat you in a moment.', 'Người dẫn chỗ sẽ mời bạn ngồi ngay.', '/hˈoʊstəs/', 'n.', 'complimentary', 'TOEIC'),
  ('waiter', 'bồi bàn nam', 'Ask the waiter for the wine list.', 'Hỏi bồi bàn danh sách rượu.', '/wˈeɪtɚ/', 'n.', 'complimentary', 'TOEIC'),
  ('waitress', 'bồi bàn nữ', 'The waitress brought extra napkins.', 'Bồi bàn mang thêm khăn giấy.', '/wˈeɪtɹəs/', 'n.', 'complimentary', 'TOEIC'),
  ('chef', 'bếp trưởng', 'The chef changes the menu each season.', 'Bếp trưởng đổi thực đơn mỗi mùa.', '/ʃˈɛf/', 'n.', 'complimentary', 'TOEIC'),
  ('cuisine', 'ẩm thực', 'The hotel is known for regional cuisine.', 'Khách sạn nổi tiếng ẩm thực vùng.', '/kwɪzˈin/', 'n.', 'complimentary', 'TOEIC'),
  ('specialty', 'món đặc trưng', 'Grilled fish is the house specialty.', 'Cá nướng là món đặc trưng của quán.', '/spˈɛʃəlti/', 'n.', 'complimentary', 'TOEIC'),
  ('entree', 'món chính', 'The entree comes with soup or salad.', 'Món chính kèm súp hoặc salad.', '/ˈɑntɹˌeɪ/', 'n.', 'complimentary', 'TOEIC'),
  ('refill', 'đổ thêm', 'Coffee refills are free during breakfast.', 'Đổ thêm cà phê miễn phí lúc ăn sáng.', '/ɹˈifɪl/', 'n.', 'complimentary', 'TOEIC'),
  ('a-la-carte', 'gọi món', 'A-la-carte dining starts at 6 p.m.', 'Gọi món bắt đầu lúc 6 giờ tối.', '/ɑ.ləˈkɑrt/', 'adj.', 'complimentary', 'TOEIC'),
  ('vegetarian', 'chay', 'Vegetarian meals can be requested in advance.', 'Suất chay có thể yêu cầu trước.', '/vˌɛdʒətˈɛɹˌiən/', 'adj.', 'complimentary', 'TOEIC'),
  ('allergy', 'dị ứng', 'Please tell the kitchen about any food allergy.', 'Hãy báo bếp nếu bị dị ứng thức ăn.', '/ˈælɚdʒi/', 'n.', 'complimentary', 'TOEIC'),
  ('ingredient', 'nguyên liệu', 'The soup''s ingredients are listed on the board.', 'Nguyên liệu súp được ghi trên bảng.', '/ˌɪnɡɹˈidiənt/', 'n.', 'inventory', 'TOEIC'),
  ('recipe', 'công thức', 'The chef will not share the secret recipe.', 'Bếp trưởng không chia sẻ công thức bí mật.', '/ɹˈɛsəpi/', 'n.', 'complimentary', 'TOEIC'),
  ('portion', 'khẩu phần', 'Lunch portions are smaller than dinner ones.', 'Khẩu phần trưa nhỏ hơn bữa tối.', '/pˈɔɹʃən/', 'n.', 'complimentary', 'TOEIC'),
  ('platter', 'đĩa lớn', 'A fruit platter is on the conference table.', 'Đĩa trái cây ở bàn hội nghị.', '/plˈætɚ/', 'n.', 'conference', 'TOEIC'),
  ('cater', 'cung cấp đồ ăn', 'A local shop will cater the afternoon break.', 'Một tiệm địa phương sẽ cung cấp đồ ăn giờ giải lao.', '/kˈeɪtɚ/', 'v.', 'conference', 'TOEIC'),
  ('reception', 'tiệc chiêu đãi / lễ tân', 'A welcome reception begins at 6:30.', 'Tiệc chào mừng bắt đầu lúc 6:30.', '/ɹɪsˈɛpʃən/', 'n.', 'conference', 'TOEIC'),
  ('cocktail', 'tiệc cocktail', 'The cocktail hour is in the courtyard.', 'Giờ cocktail ở sân trong.', '/kˈɑktˌeɪl/', 'n.', 'conference', 'TOEIC'),
  ('toast', 'lời nâng ly', 'The director gave a short toast.', 'Giám đốc nói một lời nâng ly ngắn.', '/tˈoʊst/', 'n.', 'conference', 'TOEIC'),
  ('keynote', 'bài phát biểu chính', 'The keynote will be translated live.', 'Bài phát biểu chính sẽ được dịch trực tiếp.', '/kˈinˌoʊt/', 'n.', 'conference', 'TOEIC'),
  ('panel', 'tọa đàm', 'The panel includes three hotel managers.', 'Tọa đàm có ba quản lý khách sạn.', '/pˈænəl/', 'n.', 'conference', 'TOEIC'),
  ('moderator', 'người điều phối', 'A moderator will keep the debate on time.', 'Người điều phối giữ cuộc tranh luận đúng giờ.', '/mˈɑdɚˌeɪtɚ/', 'n.', 'conference', 'TOEIC'),
  ('attendee', 'người tham dự', 'Each attendee receives a printed agenda.', 'Mỗi người tham dự nhận chương trình in.', '/ətˈɛndˈi/', 'n.', 'conference', 'TOEIC'),
  ('organizer', 'ban tổ chức', 'The organizer posted a map of the halls.', 'Ban tổ chức dán bản đồ các hội trường.', '/ˈɔɹɡənˌaɪzɚ/', 'n.', 'conference', 'TOEIC'),
  ('sponsor', 'nhà tài trợ', 'A sponsor provided the lanyards.', 'Nhà tài trợ cung cấp dây đeo thẻ.', '/spˈɑnsɚ/', 'n.', 'brochure', 'TOEIC'),
  ('exhibitor', 'đơn vị trưng bày', 'Exhibitors may set up after 7 a.m.', 'Đơn vị trưng bày được bày sau 7 giờ sáng.', '/ɪɡzˈɪbətɚ/', 'n.', 'conference', 'TOEIC'),
  ('handout', 'tài liệu phát', 'Please take one handout per person.', 'Vui lòng lấy một tài liệu mỗi người.', '/hˈændˌaʊt/', 'n.', 'conference', 'TOEIC'),
  ('proceedings', 'kỷ yếu', 'The proceedings will be emailed next week.', 'Kỷ yếu sẽ được gửi email tuần tới.', '/pɹoʊsˈidɪŋz/', 'n.', 'conference', 'TOEIC'),
  ('networking', 'giao lưu nghề nghiệp', 'Networking is scheduled after the last talk.', 'Giao lưu nghề nghiệp sau bài nói cuối.', '/nˈɛtwˌɝkɪŋ/', 'n.', 'conference', 'TOEIC'),
  ('breakout', 'phiên nhóm nhỏ', 'Join a breakout on hotel marketing.', 'Tham gia phiên nhóm nhỏ về marketing khách sạn.', '/bɹˈeɪkˌaʊt/', 'n.', 'conference', 'TOEIC'),
  ('plenary', 'phiên toàn thể', 'The plenary meets in Hall A.', 'Phiên toàn thể họp ở hội trường A.', '/plˈɛnɚi/', 'n.', 'conference', 'TOEIC'),
  ('adjournment', 'việc tạm nghỉ', 'Adjournment is expected at 5 p.m.', 'Tạm nghỉ dự kiến lúc 5 giờ chiều.', '/ədʒˈɝnmənt/', 'n.', 'deadline', 'TOEIC'),
  ('quorum', 'số đại biểu tối thiểu', 'We cannot vote without a quorum.', 'Không thể bỏ phiếu khi chưa đủ số đại biểu.', '/kwˈɔɹəm/', 'n.', 'conference', 'TOEIC'),
  ('motion', 'kiến nghị', 'Someone seconded the motion to extend hours.', 'Có người tán thành kiến nghị kéo dài giờ.', '/mˈoʊʃən/', 'n.', 'conference', 'TOEIC'),
  ('ballot', 'phiếu bầu', 'Place your ballot in the sealed box.', 'Bỏ phiếu vào hộp niêm phong.', '/bˈælət/', 'n.', 'conference', 'TOEIC'),
  ('unanimous', 'đồng thuận', 'The board reached a unanimous decision.', 'Hội đồng đi đến quyết định đồng thuận.', '/junˈænəməs/', 'adj.', 'conference', 'TOEIC'),
  ('majority', 'đa số', 'A majority voted for the new logo.', 'Đa số bỏ phiếu cho logo mới.', '/mədʒˈɔɹəti/', 'n.', 'brochure', 'TOEIC'),
  ('chairperson', 'chủ tọa', 'The chairperson opened the annual meeting.', 'Chủ tọa khai mạc cuộc họp thường niên.', '/tʃˈɛɹpˌɝsən/', 'n.', 'conference', 'TOEIC'),
  ('vice', 'phó', 'The vice president will chair if she is away.', 'Phó chủ tịch sẽ chủ trì nếu cô ấy vắng.', '/vˈaɪs/', 'n.', 'headquarters', 'TOEIC'),
  ('treasurer', 'thủ quỹ', 'The treasurer presented the yearly figures.', 'Thủ quỹ trình bày số liệu năm.', '/tɹˈɛʒɚɚ/', 'n.', 'budget', 'TOEIC'),
  ('bylaw', 'nội quy', 'A bylaw change needs a two-thirds vote.', 'Sửa nội quy cần hai phần ba phiếu.', '/bˈaɪlˌɔ/', 'n.', 'authorize', 'TOEIC'),
  ('membership', 'tư cách thành viên', 'Membership includes use of the lounge.', 'Tư cách thành viên gồm dùng phòng lounge.', '/mˈɛmbɚʃˌɪp/', 'n.', 'brochure', 'TOEIC'),
  ('dues', 'phí hội viên', 'Annual dues are collected in January.', 'Phí hội viên thu vào tháng Giêng.', '/dˈuz/', 'n.', 'budget', 'TOEIC'),
  ('newsletter', 'bản tin', 'The newsletter is mailed on the first Monday.', 'Bản tin được gửi thứ Hai đầu tháng.', '/nˈuzlˌɛtɚ/', 'n.', 'memo', 'TOEIC'),
  ('press', 'báo chí', 'The press will wait in the briefing room.', 'Báo chí chờ ở phòng họp báo.', '/pɹˈɛs/', 'n.', 'conference', 'TOEIC'),
  ('journalist', 'nhà báo', 'A journalist asked about the merger.', 'Một nhà báo hỏi về vụ sáp nhập.', '/dʒˈɝnələst/', 'n.', 'brochure', 'TOEIC'),
  ('headline', 'tít báo', 'The headline mentioned the new factory.', 'Tít báo nhắc nhà máy mới.', '/hˈɛdlˌaɪn/', 'n.', 'brochure', 'TOEIC'),
  ('article', 'bài báo', 'Please clip the article for the files.', 'Vui lòng cắt bài báo lưu hồ sơ.', '/ˈɑɹtəkəl/', 'n.', 'memo', 'TOEIC'),
  ('editorial', 'xã luận', 'The editorial praised the safety record.', 'Xã luận khen thành tích an toàn.', '/ˌɛdətˈɔɹiəl/', 'n.', 'brochure', 'TOEIC'),
  ('quote', 'lời trích / báo giá', 'May I quote you in tomorrow''s paper?', 'Tôi có thể trích lời bạn trên báo mai không?', '/kwˈoʊt/', 'n.', 'brochure', 'TOEIC'),
  ('embargo', 'lệnh cấm đưa tin', 'The report is under embargo until noon.', 'Báo cáo bị cấm đưa tin đến trưa.', '/ɛmbˈɑɹɡoʊ/', 'n.', 'memo', 'TOEIC'),
  ('release', 'thông cáo', 'A press release will go out at 9 a.m.', 'Thông cáo báo chí sẽ ra lúc 9 giờ sáng.', '/ɹilˈis/', 'n.', 'brochure', 'TOEIC'),
  ('target', 'đối tượng / mục tiêu', 'Young travelers are the campaign''s target.', 'Khách trẻ là đối tượng của chiến dịch.', '/tˈɑɹɡət/', 'n.', 'brochure', 'TOEIC'),
  ('segment', 'phân khúc', 'We added a segment for family travelers.', 'Chúng tôi thêm phân khúc khách gia đình.', '/sˈɛɡmənt/', 'n.', 'brochure', 'TOEIC'),
  ('niche', 'thị phần ngách', 'The shop found a niche in handmade soaps.', 'Cửa hàng tìm được ngách xà phòng handmade.', '/nˈɪtʃ/', 'n.', 'brochure', 'TOEIC'),
  ('branding', 'xây dựng thương hiệu', 'Branding on the vans must match the logo.', 'Thương hiệu trên xe phải khớp logo.', '/bɹˈændɪŋ/', 'n.', 'brochure', 'TOEIC'),
  ('rebrand', 'đổi nhận diện', 'The chain will rebrand next spring.', 'Chuỗi sẽ đổi nhận diện vào mùa xuân tới.', '/ˌriˈbrænd/', 'v.', 'brochure', 'TOEIC'),
  ('tagline', 'câu khẩu hiệu phụ', 'The tagline appears under every logo.', 'Câu khẩu hiệu phụ nằm dưới mọi logo.', '/tˈæɡlˌaɪn/', 'n.', 'brochure', 'TOEIC'),
  ('mascot', 'linh vật', 'A cat mascot greets children in the lobby.', 'Linh vật mèo chào trẻ ở sảnh.', '/mˈæskət/', 'n.', 'brochure', 'TOEIC'),
  ('endorsement', 'sự chứng thực', 'The chef''s endorsement lifted soup sales.', 'Sự chứng thực của bếp trưởng làm tăng bán súp.', '/ɛndˈɔɹsmənt/', 'n.', 'brochure', 'TOEIC'),
  ('testimonial', 'lời chứng thực', 'A guest testimonial is printed on the flyer.', 'Lời chứng thực của khách được in trên tờ rơi.', '/tˌɛstəmˈoʊniəl/', 'n.', 'brochure', 'TOEIC'),
  ('influencer', 'người có ảnh hưởng', 'An influencer filmed the new suite.', 'Người có ảnh hưởng quay phòng suite mới.', '/ˈɪn.flu.ən.sɚ/', 'n.', 'brochure', 'TOEIC'),
  ('hashtag', 'hashtag', 'Use the event hashtag on every post.', 'Dùng hashtag sự kiện trên mọi bài đăng.', '/hˈæʃtˌæɡ/', 'n.', 'brochure', 'TOEIC'),
  ('website', 'trang web', 'The website lists live room availability.', 'Trang web liệt kê phòng còn trống.', '/wˈɛbsˌaɪt/', 'n.', 'reservation', 'TOEIC'),
  ('homepage', 'trang chủ', 'A booking button sits on the homepage.', 'Nút đặt phòng nằm ở trang chủ.', '/hˈoʊmpˌeɪdʒ/', 'n.', 'brochure', 'TOEIC'),
  ('browser', 'trình duyệt', 'The form works in every major browser.', 'Mẫu đơn chạy trên mọi trình duyệt lớn.', '/bɹˈaʊzɚ/', 'n.', 'memo', 'TOEIC'),
  ('click', 'nhấp', 'Click the blue button to confirm.', 'Nhấp nút xanh để xác nhận.', '/klˈɪk/', 'v.', 'memo', 'TOEIC'),
  ('link', 'liên kết', 'The reset link expires in 20 minutes.', 'Liên kết đặt lại hết hạn sau 20 phút.', '/lˈɪŋk/', 'n.', 'memo', 'TOEIC'),
  ('login', 'đăng nhập', 'A new login is required after the upgrade.', 'Cần đăng nhập mới sau khi nâng cấp.', '/lˈɔɡˌɪn/', 'n.', 'authorize', 'TOEIC'),
  ('logout', 'đăng xuất', 'Please logout when you leave the desk.', 'Vui lòng đăng xuất khi rời bàn.', '/lˈɔɡˌaʊt/', 'v.', 'authorize', 'TOEIC'),
  ('username', 'tên đăng nhập', 'Your username is the company email.', 'Tên đăng nhập là email công ty.', '/jˈuzɚnˌeɪm/', 'n.', 'authorize', 'TOEIC'),
  ('profile', 'hồ sơ tài khoản', 'Update your profile photo this week.', 'Cập nhật ảnh hồ sơ tuần này.', '/pɹˈoʊfˌaɪl/', 'n.', 'memo', 'TOEIC'),
  ('settings', 'cài đặt', 'Language settings are under the gear icon.', 'Cài đặt ngôn ngữ ở biểu tượng bánh răng.', '/sˈɛtɪŋz/', 'n.', 'memo', 'TOEIC'),
  ('notification', 'thông báo', 'Turn off sound for night notifications.', 'Tắt tiếng thông báo ban đêm.', '/nˌoʊtəfəkˈeɪʃən/', 'n.', 'memo', 'TOEIC'),
  ('spam', 'thư rác', 'Move spam to the junk folder.', 'Chuyển thư rác vào thư mục junk.', '/spˈæm/', 'n.', 'memo', 'TOEIC'),
  ('inbox', 'hộp thư đến', 'Check the inbox before the meeting.', 'Xem hộp thư đến trước cuộc họp.', '/ˈɪnbˌɑks/', 'n.', 'memo', 'TOEIC'),
  ('outbox', 'hộp thư đi', 'A stuck message is sitting in the outbox.', 'Một thư bị kẹt trong hộp thư đi.', '/ˈaʊt.bɑks/', 'n.', 'memo', 'TOEIC'),
  ('attachment', 'tệp đính kèm', 'The attachment is too large to send.', 'Tệp đính kèm quá lớn để gửi.', '/ətˈætʃmənt/', 'n.', 'memo', 'TOEIC'),
  ('folder', 'thư mục', 'Put invoices in the tax folder.', 'Để hóa đơn vào thư mục thuế.', '/fˈoʊldɚ/', 'n.', 'invoice', 'TOEIC'),
  ('file', 'tệp / hồ sơ', 'Save the file with yesterday''s date.', 'Lưu tệp với ngày hôm qua.', '/fˈaɪl/', 'n.', 'memo', 'TOEIC'),
  ('cloud', 'điện toán đám mây', 'Photos are stored in the cloud.', 'Ảnh được lưu trên đám mây.', '/klˈaʊd/', 'n.', 'memo', 'TOEIC'),
  ('sync', 'đồng bộ', 'The phone will sync contacts overnight.', 'Điện thoại sẽ đồng bộ danh bạ qua đêm.', '/sˈɪŋk/', 'v.', 'memo', 'TOEIC'),
  ('offline', 'ngoại tuyến', 'The catalog can be read offline.', 'Danh mục có thể đọc khi ngoại tuyến.', '/ˈɔflˌaɪn/', 'adj.', 'brochure', 'TOEIC'),
  ('online', 'trực tuyến', 'Online check-in opens 24 hours before the flight.', 'Làm thủ tục trực tuyến mở 24 giờ trước chuyến bay.', '/ˈɔnlˌaɪn/', 'adj.', 'itinerary', 'TOEIC'),
  ('digital', 'kỹ thuật số', 'A digital copy is emailed after payment.', 'Bản kỹ thuật số được gửi email sau khi thanh toán.', '/dˈɪdʒətəl/', 'adj.', 'invoice', 'TOEIC'),
  ('paperless', 'không giấy', 'The office is moving to paperless billing.', 'Văn phòng chuyển sang lập hóa đơn không giấy.', '/pˈeɪpɚləs/', 'adj.', 'invoice', 'TOEIC'),
  ('sustainable', 'bền vững', 'The inn uses sustainable cleaning products.', 'Nhà nghỉ dùng đồ vệ sinh bền vững.', '/səstˈeɪnəbəl/', 'adj.', 'brochure', 'TOEIC'),
  ('eco-friendly', 'thân thiện môi trường', 'Eco-friendly packaging replaced plastic wrap.', 'Bao bì thân thiện môi trường thay màng nhựa.', '/ˈikoʊ.frend.li/', 'adj.', 'brochure', 'TOEIC'),
  ('carbon', 'carbon', 'The firm tracks carbon from company flights.', 'Công ty theo dõi carbon từ chuyến bay công tác.', '/kˈɑɹbən/', 'n.', 'itinerary', 'TOEIC'),
  ('emission', 'khí thải', 'New trucks cut emission levels by 20 percent.', 'Xe tải mới giảm khí thải 20 phần trăm.', '/ɪmˈɪʃən/', 'n.', 'shipment', 'TOEIC'),
  ('pollution', 'ô nhiễm', 'The plant reduced water pollution last year.', 'Nhà máy giảm ô nhiễm nước năm ngoái.', '/pəlˈuʃən/', 'n.', 'inventory', 'TOEIC'),
  ('waste', 'rác thải', 'Food waste is collected in a separate bin.', 'Rác thức ăn được thu ở thùng riêng.', '/wˈeɪst/', 'n.', 'inventory', 'TOEIC'),
  ('landfill', 'bãi chôn lấp', 'Less packaging means less landfill.', 'Ít bao bì hơn nghĩa là ít chôn lấp hơn.', '/lˈændfˌɪl/', 'n.', 'inventory', 'TOEIC'),
  ('compost', 'phân ủ', 'Kitchen scraps go into the compost bin.', 'Rác bếp cho vào thùng phân ủ.', '/kˈɑmpoʊst/', 'n.', 'inventory', 'TOEIC'),
  ('organic', 'hữu cơ', 'The café serves organic tea in the lounge.', 'Quán phục vụ trà hữu cơ ở lounge.', '/ɔɹɡˈænɪk/', 'adj.', 'complimentary', 'TOEIC'),
  ('fair', 'công bằng / thương mại công bằng', 'The shop sells fair-trade coffee.', 'Cửa hàng bán cà phê thương mại công bằng.', '/fˈɛɹ/', 'adj.', 'brochure', 'TOEIC'),
  ('ethical', 'đạo đức', 'Ethical sourcing is listed in the annual report.', 'Nguồn hàng đạo đức được ghi trong báo cáo năm.', '/ˈɛθɪkəl/', 'adj.', 'brochure', 'TOEIC'),
  ('transparency', 'minh bạch', 'Price transparency helps guests compare rooms.', 'Minh bạch giá giúp khách so phòng.', '/tɹænspˈɛɹənsi/', 'n.', 'reservation', 'TOEIC'),
  ('accountability', 'trách nhiệm giải trình', 'Managers accept accountability for safety.', 'Quản lý nhận trách nhiệm giải trình về an toàn.', '/əkˈaʊntəbˌɪlɪti/', 'n.', 'employee', 'TOEIC'),
  ('integrity', 'chính trực', 'Integrity is part of the hiring interview.', 'Chính trực nằm trong buổi phỏng vấn tuyển.', '/ˌɪntˈɛɡɹəti/', 'n.', 'applicant', 'TOEIC'),
  ('compliance', 'tuân thủ', 'A compliance officer reviews every contract.', 'Nhân viên tuân thủ rà soát mọi hợp đồng.', '/kəmplˈaɪəns/', 'n.', 'authorize', 'TOEIC'),
  ('inspector', 'thanh tra', 'A fire inspector will visit on Thursday.', 'Thanh tra PCCC sẽ đến vào thứ Năm.', '/ˌɪnspˈɛktɚ/', 'n.', 'authorize', 'TOEIC'),
  ('violation', 'vi phạm', 'A parking violation may result in a fine.', 'Vi phạm đỗ xe có thể bị phạt.', '/vaɪəlˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('fine', 'tiền phạt', 'The fine for smoking indoors is 50 dollars.', 'Tiền phạt hút thuốc trong nhà là 50 đô la.', '/fˈaɪn/', 'n.', 'authorize', 'TOEIC'),
  ('citation', 'biên bản phạt', 'The driver received a citation for blocking the dock.', 'Tài xế nhận biên bản vì chặn bến.', '/saɪtˈeɪʃən/', 'n.', 'shipment', 'TOEIC'),
  ('hazard', 'mối nguy', 'Wet floors are a slipping hazard.', 'Sàn ướt là mối nguy trượt.', '/hˈæzɚd/', 'n.', 'inventory', 'TOEIC'),
  ('precaution', 'biện pháp phòng ngừa', 'Wear goggles as a precaution.', 'Đeo kính bảo hộ làm biện pháp phòng ngừa.', '/pɹikˈɔʃən/', 'n.', 'inventory', 'TOEIC'),
  ('emergency', 'tình huống khẩn', 'The emergency exit is behind the stage.', 'Lối thoát khẩn ở sau sân khấu.', '/ɪmˈɝdʒənsi/', 'n.', 'conference', 'TOEIC'),
  ('evacuation', 'sơ tán', 'Evacuation maps are posted by the stairs.', 'Bản đồ sơ tán dán cạnh cầu thang.', '/ɪvˌækjəwˈeɪʃən/', 'n.', 'headquarters', 'TOEIC'),
  ('assembly', 'điểm tập trung', 'Meet at the assembly point in the parking lot.', 'Tập trung ở điểm tập trung trong bãi xe.', '/əsˈɛmbli/', 'n.', 'headquarters', 'TOEIC'),
  ('extinguisher', 'bình chữa cháy', 'An extinguisher hangs next to the kitchen.', 'Bình chữa cháy treo cạnh bếp.', '/ɪkstˈɪŋɡwɪʃɚ/', 'n.', 'inventory', 'TOEIC'),
  ('sprinkler', 'vòi phun chữa cháy', 'A sprinkler test will run at dawn.', 'Thử vòi phun sẽ chạy lúc bình minh.', '/spɹˈɪŋklɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('alarm', 'chuông báo', 'Do not ignore a fire alarm.', 'Không bỏ qua chuông báo cháy.', '/əlˈɑɹm/', 'n.', 'authorize', 'TOEIC'),
  ('drill', 'buổi diễn tập', 'A fire drill is held every quarter.', 'Diễn tập cháy được tổ chức mỗi quý.', '/dɹˈɪl/', 'n.', 'employee', 'TOEIC'),
  ('first-aid', 'sơ cứu', 'A first-aid kit is at the reception desk.', 'Hộp sơ cứu ở quầy lễ tân.', '/ˈfɝst.eɪd/', 'n.', 'reservation', 'TOEIC'),
  ('paramedic', 'nhân viên cấp cứu', 'A paramedic is on call during the festival.', 'Nhân viên cấp cứu trực trong lễ hội.', '/pˌɛɹəmˈɛdɪk/', 'n.', 'employee', 'TOEIC'),
  ('clinic', 'phòng khám', 'The staff clinic opens at 8 a.m.', 'Phòng khám nhân viên mở lúc 8 giờ sáng.', '/klˈɪnɪk/', 'n.', 'employee', 'TOEIC'),
  ('pharmacy', 'nhà thuốc', 'The nearest pharmacy is two blocks east.', 'Nhà thuốc gần nhất cách hai khối phố về phía đông.', '/fˈɑɹməsi/', 'n.', 'itinerary', 'TOEIC'),
  ('prescription', 'đơn thuốc', 'A prescription is required for this medicine.', 'Cần đơn thuốc cho loại thuốc này.', '/pɹəskɹˈɪpʃən/', 'n.', 'authorize', 'TOEIC'),
  ('copay', 'khoản đồng chi trả', 'The clinic copay is 15 dollars.', 'Khoản đồng chi trả phòng khám là 15 đô la.', '/ˈkoʊ.peɪ/', 'n.', 'invoice', 'TOEIC'),
  ('adjuster', 'giám định viên bảo hiểm', 'An adjuster photographed the damaged crates.', 'Giám định viên chụp các thùng bị hỏng.', '/ədʒˈʌstɚ/', 'n.', 'shipment', 'TOEIC'),
  ('beneficiary', 'người thụ hưởng', 'Name a beneficiary on the policy form.', 'Ghi người thụ hưởng trên mẫu hợp đồng.', '/bˌɛnəfˈɪʃiˌɛɹi/', 'n.', 'authorize', 'TOEIC'),
  ('policyholder', 'chủ hợp đồng bảo hiểm', 'The policyholder must report theft within 24 hours.', 'Chủ hợp đồng phải báo trộm trong 24 giờ.', '/pˈɑləsihˌoʊldɚ/', 'n.', 'authorize', 'TOEIC'),
  ('underwrite', 'bảo lãnh bảo hiểm', 'The firm will underwrite the event insurance.', 'Công ty sẽ bảo lãnh bảo hiểm sự kiện.', '/ˈʌndɚɹˌaɪt/', 'v.', 'authorize', 'TOEIC'),
  ('negligence', 'sơ suất', 'The report found no negligence by the driver.', 'Báo cáo không thấy sơ suất của tài xế.', '/nˈɛɡlədʒəns/', 'n.', 'authorize', 'TOEIC'),
  ('damages', 'tiền bồi thường thiệt hại', 'The court awarded damages to the hotel.', 'Tòa án tuyên tiền bồi thường cho khách sạn.', '/dˈæmədʒəz/', 'n.', 'authorize', 'TOEIC'),
  ('settlement', 'thỏa thuận bồi thường', 'A settlement ended the dispute last week.', 'Thỏa thuận bồi thường chấm dứt tranh chấp tuần trước.', '/sˈɛtəlmənt/', 'n.', 'authorize', 'TOEIC'),
  ('dispute', 'tranh chấp', 'A billing dispute should go to accounting.', 'Tranh chấp hóa đơn nên gửi kế toán.', '/dɪspjˈut/', 'n.', 'invoice', 'TOEIC'),
  ('mediation', 'hòa giải', 'Mediation is cheaper than a lawsuit.', 'Hòa giải rẻ hơn kiện tụng.', '/mˌidiˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('arbitration', 'trọng tài', 'The contract requires arbitration in Singapore.', 'Hợp đồng yêu cầu trọng tài tại Singapore.', '/ˌɑɹbɪtɹˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('plaintiff', 'nguyên đơn', 'The plaintiff asked for a public apology.', 'Nguyên đơn yêu cầu xin lỗi công khai.', '/plˈeɪntəf/', 'n.', 'authorize', 'TOEIC'),
  ('defendant', 'bị đơn', 'The defendant has 14 days to reply.', 'Bị đơn có 14 ngày để trả lời.', '/dɪfˈɛndənt/', 'n.', 'authorize', 'TOEIC'),
  ('verdict', 'phán quyết', 'The verdict was announced at noon.', 'Phán quyết được công bố lúc trưa.', '/vˈɝdɪkt/', 'n.', 'authorize', 'TOEIC'),
  ('appeal', 'kháng cáo', 'An appeal must be filed within 30 days.', 'Kháng cáo phải nộp trong 30 ngày.', '/əpˈil/', 'n.', 'authorize', 'TOEIC'),
  ('hearing', 'phiên điều trần', 'The hearing is open to the public.', 'Phiên điều trần mở cho công chúng.', '/hˈiɹɪŋ/', 'n.', 'authorize', 'TOEIC'),
  ('subpoena', 'trát đòi hầu tòa', 'A subpoena was delivered to the office.', 'Trát đòi hầu tòa được giao tới văn phòng.', '/səpˈinə/', 'n.', 'authorize', 'TOEIC'),
  ('testimony', 'lời khai', 'Her testimony lasted two hours.', 'Lời khai của cô ấy kéo dài hai giờ.', '/tˈɛstəmˌoʊni/', 'n.', 'authorize', 'TOEIC'),
  ('affidavit', 'bản khai có tuyên thệ', 'Sign the affidavit in front of a notary.', 'Ký bản khai trước công chứng viên.', '/ˌæfədˈeɪvət/', 'n.', 'authorize', 'TOEIC'),
  ('notary', 'công chứng viên', 'A notary sits in room 12 on Tuesdays.', 'Công chứng viên ngồi phòng 12 vào thứ Ba.', '/nˈoʊtɚi/', 'n.', 'authorize', 'TOEIC'),
  ('stamp', 'con dấu', 'The clerk put a stamp on each page.', 'Nhân viên đóng dấu mỗi trang.', '/stˈæmp/', 'n.', 'authorize', 'TOEIC'),
  ('seal', 'dấu niêm phong', 'Break the seal only when the goods arrive.', 'Chỉ bẻ dấu niêm khi hàng đến.', '/sˈil/', 'n.', 'shipment', 'TOEIC'),
  ('notarize', 'công chứng', 'We must notarize the power of attorney.', 'Chúng tôi phải công chứng giấy ủy quyền.', '/ˈnoʊ.tə.raɪz/', 'v.', 'authorize', 'TOEIC'),
  ('proxy', 'ủy quyền đại diện', 'You may vote by proxy if you cannot attend.', 'Bạn có thể bỏ phiếu ủy quyền nếu không dự.', '/pɹˈɑksi/', 'n.', 'conference', 'TOEIC'),
  ('revocation', 'thu hồi', 'Revocation of the permit takes effect today.', 'Việc thu hồi giấy phép có hiệu lực hôm nay.', '/ɹˌɛvəkˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('suspension', 'đình chỉ', 'A license suspension lasts 90 days.', 'Đình chỉ giấy phép kéo dài 90 ngày.', '/səspˈɛnʃən/', 'n.', 'authorize', 'TOEIC'),
  ('renewal', 'gia hạn', 'Submit a renewal 30 days before expiry.', 'Nộp gia hạn 30 ngày trước khi hết hạn.', '/ɹɪnˈuəl/', 'n.', 'deadline', 'TOEIC'),
  ('amendment', 'sửa đổi', 'An amendment was added to clause 4.', 'Một sửa đổi được thêm vào điều 4.', '/əmˈɛndmənt/', 'n.', 'authorize', 'TOEIC'),
  ('addendum', 'phụ lục', 'See the addendum for shipping rates.', 'Xem phụ lục về cước vận chuyển.', '/ədˈɛndəm/', 'n.', 'shipment', 'TOEIC'),
  ('appendix', 'phụ lục (cuối tài liệu)', 'Charts are in the appendix.', 'Biểu đồ nằm ở phụ lục.', '/əpˈɛndɪks/', 'n.', 'memo', 'TOEIC'),
  ('exhibit', 'tài liệu đính kèm vụ việc', 'Exhibit B shows the original invoice.', 'Tài liệu B cho thấy hóa đơn gốc.', '/ɪɡzˈɪbɪt/', 'n.', 'invoice', 'TOEIC'),
  ('stipulation', 'quy định trong hợp đồng', 'One stipulation forbids overnight parking.', 'Một quy định cấm đỗ xe qua đêm.', '/stˌɪpjəlˈeɪʃən/', 'n.', 'authorize', 'TOEIC'),
  ('waiver', 'giấy từ bỏ quyền', 'Sign a waiver before using the gym.', 'Ký giấy từ bỏ quyền trước khi dùng phòng gym.', '/wˈeɪvɚ/', 'n.', 'authorize', 'TOEIC'),
  ('waive', 'miễn', 'The hotel will waive the cancellation fee.', 'Khách sạn sẽ miễn phí hủy.', '/wˈeɪv/', 'v.', 'reservation', 'TOEIC'),
  ('opt-in', 'đăng ký nhận', 'Email opt-in is confirmed with a link.', 'Đăng ký nhận email được xác nhận bằng liên kết.', '/ˈɑpt.ɪn/', 'n.', 'brochure', 'TOEIC'),
  ('opt-out', 'hủy nhận', 'You may opt-out of marketing mail anytime.', 'Bạn có thể hủy nhận thư marketing bất cứ lúc nào.', '/ˈɑpt.aʊt/', 'v.', 'brochure', 'TOEIC'),
  ('privacy', 'quyền riêng tư', 'The privacy notice is posted at check-in.', 'Thông báo quyền riêng tư được dán lúc nhận phòng.', '/pɹˈaɪvəsi/', 'n.', 'authorize', 'TOEIC'),
  ('cookie', 'cookie (web)', 'The site uses a cookie to save language.', 'Trang dùng cookie để lưu ngôn ngữ.', '/kˈʊki/', 'n.', 'brochure', 'TOEIC'),
  ('encryption', 'mã hóa', 'Encryption protects card numbers in transit.', 'Mã hóa bảo vệ số thẻ khi truyền.', '/ɛnkɹˈɪpʃən/', 'n.', 'authorize', 'TOEIC'),
  ('firewall', 'tường lửa', 'The firewall blocked an unknown login.', 'Tường lửa chặn một lần đăng nhập lạ.', '/fˈaɪɹwɑl/', 'n.', 'authorize', 'TOEIC'),
  ('malware', 'mã độc', 'Do not install software that may contain malware.', 'Không cài phần mềm có thể chứa mã độc.', '/mˈælwˌɛɹ/', 'n.', 'memo', 'TOEIC'),
  ('phishing', 'lừa đảo qua mạng', 'Delete phishing mail that asks for passwords.', 'Xóa thư lừa đảo hỏi mật khẩu.', '/fˈɪʃɪŋ/', 'n.', 'memo', 'TOEIC'),
  ('downtime', 'thời gian ngừng hệ thống', 'Overnight downtime is used for updates.', 'Thời gian ngừng đêm dùng để cập nhật.', '/dˈaʊntˌaɪm/', 'n.', 'memo', 'TOEIC'),
  ('uptime', 'thời gian hệ thống chạy', 'The booking site had 99 percent uptime.', 'Trang đặt phòng chạy 99 phần trăm thời gian.', '/ˈʌp.taɪm/', 'n.', 'reservation', 'TOEIC'),
  ('bandwidth', 'băng thông', 'Video calls use more bandwidth than mail.', 'Gọi video dùng băng thông nhiều hơn thư.', '/bˈændwɪdθ/', 'n.', 'memo', 'TOEIC'),
  ('latency', 'độ trễ mạng', 'High latency made the call choppy.', 'Độ trễ cao làm cuộc gọi bị ngắt quãng.', '/lˈeɪtənsi/', 'n.', 'memo', 'TOEIC'),
  ('router', 'bộ định tuyến', 'The router is in the locked closet.', 'Bộ định tuyến ở tủ khóa.', '/ɹˈutɚ/', 'n.', 'headquarters', 'TOEIC'),
  ('modem', 'modem', 'A new modem will arrive on Tuesday.', 'Modem mới sẽ đến vào thứ Ba.', '/mˈoʊdəm/', 'n.', 'inventory', 'TOEIC'),
  ('hotspot', 'điểm phát wifi', 'A guest hotspot is available in the lobby.', 'Điểm phát wifi khách có ở sảnh.', '/hˈɑtspˌɑt/', 'n.', 'reservation', 'TOEIC'),
  ('ethernet', 'mạng dây', 'Meeting rooms still have ethernet ports.', 'Phòng họp vẫn có cổng mạng dây.', '/ˈiθɚnˌɛt/', 'n.', 'conference', 'TOEIC'),
  ('adapter', 'bộ chuyển', 'An adapter for UK plugs is at the desk.', 'Bộ chuyển phích cắm Anh có ở quầy.', '/ədˈæptɚ/', 'n.', 'itinerary', 'TOEIC'),
  ('charger', 'bộ sạc', 'A phone charger can be borrowed at reception.', 'Bộ sạc điện thoại có thể mượn ở lễ tân.', '/tʃˈɑɹdʒɚ/', 'n.', 'reservation', 'TOEIC'),
  ('battery', 'pin', 'The scanner battery lasts one shift.', 'Pin máy quét dùng được một ca.', '/bˈætɚi/', 'n.', 'inventory', 'TOEIC'),
  ('toner', 'mực in', 'Order toner when the light turns red.', 'Đặt mực in khi đèn đỏ.', '/tˈoʊnɚ/', 'n.', 'inventory', 'TOEIC'),
  ('cartridge', 'hộp mực', 'Shake the cartridge before you install it.', 'Lắc hộp mực trước khi lắp.', '/kˈɑɹtɹədʒ/', 'n.', 'inventory', 'TOEIC'),
  ('paper', 'giấy', 'Letter-size paper is in the cabinet.', 'Giấy khổ thư ở trong tủ.', '/pˈeɪpɚ/', 'n.', 'memo', 'TOEIC'),
  ('clip', 'kẹp giấy', 'Paper clips are in the middle drawer.', 'Kẹp giấy ở ngăn giữa.', '/klˈɪp/', 'n.', 'memo', 'TOEIC'),
  ('staple', 'ghim', 'Do not put staples in the scanner.', 'Không cho ghim vào máy quét.', '/stˈeɪpəl/', 'n.', 'memo', 'TOEIC'),
  ('binder', 'bìa còng', 'The training binder is on the shelf.', 'Bìa còng đào tạo ở trên kệ.', '/bˈaɪndɚ/', 'n.', 'employee', 'TOEIC'),
  ('whiteboard', 'bảng trắng', 'Wipe the whiteboard after the class.', 'Xóa bảng trắng sau buổi học.', '/ˈwaɪt.bɔrd/', 'n.', 'conference', 'TOEIC'),
  ('marker', 'bút lông', 'Only use dry-erase markers on this board.', 'Chỉ dùng bút xóa được trên bảng này.', '/mˈɑɹkɚ/', 'n.', 'conference', 'TOEIC'),
  ('flipchart', 'bảng giấy lật', 'A flipchart stands by the window.', 'Bảng giấy lật đứng cạnh cửa sổ.', '/ˈflɪp.tʃɑrt/', 'n.', 'conference', 'TOEIC'),
  ('podium', 'bục', 'The microphone is clipped to the podium.', 'Micro kẹp trên bục.', '/pˈoʊdiəm/', 'n.', 'conference', 'TOEIC'),
  ('microphone', 'micro', 'Test the microphone before guests arrive.', 'Thử micro trước khi khách đến.', '/mˈaɪkɹəfˌoʊn/', 'n.', 'conference', 'TOEIC'),
  ('headset', 'tai nghe', 'Interpreters will wear a headset.', 'Phiên dịch sẽ đeo tai nghe.', '/hˈɛdsˌɛt/', 'n.', 'conference', 'TOEIC'),
  ('interpreter', 'phiên dịch viên', 'An interpreter sits in the back row.', 'Phiên dịch viên ngồi hàng sau.', '/ˌɪntˈɝpɹətɚ/', 'n.', 'conference', 'TOEIC'),
  ('translation', 'bản dịch', 'A translation of the menu is on the table.', 'Bản dịch thực đơn ở trên bàn.', '/tɹænzlˈeɪʃən/', 'n.', 'complimentary', 'TOEIC'),
  ('bilingual', 'song ngữ', 'Bilingual staff work at the information desk.', 'Nhân viên song ngữ làm ở quầy thông tin.', '/baɪlˈɪŋɡwəl/', 'adj.', 'employee', 'TOEIC'),
  ('fluency', 'độ trôi chảy', 'Fluency in Korean is a plus for this post.', 'Trôi chảy tiếng Hàn là lợi thế cho vị trí này.', '/flˈuənsi/', 'n.', 'applicant', 'TOEIC'),
  ('accent', 'giọng', 'Guests had no trouble with her accent.', 'Khách không khó nghe giọng cô ấy.', '/əksˈɛnt/', 'n.', 'employee', 'TOEIC'),
  ('idiom', 'thành ngữ', 'Avoid idiom in safety instructions.', 'Tránh thành ngữ trong hướng dẫn an toàn.', '/ˈɪdiəm/', 'n.', 'memo', 'TOEIC'),
  ('jargon', 'thuật ngữ ngành', 'Replace jargon with plain words for guests.', 'Đổi thuật ngữ ngành thành lời dễ cho khách.', '/dʒˈɑɹɡən/', 'n.', 'brochure', 'TOEIC'),
  ('plain', 'dễ hiểu', 'Write signs in plain language.', 'Viết biển bằng ngôn ngữ dễ hiểu.', '/plˈeɪn/', 'adj.', 'brochure', 'TOEIC'),
  ('concise', 'ngắn gọn', 'Keep the email concise and polite.', 'Giữ email ngắn gọn và lịch sự.', '/kənsˈaɪs/', 'adj.', 'memo', 'TOEIC'),
  ('legible', 'dễ đọc', 'Write your name in legible letters.', 'Viết tên bằng chữ dễ đọc.', '/lˈɛdʒəbəl/', 'adj.', 'memo', 'TOEIC'),
  ('illegible', 'khó đọc', 'The signature on the form is illegible.', 'Chữ ký trên mẫu khó đọc.', '/ˌɪlˈɛdʒəbəl/', 'adj.', 'authorize', 'TOEIC'),
  ('proofread', 'đọc soát', 'Please proofread the brochure before printing.', 'Vui lòng đọc soát tờ brochure trước khi in.', '/pɹˈufɹˌid/', 'v.', 'brochure', 'TOEIC'),
  ('typo', 'lỗi đánh máy', 'A typo in the price list caused confusion.', 'Lỗi đánh máy trong bảng giá gây nhầm.', '/tˈaɪpoʊ/', 'n.', 'brochure', 'TOEIC'),
  ('edit', 'biên tập', 'Edit the draft before the director sees it.', 'Biên tập bản nháp trước khi giám đốc xem.', '/ˈɛdət/', 'v.', 'memo', 'TOEIC'),
  ('rewrite', 'viết lại', 'Rewrite the apology in a calmer tone.', 'Viết lại lời xin lỗi với giọng ôn hòa hơn.', '/ɹiɹˈaɪt/', 'v.', 'memo', 'TOEIC'),
  ('format', 'định dạng', 'Format the report with page numbers.', 'Định dạng báo cáo có số trang.', '/fˈɔɹmˌæt/', 'v.', 'memo', 'TOEIC'),
  ('template', 'mẫu sẵn', 'Use the letter template on the shared drive.', 'Dùng mẫu thư trên ổ dùng chung.', '/tˈɛmplət/', 'n.', 'memo', 'TOEIC'),
  ('letterhead', 'tiêu đề giấy công ty', 'Print contracts on official letterhead.', 'In hợp đồng trên giấy tiêu đề công ty.', '/lˈɛtɚhˌɛd/', 'n.', 'memo', 'TOEIC'),
  ('watermark', 'hình mờ', 'A draft watermark appears on each page.', 'Hình mờ bản nháp hiện trên mỗi trang.', '/wˈɔtɚmˌɑɹk/', 'n.', 'memo', 'TOEIC'),
  ('font', 'phông chữ', 'Use the same font as last year''s catalog.', 'Dùng cùng phông chữ với danh mục năm ngoái.', '/fˈɑnt/', 'n.', 'brochure', 'TOEIC'),
  ('layout', 'bố cục', 'The layout leaves room for a map.', 'Bố cục chừa chỗ cho bản đồ.', '/lˈeɪˌaʊt/', 'n.', 'brochure', 'TOEIC'),
  ('spacing', 'giãn dòng', 'Increase spacing so the text is easier to read.', 'Tăng giãn dòng để dễ đọc hơn.', '/spˈeɪsɪŋ/', 'n.', 'memo', 'TOEIC'),
  ('bullet', 'gạch đầu dòng', 'Use bullets for the three main benefits.', 'Dùng gạch đầu dòng cho ba lợi ích chính.', '/bˈʊlət/', 'n.', 'brochure', 'TOEIC'),
  ('heading', 'tiêu đề mục', 'Each heading should be in bold.', 'Mỗi tiêu đề mục nên in đậm.', '/hˈɛdɪŋ/', 'n.', 'memo', 'TOEIC'),
  ('caption', 'chú thích ảnh', 'Write a caption under every photo.', 'Viết chú thích dưới mỗi ảnh.', '/kˈæpʃən/', 'n.', 'brochure', 'TOEIC'),
  ('illustration', 'minh họa', 'The illustration shows how to fold the map.', 'Minh họa cho thấy cách gấp bản đồ.', '/ˌɪləstɹˈeɪʃən/', 'n.', 'brochure', 'TOEIC'),
  ('graphic', 'đồ họa', 'A graphic of the airport is on page two.', 'Đồ họa sân bay ở trang hai.', '/ɡɹˈæfɪk/', 'n.', 'itinerary', 'TOEIC'),
  ('icon', 'biểu tượng', 'A suitcase icon marks the luggage claim.', 'Biểu tượng vali đánh dấu nơi lấy hành lý.', '/ˈaɪkɑn/', 'n.', 'itinerary', 'TOEIC'),
  ('royalty', 'tiền bản quyền', 'The designer receives a royalty on each sale.', 'Nhà thiết kế nhận tiền bản quyền mỗi lần bán.', '/ɹˈɔɪəlti/', 'n.', 'budget', 'TOEIC'),
  ('franchise', 'nhượng quyền', 'A new franchise will open near the station.', 'Cửa hàng nhượng quyền mới sẽ mở gần ga.', '/fɹˈæntʃˌaɪz/', 'n.', 'headquarters', 'TOEIC'),
  ('outlet', 'cửa hàng chi nhánh', 'The outlet store sells last season''s bags.', 'Cửa hàng chi nhánh bán túi mùa trước.', '/ˈaʊtlˌɛt/', 'n.', 'brochure', 'TOEIC'),
  ('flagship', 'cửa hàng chính', 'The flagship store is on the main square.', 'Cửa hàng chính ở quảng trường lớn.', '/flˈæɡʃˌɪp/', 'n.', 'headquarters', 'TOEIC'),
  ('boutique', 'cửa hàng nhỏ', 'A boutique in the lobby sells local crafts.', 'Cửa hàng nhỏ ở sảnh bán đồ thủ công.', '/butˈik/', 'n.', 'brochure', 'TOEIC'),
  ('vending', 'máy bán hàng tự động', 'The vending machine on floor 3 takes cards.', 'Máy bán hàng tầng 3 nhận thẻ.', '/vˈɛndɪŋ/', 'n.', 'headquarters', 'TOEIC'),
  ('checkout', 'quầy thanh toán', 'Express checkout is for guests with no extras.', 'Thanh toán nhanh cho khách không phát sinh.', '/tʃˈɛkˌaʊt/', 'n.', 'reservation', 'TOEIC'),
  ('cashier', 'thu ngân', 'The cashier can print a duplicate receipt.', 'Thu ngân có thể in biên lai sao.', '/kæʃˈɪɹ/', 'n.', 'invoice', 'TOEIC'),
  ('change', 'tiền thối', 'The guest asked for change in small bills.', 'Khách xin thối tiền bằng tờ nhỏ.', '/tʃˈeɪndʒ/', 'n.', 'invoice', 'TOEIC'),
  ('recall', 'thu hồi sản phẩm', 'A recall was issued for the faulty charger.', 'Thu hồi được ban cho bộ sạc lỗi.', '/ɹˈikˌɔl/', 'n.', 'inventory', 'TOEIC'),
  ('defect', 'lỗi', 'Report any defect within 48 hours.', 'Báo lỗi trong vòng 48 giờ.', '/dˈifɛkt/', 'n.', 'inventory', 'TOEIC'),
  ('malfunction', 'trục trặc', 'A malfunction stopped the ticket machine.', 'Trục trặc làm dừng máy bán vé.', '/mælfˈʌŋkʃən/', 'n.', 'inventory', 'TOEIC'),
  ('breakdown', 'hỏng máy', 'A breakdown on the highway delayed the truck.', 'Hỏng máy trên cao tốc làm chậm xe tải.', '/bɹˈeɪkdˌaʊn/', 'n.', 'shipment', 'TOEIC'),
  ('part', 'phụ tùng', 'This part is no longer manufactured.', 'Phụ tùng này không còn được sản xuất.', '/pˈɑɹt/', 'n.', 'inventory', 'TOEIC'),
  ('patch', 'bản vá', 'Install the security patch tonight.', 'Cài bản vá bảo mật tối nay.', '/pˈætʃ/', 'n.', 'memo', 'TOEIC'),
  ('version', 'phiên bản', 'Version 3.2 fixes the printing bug.', 'Phiên bản 3.2 sửa lỗi in.', '/vˈɝʒən/', 'n.', 'memo', 'TOEIC'),
  ('beta', 'bản thử', 'Staff may try the beta on test phones only.', 'Nhân viên chỉ thử bản beta trên máy test.', '/bˈeɪtə/', 'n.', 'memo', 'TOEIC'),
  ('rollout', 'đợt triển khai', 'The nationwide rollout begins in October.', 'Đợt triển khai toàn quốc bắt đầu tháng Mười.', '/ɹˈoʊlˌaʊt/', 'n.', 'headquarters', 'TOEIC'),
  ('pilot', 'thí điểm', 'A pilot of the new menu runs in two cafés.', 'Thí điểm thực đơn mới chạy ở hai quán.', '/pˈaɪlət/', 'n.', 'complimentary', 'TOEIC'),
  ('prototype', 'nguyên mẫu', 'The prototype chair is in the showroom.', 'Ghế nguyên mẫu ở phòng trưng bày.', '/pɹˈoʊtətˌaɪp/', 'n.', 'inventory', 'TOEIC'),
  ('mock-up', 'mô hình thử', 'The designer sent a mock-up of the flyer.', 'Nhà thiết kế gửi mô hình thử tờ rơi.', '/ˈmɑk.ʌp/', 'n.', 'brochure', 'TOEIC'),
  ('blueprint', 'bản thiết kế', 'The blueprint shows a wider loading dock.', 'Bản thiết kế cho thấy bến chất hàng rộng hơn.', '/blˈupɹˌɪnt/', 'n.', 'shipment', 'TOEIC'),
  ('specification', 'thông số', 'The specification lists the maximum load.', 'Thông số liệt kê tải tối đa.', '/spˌɛsɪfɪkˈeɪʃən/', 'n.', 'inventory', 'TOEIC'),
  ('dimension', 'kích thước', 'Check the dimension of the crate before shipping.', 'Kiểm tra kích thước thùng trước khi gửi.', '/dɪmˈɛnʃən/', 'n.', 'shipment', 'TOEIC'),
  ('weight', 'trọng lượng', 'The weight limit for this elevator is posted.', 'Giới hạn trọng lượng thang máy được niêm yết.', '/wˈeɪt/', 'n.', 'occupancy', 'TOEIC'),
  ('volume', 'thể tích / sản lượng', 'Shipping volume rose in the holiday week.', 'Sản lượng gửi hàng tăng tuần lễ.', '/vˈɑljum/', 'n.', 'shipment', 'TOEIC'),
  ('quantity', 'số lượng', 'Write the quantity next to each item.', 'Ghi số lượng cạnh mỗi mặt hàng.', '/kwˈɑntəti/', 'n.', 'invoice', 'TOEIC'),
  ('unit', 'đơn vị', 'The price is 2 dollars per unit.', 'Giá là 2 đô la mỗi đơn vị.', '/jˈunət/', 'n.', 'invoice', 'TOEIC'),
  ('dozen', 'tá', 'Order two dozen towels for the spa.', 'Đặt hai tá khăn cho spa.', '/dˈʌzən/', 'n.', 'inventory', 'TOEIC'),
  ('gross', 'tổng trước thuế', 'The gross amount is printed in bold.', 'Tổng trước thuế được in đậm.', '/ɡɹˈoʊs/', 'n.', 'invoice', 'TOEIC'),
  ('net', 'ròng', 'Net pay appears at the bottom of the slip.', 'Lương ròng ở cuối phiếu.', '/nˈɛt/', 'adj.', 'budget', 'TOEIC'),
  ('rebate', 'hoàn tiền khuyến mãi', 'Mail the form to claim a 20-dollar rebate.', 'Gửi mẫu để nhận hoàn 20 đô la khuyến mãi.', '/ɹˈibˌeɪt/', 'n.', 'invoice', 'TOEIC'),
  ('coupon', 'phiếu giảm giá', 'This coupon cannot be combined with other offers.', 'Phiếu này không cộng với ưu đãi khác.', '/kˈupˌɔn/', 'n.', 'brochure', 'TOEIC'),
  ('voucher', 'phiếu quà tặng', 'A meal voucher is valid for 90 days.', 'Phiếu ăn có hiệu lực 90 ngày.', '/vˈaʊtʃɚ/', 'n.', 'complimentary', 'TOEIC'),
  ('gift', 'quà', 'A welcome gift waits in every suite.', 'Quà chào mừng chờ trong mỗi suite.', '/ɡˈɪft/', 'n.', 'complimentary', 'TOEIC'),
  ('loyalty', 'lòng trung thành', 'Loyalty points can be used for a free night.', 'Điểm trung thành đổi được một đêm miễn phí.', '/lˈɔɪəlti/', 'n.', 'reservation', 'TOEIC'),
  ('points', 'điểm thưởng', '500 points equal one breakfast.', '500 điểm tương đương một bữa sáng.', '/pˈɔɪnts/', 'n.', 'complimentary', 'TOEIC'),
  ('tier', 'hạng thành viên', 'Gold-tier guests get late checkout.', 'Khách hạng vàng được trả phòng muộn.', '/tˈiɹ/', 'n.', 'reservation', 'TOEIC'),
  ('privilege', 'đặc quyền', 'Lounge access is a privilege of business class.', 'Vào lounge là đặc quyền hạng thương gia.', '/pɹˈɪvlədʒ/', 'n.', 'itinerary', 'TOEIC'),
  ('perk', 'quyền lợi thêm', 'Free parking is a perk for night staff.', 'Đỗ xe miễn phí là quyền lợi thêm của ca đêm.', '/pˈɝk/', 'n.', 'employee', 'TOEIC'),
  ('incentive', 'động lực / thưởng khích lệ', 'A sales incentive is paid each quarter.', 'Thưởng khích lệ bán hàng trả mỗi quý.', '/ˌɪnsˈɛntɪv/', 'n.', 'budget', 'TOEIC'),
  ('commission', 'hoa hồng', 'Agents earn a 5 percent commission.', 'Đại lý nhận hoa hồng 5 phần trăm.', '/kəmˈɪʃən/', 'n.', 'budget', 'TOEIC'),
  ('raise', 'tăng lương', 'She received a raise after the review.', 'Cô ấy được tăng lương sau đánh giá.', '/ɹˈeɪz/', 'n.', 'employee', 'TOEIC'),
  ('cut', 'cắt giảm', 'A pay cut was avoided this year.', 'Năm nay tránh được cắt lương.', '/kˈʌt/', 'n.', 'budget', 'TOEIC'),
  ('freeze', 'đóng băng (tuyển/lương)', 'A hiring freeze lasts until March.', 'Đóng băng tuyển dụng kéo dài đến tháng Ba.', '/fɹˈiz/', 'n.', 'applicant', 'TOEIC'),
  ('headcount', 'số nhân sự', 'Headcount in accounting grew by two.', 'Số nhân sự kế toán tăng thêm hai.', '/hˈɛdkˌaʊnt/', 'n.', 'employee', 'TOEIC'),
  ('attrition', 'hao hụt nhân sự', 'Natural attrition will reduce the team by three.', 'Hao hụt tự nhiên sẽ giảm nhóm đi ba người.', '/ətɹˈɪʃən/', 'n.', 'employee', 'TOEIC'),
  ('retention', 'giữ chân nhân sự', 'Better hours improved staff retention.', 'Giờ làm tốt hơn giúp giữ chân nhân sự.', '/ɹitˈɛnʃən/', 'n.', 'employee', 'TOEIC'),
  ('morale', 'sĩ khí', 'Free lunch lifted morale on Fridays.', 'Cơm trưa miễn phí nâng sĩ khí thứ Sáu.', '/mɚˈæl/', 'n.', 'employee', 'TOEIC'),
  ('burnout', 'kiệt sức nghề nghiệp', 'Managers watch for signs of burnout.', 'Quản lý theo dõi dấu hiệu kiệt sức.', '/bˈɝnˌaʊt/', 'n.', 'employee', 'TOEIC'),
  ('wellness', 'sức khỏe toàn diện', 'A wellness talk is offered each month.', 'Buổi nói về sức khỏe được tổ chức mỗi tháng.', '/wˈɛlnəs/', 'n.', 'employee', 'TOEIC'),
  ('ergonomic', 'công thái học', 'An ergonomic chair is available on request.', 'Ghế công thái học có khi yêu cầu.', '/ˌɝɡənˈɑmɪk/', 'adj.', 'employee', 'TOEIC'),
  ('flex', 'linh hoạt', 'Flex hours start between 7 and 10 a.m.', 'Giờ linh hoạt bắt đầu từ 7 đến 10 giờ sáng.', '/flˈɛks/', 'adj.', 'employee', 'TOEIC'),
  ('remote', 'từ xa', 'Remote staff join the call at 9.', 'Nhân viên từ xa vào cuộc gọi lúc 9 giờ.', '/ɹɪmˈoʊt/', 'adj.', 'employee', 'TOEIC'),
  ('hybrid', 'kết hợp', 'Hybrid work means two office days a week.', 'Làm kết hợp nghĩa là hai ngày ở văn phòng.', '/hˈaɪbɹəd/', 'adj.', 'employee', 'TOEIC'),
  ('carpool', 'đi chung xe', 'Staff may carpool to the off-site meeting.', 'Nhân viên có thể đi chung xe tới họp ngoài.', '/kˈɑɹpˌul/', 'v.', 'itinerary', 'TOEIC'),
  ('teleconference', 'họp từ xa', 'The teleconference ID is in the invite.', 'Mã họp từ xa nằm trong thư mời.', '/tˌɛləkˈɑnfɹəns/', 'n.', 'conference', 'TOEIC'),
  ('webinar', 'hội thảo trực tuyến', 'The webinar will be recorded.', 'Hội thảo trực tuyến sẽ được ghi.', '/wˈɛbɪnɚ/', 'n.', 'conference', 'TOEIC'),
  ('livestream', 'phát trực tiếp', 'A livestream of the keynote starts at 10.', 'Phát trực tiếp bài chính bắt đầu lúc 10 giờ.', '/ˈlaɪv.strim/', 'n.', 'conference', 'TOEIC'),
  ('recording', 'bản ghi', 'The recording will stay online for a week.', 'Bản ghi sẽ ở trực tuyến một tuần.', '/ɹəkˈɔɹdɪŋ/', 'n.', 'conference', 'TOEIC'),
  ('transcript', 'bản ghi lời', 'A transcript is emailed to attendees.', 'Bản ghi lời được gửi email cho người dự.', '/tɹˈænskɹˌɪpt/', 'n.', 'conference', 'TOEIC'),
  ('slides', 'slide', 'Please send the slides by Thursday.', 'Vui lòng gửi slide trước thứ Năm.', '/slˈaɪdz/', 'n.', 'conference', 'TOEIC'),
  ('Q&A', 'hỏi đáp', 'Q&A follows the 20-minute talk.', 'Hỏi đáp sau bài nói 20 phút.', '/kju.ænd.eɪ/', 'n.', 'conference', 'TOEIC');
