INSERT INTO topics (code, name_vi, name_en, category, icon_key) VALUES
  ('family', 'Gia đình', 'Family', 'daily_life', 'family'),
  ('food_dining', 'Ẩm thực', 'Food & dining', 'daily_life', 'food_dining'),
  ('shopping', 'Mua sắm', 'Shopping', 'daily_life', 'shopping'),
  ('health', 'Sức khoẻ', 'Health', 'daily_life', 'health'),
  ('weather', 'Thời tiết', 'Weather', 'daily_life', 'weather'),
  ('housing', 'Nhà cửa', 'Housing', 'daily_life', 'housing'),
  ('transportation', 'Giao thông', 'Transportation', 'daily_life', 'transportation'),
  ('office_work', 'Công việc văn phòng', 'Office work', 'work_study', 'office_work'),
  ('meetings_presentations', 'Họp hành & thuyết trình', 'Meetings & presentations', 'work_study', 'meetings_presentations'),
  ('business_email', 'Email công việc', 'Business email', 'work_study', 'business_email'),
  ('job_interview', 'Phỏng vấn xin việc', 'Job interview', 'work_study', 'job_interview'),
  ('education', 'Giáo dục', 'Education', 'work_study', 'education'),
  ('travel', 'Du lịch', 'Travel', 'social', 'travel'),
  ('hobbies_entertainment', 'Sở thích & giải trí', 'Hobbies & entertainment', 'social', 'hobbies_entertainment'),
  ('sports', 'Thể thao', 'Sports', 'social', 'sports'),
  ('technology_social_media', 'Công nghệ & mạng xã hội', 'Technology & social media', 'social', 'technology_social_media'),
  ('small_talk_greetings', 'Giao tiếp xã giao', 'Small talk & greetings', 'social', 'small_talk_greetings'),
  ('banking_finance', 'Ngân hàng & tài chính', 'Banking & finance', 'finance', 'banking_finance');
