import type { MissionType, PetMood } from "../types";
import type { TopicCode } from "../features/learning-program/catalog";
import { TOPIC_BY_CODE } from "../features/learning-program/catalog";

export const APP_NAME = "Yume";
export const DEFAULT_PET_NAME = "Sora";

export const UI = {
  openApp: "Mở app",
  studyNow: "Học ngay",
  floatPet: "Đưa pet ra màn hình",
  quit: "Thoát",
  onboardingTitle: `Chào mừng đến ${APP_NAME}`,
  onboardingSubtitle: "Chọn người bạn đồng hành. Pet lớn lên mỗi khi bạn học flashcard TOEIC.",
  petNameLabel: "Tên pet",
  petNamePlaceholder: DEFAULT_PET_NAME,
  choosePet: "Chọn pet này",
  homeTitle: "Nhà của pet",
  homeGreetingMorning: "Chào buổi sáng",
  homeGreetingAfternoon: "Chào buổi chiều",
  homeGreetingEvening: "Chào buổi tối",
  homeSkyLabel: "Bầu trời của bạn",
  homeSkyDate: "+ {sky} · {day} tháng {month} +",
  homeSkyTitle: "Mỗi hành tinh mở ra một điều thú vị.",
  homeSkyMapLabel: "Không gian học cùng Sora",
  homeGoHome: "Về trang chủ",
  homeSuggestedLessons: "Bài học đề xuất",
  homePetDreaming: "đang mơ một điều hay",
  homeWelcomeSub: "Học tiếng Anh thật nhẹ nhàng, mỗi ngày một chút thôi 🌙",
  homePetQuote: "Tớ giữ chỗ bên cạnh cho cậu.",
  homeCompanionLabel: "Đồng hành",
  homeCompanionDaysUnit: "ngày",
  homeStartStudy: "Bắt đầu 5 phút",
  homeLookupHint: "Khám phá một từ mới",
  homeLookupShortHint: "Tra cứu",
  homeChatHint: "Luyện một cuộc hội thoại",
  homeChatShortHint: "Tâm sự",
  homeDailyStory: "Đọc truyện · Song ngữ",
  homeDailyStoryHint: "2 phút đọc song ngữ",
  homeStoryShortHint: "Thư viện",
  homeQuickActionsLabel: "Lối tắt",
  storyLibraryEyebrow: "Truyện song ngữ · Đọc nhẹ",
  storyLibraryTitle: "Thư viện truyện",
  storyLibrarySubtitle: "Chọn một câu chuyện và đọc song ngữ cùng Sora.",
  storySearchPlaceholder: "Tìm truyện…",
  storyFilterLabel: "Lọc",
  storyFilterAll: "Tất cả",
  storyFilterNew: "Mới bắt đầu",
  storyFilterReading: "Đang đọc",
  storyFilterFavorite: "Yêu thích",
  storyFilterChildren: "Thiếu nhi",
  storyFilterCommunication: "Giao tiếp",
  storySortLabel: "Sắp xếp",
  storySortNewest: "Mới nhất",
  storySortPopular: "Phổ biến",
  storySortAz: "A–Z",
  storySortLevel: "Level",
  storySortDuration: "Thời lượng",
  storyViewStory: "Xem truyện",
  storyContinueReading: "Tiếp tục đọc",
  storyReadFromStart: "Đọc từ đầu",
  storyReadSelectedChapter: "Đọc chương đã chọn",
  storyProgressRead: "Đã đọc {read}/{total}",
  storyFavoriteAdd: "Thêm yêu thích",
  storyFavoriteRemove: "Bỏ yêu thích",
  storyShare: "Chia sẻ",
  storyMore: "Thêm",
  storyChapters: "Danh sách chương",
  storyAttribution: "Nguồn & bản quyền",
  storyChapterMinutes: "{n} phút",
  storyChapterCount: "{n} chương",
  storyLoading: "Đang tải truyện…",
  storyEmptyLibrary: "Chưa có truyện nào phù hợp.",
  storyEmptySearch: "Không tìm thấy truyện. Thử từ khóa khác hoặc xóa bộ lọc.",
  storyClearFilters: "Xóa bộ lọc",
  storyLoadError: "Không tải được truyện. Thử lại.",
  storyRetry: "Thử lại",
  storyReaderBreadcrumbLibrary: "Thư viện truyện",
  storyReaderListen: "Nghe",
  storyReaderSave: "Lưu",
  storyReaderBookmark: "Đánh dấu",
  storyReaderFontSize: "Cỡ chữ",
  storyReaderFontSmall: "Nhỏ",
  storyReaderFontMedium: "Vừa",
  storyReaderFontLarge: "Lớn",
  storyReaderFontXl: "Rất lớn",
  storyReaderTheme: "Chế độ nền",
  storyReaderThemeGalaxy: "Galaxy",
  storyReaderThemeDark: "Tối",
  storyReaderLangBilingual: "Song ngữ",
  storyReaderLangEn: "Chỉ Anh",
  storyReaderLangVi: "Chỉ Việt",
  storyReaderFeaturedVocab: "Từ vựng nổi bật",
  storyReaderViewAllVocab: "Xem tất cả",
  storyReaderPrevChapter: "Chương trước",
  storyReaderNextChapter: "Chương tiếp theo",
  storyReaderPickChapter: "Chọn chương",
  storyReaderChapterProgress: "Tiến độ chương",
  storyReaderChapterTitle: "Chương {chapter}: {titleVi} · {titleEn}",
  storyReaderLanguageLabel: "Ngôn ngữ đọc",
  storyReaderListenSentence: "Nghe câu: {sentence}",
  storyReaderListenWord: "Nghe từ {word}",
  storyDictError: "Không tra được từ này. Thử lại.",
  storySaveWord: "Lưu từ",
  storyWordSaved: "Đã lưu từ",
  storyTtsUnsupported: "Trình duyệt không hỗ trợ đọc to.",
  storyShareCopied: "Đã sao chép liên kết.",
  storyShareFailed: "Không chia sẻ được.",
  homeWhisperLabel: "Lời thì thầm hôm nay",
  homeWhisperQuote: "Bước bé xíu thôi, là tiến bộ rồi.",
  homeWhisperAuthor: "",
  homeStreakSuffix: "ngày cùng Sora",
  homeFeedVocabTitle: "Học từ vựng nhanh",
  homeFeedPhraseTitle: "Học giao tiếp nhanh",
  homeFeedStoryTitle: "Truyện ngắn thư giãn",
  homeFeedPrevWord: "Từ trước",
  homeFeedNextWord: "Từ tiếp theo",
  homeFeedPrevPhrase: "Câu trước",
  homeFeedNextPhrase: "Câu tiếp theo",
  homeFeedSuggestedAnswer: "Câu trả lời gợi ý",
  homeFeedReadNow: "Đọc ngay",
  homeFeedMoreStories: "Xem thêm truyện",
  homeFeedTagBilingual: "Song ngữ",
  homeFeedTagEasy: "Dễ",
  homeLessonVocabKicker: "Lộ trình tối nay · 5 phút",
  homeLessonVocabTitle: "Một chuyến học nhỏ, trước giờ ngủ.",
  homeLessonVocabDeck: "TOEIC · Office English",
  homeLessonVocabProgress: "12 / 20 thẻ",
  homeLessonVocabWord: "coordinate",
  homeLessonVocabPhonetic: "/koʊˈɔːrdəneɪt/",
  homeLessonVocabMeaning: "phối hợp · điều phối",
  homeLessonPhraseKicker: "Luyện cùng Sora · 5 phút",
  homeLessonPhraseTitle: "Nói một câu, Sora sẽ lắng nghe.",
  homeLessonPhraseDeck: "TOEIC · Small talk",
  homeLessonPhraseProgress: "01 / 05 lượt",
  homeLessonPhraseWord: "How was your day?",
  homeLessonPhrasePhonetic: "Hôm nay của bạn thế nào?",
  homeLessonPhraseMeaning: "Mở đầu một cuộc trò chuyện thân thiện",
  homeLessonHint: "Sora nghĩ bạn sẽ thích từ này",
  studyModeTitle: "Chế độ học",
  vocabulary: "Từ vựng",
  phrases: "Giao tiếp",
  pickTopic: "Chủ đề",
  allTopics: "Tất cả chủ đề",
  pause: "Tạm dừng",
  resume: "Tiếp tục",
  known: "Đã nhớ",
  unknown: "Chưa nhớ",
  nextCard: "Thẻ tiếp",
  prevCard: "Thẻ trước",
  listen: "Nghe phát âm",
  close: "Đóng",
  level: "Cấp",
  xp: "XP",
  streak: "Streak",
  missionsToday: "Nhiệm vụ hôm nay",
  schedulerLabel: "Nhắc học mỗi (phút)",
  cardIntervalHint: "Pet đổi thẻ mỗi 30 giây",
  vocabBankSize: "{n} từ trong bộ học",
  loading: "Đang tải...",
  preparingData: "Đang chuẩn bị dữ liệu...",
  noCard: "Chưa có thẻ nào phù hợp.",
  popupTitle: APP_NAME,
  xpGained: "Pet vui lên · +{n} XP",
  levelUp: "Lên cấp {n}",
  missionComplete: "Hoàn thành nhiệm vụ",
  hungryHint: "Pet đang đói — một thẻ là đủ để pet vui lại.",
  sadHint: "Pet hơi buồn. Học một thẻ nhé.",
  dbUnavailable: "Không kết nối được dữ liệu. Hãy mở app bằng pnpm tauri dev.",
  exampleLabel: "Ví dụ",
  meaningLabel: "Nghĩa",
  loginTitle: "Chào lại",
  loginSubtitle: "Đăng nhập để gặp lại pet.",
  registerTitle: "Tạo tài khoản",
  registerSubtitle: "Chỉ cần tên và mật khẩu. Không cần email.",
  forgotTitle: "Quên mật khẩu",
  forgotSubtitle: "Lần đầu: email này sẽ lưu vào tài khoản. Lần sau phải dùng đúng email đó.",
  forgot2Title: "Đặt mật khẩu mới",
  username: "Username",
  password: "Mật khẩu",
  confirmPassword: "Nhập lại mật khẩu",
  currentPassword: "Mật khẩu hiện tại",
  newPassword: "Mật khẩu mới",
  confirmNewPassword: "Nhập lại mật khẩu mới",
  defaultPassword: "Mật khẩu mặc định",
  email: "Email",
  displayName: "Tên thường gọi",
  loginId: "Tên đăng nhập",
  createAccount: "Tạo tài khoản",
  alreadyHaveAccount: "Đã có tài khoản",
  login: "Đăng nhập",
  createAccountLink: "Tạo tài khoản",
  forgotPassword: "Quên mật khẩu",
  sendMail: "Gửi mail",
  backToLogin: "Quay lại đăng nhập",
  changePassword: "Đổi mật khẩu",
  passwordHint: "Ít nhất 8 ký tự. Không dùng lại username.",
  showPassword: "Hiện mật khẩu",
  hidePassword: "Ẩn mật khẩu",
  accountTitle: "Thông tin tài khoản",
  accountManage: "Quản lý tài khoản",
  accountPersonalTitle: "Thông tin cá nhân",
  accountPersonalSubtitle: "Thông tin cơ bản của tài khoản",
  accountMemberBadge: "Thành viên",
  accountWelcome: "Chào mừng bạn trở lại, cùng Yume tiếp tục hành trình đáng yêu nhé!",
  accountActionLearningDesc: "Xem tiến trình và tiếp tục học tập.",
  accountActionEditDesc: "Cập nhật thông tin cá nhân của bạn.",
  accountActionPasswordDesc: "Bảo mật tài khoản của bạn.",
  accountActionLogoutDesc: "Đăng xuất khỏi tài khoản hiện tại.",
  settingsBrand: "Cài đặt Yume",
  settingsNavHome: "Trang chủ",
  settingsNavPet: "Thú cưng",
  settingsNavMissions: "Nhiệm vụ",
  settingsNavCommunity: "Cộng đồng",
  settingsNavSectionAccount: "Tài khoản",
  settingsNavProfile: "Hồ sơ",
  settingsNavSettings: "Cài đặt",
  settingsNavNotifications: "Thông báo",
  settingsNavHelp: "Trợ giúp",
  settingsComingSoon: "Sắp có",
  settingsPromoTitle: "Nâng cấp trải nghiệm",
  settingsPromoBody: "Thêm tính năng sẽ xuất hiện tại đây.",
  settingsPromoCta: "Khám phá ngay",
  editAccountTitle: "Chỉnh sửa thông tin",
  editAccount: "Chỉnh sửa thông tin",
  petSection: "Pet",
  changeSpecies: "Loài pet",
  backHome: "Nhà của pet",
  cancel: "Hủy",
  save: "Lưu",
  logout: "Đăng xuất",
  logoutConfirmTitle: "Đăng xuất?",
  logoutConfirmBody: "Pet vẫn trên máy. Đăng nhập lại để học tiếp.",
  deleteAccount: "Xóa tài khoản",
  deleteConfirmTitle: "Xóa tài khoản?",
  deleteConfirmBody: "Pet, tiến độ và ảnh đại diện trên máy này sẽ bị xóa.",
  typeUsername: "Gõ lại username để xác nhận",
  emailEmptyConfirm: "Chưa có email. Lần quên mật khẩu tới sẽ lưu email bạn nhập lúc đó.",
  emailNotSaved: "Chưa lưu",
  savedProfile: "Đã lưu thông tin tài khoản.",
  changedPassword: "Đã đổi mật khẩu.",
  changePhoto: "Đổi ảnh",
  removePhoto: "Xóa ảnh",
  sentDefaultPassword: "Đã gửi mật khẩu mặc định tới",
  popupNeedLogin: "Mở app để đăng nhập",
  companion: "Nói với Sora",
  companionChatTitle: "Tâm sự cùng Sora",
  companionChatEyebrow: "Trò chuyện cùng Sora • Lắng nghe mỗi ngày",
  companionIntro: "Nói chuyện tiếng Anh với Sora. Học khi bạn muốn — không khi bạn đang tâm sự.",
  companionListenTagline: "Sora lắng nghe nhẹ nhàng, không phán xét.",
  companionPlaceholder: "Nói với Sora bằng tiếng Anh…",
  companionSend: "Gửi",
  companionCoach: "Gợi ý tiếng Anh",
  companionError: "Không gửi được. Thử lại.",
  learningProgram: "Chương trình học",
  learningProgramTitle: "Chương trình học",
  learningProgramSubtitle:
    "Cùng Sora thiết kế lộ trình học tiếng Anh thật nhẹ nhàng, phù hợp với bạn.",
  learningProgramName: "Tên chương trình",
  learningProgramLevel: "Trình độ",
  learningProgramContent: "Loại nội dung ưu tiên",
  learningProgramTopics: "Chủ đề đang học",
  learningProgramSave: "Lưu thay đổi",
  learningProgramSaved: "Đã lưu chương trình học.",
  learningProgramEdit: "Chỉnh sửa chương trình học",
  learningProgramActive: "Chủ đề đang học",
  learningProgramRoadmapTitle: "Lộ trình của bạn",
  learningProgramPriority: "Ưu tiên",
  learningProgramTopicsSelected: "Chủ đề đã chọn",
  learningProgramDailyReminder: "Nhắc học mỗi ngày",
  learningProgramTopicCount: "{n} chủ đề",
  learningProgramReminderValue: "{n} phút",
  learningProgramRoadmapNote:
    "Chỉ cần học một chút mỗi ngày là đủ. Sora luôn ở đây, cùng bạn tiến bộ mỗi ngày.",
  learningProgramLowContent:
    "Bộ chủ đề này còn ít nội dung (dưới 15 mục). Bạn vẫn có thể lưu và bổ sung sau.",
  learningProgramMinTopic: "Giữ ít nhất một chủ đề.",
  contentPrefVocabulary: "Từ vựng",
  contentPrefPhrase: "Giao tiếp",
  contentPrefBoth: "Cả hai",
  quickLookupTitle: "Tra từ nhanh",
  quickLookupEyebrow: "Tra cứu nhanh • Tiết kiệm thời gian",
  quickLookupDescription: "Tra cứu từ vựng tiếng Anh nhanh chóng, chính xác và tiện lợi.",
  quickLookupPlaceholder: "Nhập từ hoặc cụm từ tiếng Anh…",
  quickLookupHint: "Nhấn Enter để tra. Kết quả đã tra được lưu để dùng lại cả khi offline.",
  quickLookupLoading: "Đang tra từ…",
  quickLookupRecent: "Tìm kiếm gần đây",
  quickLookupClearRecent: "Xóa tất cả",
  quickLookupRemoveRecent: "Xóa khỏi lịch sử",
  quickLookupDefinition: "Định nghĩa",
  quickLookupSaveWord: "Lưu từ",
  quickLookupSpeak: "Phát âm",
  quickLookupAdd: "Thêm vào từ vựng đang học",
  quickLookupTopic: "Chủ đề",
  quickLookupAdded: "Đã thêm vào từ vựng.",
  quickLookupAddFailed: "Không thêm được từ này. Thử lại.",
  quickLookupPickTopic: "Chọn một chủ đề trước khi thêm.",
  quickLookupNoTopics: "Chưa có chủ đề trong chương trình học.",
  quickLookupNeedDesktop: "Thêm vào từ vựng chỉ khả dụng trên bản desktop.",
  quickLookupTray: "Tra từ nhanh",
} as const;

export function topicLabel(code: string): string {
  return TOPIC_BY_CODE.get(code as TopicCode)?.nameVi ?? code;
}

export const MOOD_LABELS: Record<PetMood, string> = {
  happy: "Vui",
  neutral: "Bình thường",
  sad: "Buồn",
  hungry: "Đói",
};

/** Longer mood line for Home companion card. */
export const HOME_MOOD_STATUS: Record<PetMood, string> = {
  happy: "đang rất vui",
  neutral: "đang bình thường",
  sad: "đang hơi buồn",
  hungry: "đang đói bụng",
};

export const MISSION_TITLES: Record<MissionType, string> = {
  learn_new: "Học từ/câu mới hôm nay",
  review_wrong: "Ôn lại từ chưa nhớ",
  topic_practice: "Luyện chủ đề",
};
