import type { MissionType, PetMood, PhraseTopic } from "../types";

export const APP_NAME = "Vocab Pet";

export const UI = {
  openApp: "Mở app",
  studyNow: "Học ngay",
  quit: "Thoát",
  onboardingTitle: "Chọn người bạn đồng hành",
  onboardingSubtitle: "Pet sẽ lớn lên mỗi khi bạn học từ vựng đúng.",
  choosePet: "Chọn pet này",
  homeTitle: "Nhà của pet",
  studyModeTitle: "Chọn chế độ học",
  vocabulary: "Từ vựng",
  phrases: "Câu giao tiếp",
  pickTopic: "Chọn chủ đề",
  allTopics: "Tất cả chủ đề",
  submit: "Submit",
  nextCard: "Thẻ tiếp theo",
  close: "Đóng",
  correct: "Đúng rồi!",
  incorrect: "Chưa đúng",
  level: "Cấp",
  xp: "XP",
  streak: "Streak",
  missionsToday: "Nhiệm vụ hôm nay",
  schedulerLabel: "Popup mỗi (phút)",
  loading: "Đang tải...",
  noCard: "Chưa có thẻ nào phù hợp.",
  needChoice: "Hãy chọn một đáp án.",
  popupTitle: "Học ngay",
  xpGained: "pet vui lên và nhận XP",
  missionComplete: "Hoàn thành nhiệm vụ",
  dbUnavailable: "Không kết nối được SQLite. Hãy chạy bằng pnpm tauri dev.",
  loginTitle: "Chào lại",
  loginSubtitle: "Đăng nhập để gặp lại pet.",
  registerTitle: "Tạo tài khoản",
  registerSubtitle: "Chỉ cần tên và mật khẩu. Không cần email.",
  forgotTitle: "Quên mật khẩu",
  forgotSubtitle: "Lần đầu: email này sẽ lưu vào tài khoản. Lần sau phải dùng đúng email đó.",
  forgot2Title: "Đặt mật khẩu mới",
  username: "Username",
  password: "Mật khẩu",
  confirmPassword: "Nhập lại mật khẩu",
  currentPassword: "Mật khẩu hiện tại",
  newPassword: "Mật khẩu mới",
  confirmNewPassword: "Nhập lại mật khẩu mới",
  defaultPassword: "Mật khẩu mặc định",
  email: "Email",
  displayName: "Tên thường gọi",
  loginId: "Tên đăng nhập",
  createAccount: "Tạo tài khoản",
  alreadyHaveAccount: "Đã có tài khoản",
  login: "Đăng nhập",
  createAccountLink: "Tạo tài khoản",
  forgotPassword: "Quên mật khẩu",
  sendMail: "Gửi mail",
  backToLogin: "Quay lại đăng nhập",
  changePassword: "Đổi mật khẩu",
  passwordHint: "Ít nhất 8 ký tự. Không dùng lại username.",
  showPassword: "Hiện mật khẩu",
  hidePassword: "Ẩn mật khẩu",
  accountTitle: "Thông tin tài khoản",
  editAccountTitle: "Chỉnh sửa thông tin",
  editAccount: "Chỉnh sửa thông tin",
  backHome: "Nhà của pet",
  cancel: "Hủy",
  save: "Lưu",
  logout: "Đăng xuất",
  logoutConfirmTitle: "Đăng xuất?",
  logoutConfirmBody: "Pet vẫn trên máy. Đăng nhập lại để học tiếp.",
  deleteAccount: "Xóa tài khoản",
  deleteConfirmTitle: "Xóa tài khoản?",
  deleteConfirmBody: "Pet, tiến độ và ảnh đại diện trên máy này sẽ bị xóa.",
  typeUsername: "Gõ lại username để xác nhận",
  emailEmptyConfirm: "Chưa có email. Lần quên mật khẩu tới sẽ lưu email bạn nhập lúc đó.",
  emailNotSaved: "Chưa lưu",
  savedProfile: "Đã lưu thông tin tài khoản.",
  changedPassword: "Đã đổi mật khẩu.",
  changePhoto: "Đổi ảnh",
  removePhoto: "Xóa ảnh",
  sentDefaultPassword: "Đã gửi mật khẩu mặc định tới",
  popupNeedLogin: "Mở app để đăng nhập",
} as const;

export const TOPIC_LABELS: Record<PhraseTopic, string> = {
  travel: "Du lịch",
  food: "Ẩm thực",
  office: "Công việc",
  family: "Gia đình",
};

export const MOOD_LABELS: Record<PetMood, string> = {
  happy: "Vui",
  neutral: "Bình thường",
  sad: "Buồn",
  hungry: "Đói",
};

export const MISSION_TITLES: Record<MissionType, string> = {
  learn_new: "Học từ/câu mới hôm nay",
  review_wrong: "Ôn lại từ/câu đã trả lời sai",
  topic_practice: "Luyện chủ đề",
};

export const TOPICS: PhraseTopic[] = ["travel", "food", "office", "family"];
