import type { MissionType, PetMood, PhraseTopic } from "../types";

export const APP_NAME = "Yume";
export const DEFAULT_PET_NAME = "Sora";

export const UI = {
  openApp: "Mở app",
  studyNow: "Học ngay",
  quit: "Thoát",
  onboardingTitle: `Chào mừng đến ${APP_NAME}`,
  onboardingSubtitle: "Chọn người bạn đồng hành. Pet lớn lên mỗi khi bạn học flashcard TOEIC.",
  petNameLabel: "Tên pet",
  petNamePlaceholder: DEFAULT_PET_NAME,
  choosePet: "Chọn pet này",
  homeTitle: "Nhà của pet",
  studyModeTitle: "Chế độ học",
  vocabulary: "Từ vựng",
  phrases: "Câu giao tiếp",
  conversation: "Hội thoại",
  pickTopic: "Chủ đề",
  allTopics: "Tất cả chủ đề",
  pause: "Tạm dừng",
  resume: "Tiếp tục",
  known: "Đã nhớ",
  unknown: "Chưa nhớ",
  nextCard: "Thẻ tiếp",
  prevCard: "Thẻ trước",
  listen: "Nghe phát âm",
  close: "Đóng",
  level: "Cấp",
  xp: "XP",
  streak: "Streak",
  missionsToday: "Nhiệm vụ hôm nay",
  schedulerLabel: "Nhắc học mỗi (phút)",
  cardIntervalHint: "Pet đổi thẻ mỗi 30 giây",
  vocabBankSize: "{n} từ trong bộ học",
  loading: "Đang tải...",
  noCard: "Chưa có thẻ nào phù hợp.",
  popupTitle: APP_NAME,
  xpGained: "Pet vui lên · +{n} XP",
  levelUp: "Lên cấp {n}",
  missionComplete: "Hoàn thành nhiệm vụ",
  hungryHint: "Pet đang đói — một thẻ là đủ để pet vui lại.",
  sadHint: "Pet hơi buồn. Học một thẻ nhé.",
  dbUnavailable: "Không kết nối được dữ liệu. Hãy mở app bằng pnpm tauri dev.",
  exampleLabel: "Ví dụ",
  meaningLabel: "Nghĩa",
  loginTitle: "Chào lại",
  loginSubtitle: "Đăng nhập để gặp lại pet.",
  registerTitle: "Tạo tài khoản",
  registerSubtitle: "Chỉ cần tên và mật khẩu. Không cần email.",
  forgotTitle: "Quên mật khẩu",
  forgotSubtitle: "Lần đầu: email này sẽ lưu vào tài khoản. Lần sau phải dùng đúng email đó.",
  forgot2Title: "Đặt mật khẩu mới",
  username: "Username",
  password: "Mật khẩu",
  confirmPassword: "Nhập lại mật khẩu",
  currentPassword: "Mật khẩu hiện tại",
  newPassword: "Mật khẩu mới",
  confirmNewPassword: "Nhập lại mật khẩu mới",
  defaultPassword: "Mật khẩu mặc định",
  email: "Email",
  displayName: "Tên thường gọi",
  loginId: "Tên đăng nhập",
  createAccount: "Tạo tài khoản",
  alreadyHaveAccount: "Đã có tài khoản",
  login: "Đăng nhập",
  createAccountLink: "Tạo tài khoản",
  forgotPassword: "Quên mật khẩu",
  sendMail: "Gửi mail",
  backToLogin: "Quay lại đăng nhập",
  changePassword: "Đổi mật khẩu",
  passwordHint: "Ít nhất 8 ký tự. Không dùng lại username.",
  showPassword: "Hiện mật khẩu",
  hidePassword: "Ẩn mật khẩu",
  accountTitle: "Thông tin tài khoản",
  editAccountTitle: "Chỉnh sửa thông tin",
  editAccount: "Chỉnh sửa thông tin",
  backHome: "Nhà của pet",
  cancel: "Hủy",
  save: "Lưu",
  logout: "Đăng xuất",
  logoutConfirmTitle: "Đăng xuất?",
  logoutConfirmBody: "Pet vẫn trên máy. Đăng nhập lại để học tiếp.",
  deleteAccount: "Xóa tài khoản",
  deleteConfirmTitle: "Xóa tài khoản?",
  deleteConfirmBody: "Pet, tiến độ và ảnh đại diện trên máy này sẽ bị xóa.",
  typeUsername: "Gõ lại username để xác nhận",
  emailEmptyConfirm: "Chưa có email. Lần quên mật khẩu tới sẽ lưu email bạn nhập lúc đó.",
  emailNotSaved: "Chưa lưu",
  savedProfile: "Đã lưu thông tin tài khoản.",
  changedPassword: "Đã đổi mật khẩu.",
  changePhoto: "Đổi ảnh",
  removePhoto: "Xóa ảnh",
  sentDefaultPassword: "Đã gửi mật khẩu mặc định tới",
  popupNeedLogin: "Mở app để đăng nhập",
} as const;

export const TOPIC_LABELS: Record<PhraseTopic, string> = {
  travel: "Du lịch",
  food: "Ẩm thực",
  office: "Công việc",
  family: "Gia đình",
};

export const MOOD_LABELS: Record<PetMood, string> = {
  happy: "Vui",
  neutral: "Bình thường",
  sad: "Buồn",
  hungry: "Đói",
};

export const MISSION_TITLES: Record<MissionType, string> = {
  learn_new: "Học từ/câu mới hôm nay",
  review_wrong: "Ôn lại từ chưa nhớ",
  topic_practice: "Luyện chủ đề",
};

export const TOPICS: PhraseTopic[] = ["travel", "food", "office", "family"];
