#!/usr/bin/env python3
"""Append extra TOEIC lemmas to the TSV until the bank reaches 1000."""

from __future__ import annotations

# word, pos, meaning, example, exampleVi, imageKey
EXTRA: list[tuple[str, str, str, str, str, str]] = [
    ("abide", "v.", "tuân theo", "Both sides must abide by the signed contract.", "Cả hai bên phải tuân theo hợp đồng đã ký.", "authorize"),
    ("agreement", "n.", "thỏa thuận", "The agreement will take effect on Monday.", "Thỏa thuận sẽ có hiệu lực vào thứ Hai.", "authorize"),
    ("assurance", "n.", "sự bảo đảm", "We need written assurance that the parts will arrive.", "Chúng tôi cần bảo đảm bằng văn bản rằng linh kiện sẽ đến.", "authorize"),
    ("cancellation", "n.", "việc hủy", "A late cancellation may incur a fee.", "Hủy muộn có thể bị tính phí.", "authorize"),
    ("determine", "v.", "xác định", "Please determine the cause of the delay.", "Vui lòng xác định nguyên nhân chậm trễ.", "deadline"),
    ("engage", "v.", "thuê / cam kết", "The firm will engage a lawyer for the case.", "Công ty sẽ thuê luật sư cho vụ việc.", "authorize"),
    ("obligate", "v.", "ràng buộc nghĩa vụ", "The clause does not obligate us to renew.", "Điều khoản không ràng buộc chúng tôi phải gia hạn.", "authorize"),
    ("party", "n.", "bên (hợp đồng)", "Each party must keep a signed copy.", "Mỗi bên phải giữ một bản đã ký.", "authorize"),
    ("provision", "n.", "điều khoản", "This provision covers damage during shipping.", "Điều khoản này gồm thiệt hại khi vận chuyển.", "authorize"),
    ("attract", "v.", "thu hút", "Bright signs attract visitors to the booth.", "Biển sáng thu hút khách tới gian hàng.", "brochure"),
    ("compare", "v.", "so sánh", "Please compare these two printers before buying.", "Vui lòng so sánh hai máy in này trước khi mua.", "brochure"),
    ("competition", "n.", "cạnh tranh", "Competition in this market is very strong.", "Cạnh tranh trên thị trường này rất mạnh.", "brochure"),
    ("consume", "v.", "tiêu thụ", "The factory consumes less energy after the upgrade.", "Nhà máy tiêu thụ ít năng lượng hơn sau khi nâng cấp.", "inventory"),
    ("convince", "v.", "thuyết phục", "The sample helped convince the buyer.", "Mẫu thử giúp thuyết phục người mua.", "brochure"),
    ("inspiration", "n.", "nguồn cảm hứng", "The designer found inspiration in local crafts.", "Nhà thiết kế tìm cảm hứng từ đồ thủ công địa phương.", "brochure"),
    ("persuasion", "n.", "sự thuyết phục", "The ad relies on gentle persuasion, not pressure.", "Quảng cáo dựa vào thuyết phục nhẹ, không ép.", "brochure"),
    ("productive", "adj.", "năng suất", "The morning session was surprisingly productive.", "Buổi sáng làm việc năng suất hơn mong đợi.", "conference"),
    ("satisfaction", "n.", "sự hài lòng", "Customer satisfaction rose after the refund policy changed.", "Sự hài lòng của khách tăng sau khi đổi chính sách hoàn tiền.", "brochure"),
    ("characteristic", "n.", "đặc điểm", "Durability is a key characteristic of this brand.", "Độ bền là đặc điểm then chốt của thương hiệu này.", "brochure"),
    ("consequence", "n.", "hậu quả", "A missed deadline can have a serious consequence.", "Bỏ lỡ hạn chót có thể gây hậu quả nghiêm trọng.", "deadline"),
    ("cover", "v.", "chi trả / bao gồm", "Does this plan cover dental care?", "Gói này có chi trả nha khoa không?", "authorize"),
    ("expiration", "n.", "ngày hết hạn", "Check the expiration date on the coupon.", "Kiểm tra ngày hết hạn trên phiếu.", "deadline"),
    ("frequently", "adv.", "thường xuyên", "The printer jams frequently in humid weather.", "Máy in kẹt giấy thường xuyên khi trời ẩm.", "inventory"),
    ("imply", "v.", "ám chỉ", "The memo does not imply that jobs will be cut.", "Bản ghi nhớ không ám chỉ sẽ cắt việc.", "memo"),
    ("promise", "n.", "lời hứa", "We kept our promise to ship on Friday.", "Chúng tôi giữ lời hứa gửi hàng vào thứ Sáu.", "shipment"),
    ("protect", "v.", "bảo vệ", "Wear gloves to protect your hands.", "Đeo găng để bảo vệ tay.", "inventory"),
    ("variety", "n.", "sự đa dạng", "The shop offers a variety of office chairs.", "Cửa hàng có nhiều loại ghế văn phòng.", "brochure"),
    ("address", "v.", "giải quyết (vấn đề)", "The director will address safety concerns today.", "Giám đốc sẽ giải quyết các lo ngại an toàn hôm nay.", "conference"),
    ("demonstrate", "v.", "trình diễn / chứng minh", "Please demonstrate how the new scanner works.", "Vui lòng trình diễn máy quét mới hoạt động thế nào.", "inventory"),
    ("develop", "v.", "phát triển", "The team will develop a training plan.", "Nhóm sẽ phát triển kế hoạch đào tạo.", "employee"),
    ("gather", "v.", "thu thập", "Please gather the survey forms from each table.", "Vui lòng thu thập phiếu khảo sát từ mỗi bàn.", "memo"),
    ("offer", "n.", "đề nghị / ưu đãi", "The limited-time offer ends on Sunday.", "Ưu đãi có thời hạn kết thúc vào Chủ nhật.", "brochure"),
    ("primarily", "adv.", "chủ yếu", "This shop serves primarily business travelers.", "Cửa hàng này phục vụ chủ yếu khách công tác.", "reservation"),
    ("risk", "n.", "rủi ro", "Delaying the shipment increases the risk of damage.", "Hoãn lô hàng làm tăng rủi ro hư hỏng.", "shipment"),
    ("strategy", "n.", "chiến lược", "Our strategy is to open smaller stores first.", "Chiến lược của chúng tôi là mở cửa hàng nhỏ trước.", "brochure"),
    ("strong", "adj.", "mạnh", "The company posted strong sales in March.", "Công ty ghi nhận doanh số mạnh vào tháng Ba.", "budget"),
    ("substitution", "n.", "sự thay thế", "No substitution of parts is allowed under the warranty.", "Không được thay linh kiện khác trong thời hạn bảo hành.", "inventory"),
    ("accommodate", "v.", "chứa / đáp ứng", "The hall can accommodate 250 guests.", "Hội trường chứa được 250 khách.", "occupancy"),
    ("arrangement", "n.", "sự sắp xếp", "Travel arrangements were made by the assistant.", "Việc sắp xếp chuyến đi do trợ lý thực hiện.", "itinerary"),
    ("association", "n.", "hiệp hội", "She joined the local hotel association.", "Cô ấy gia nhập hiệp hội khách sạn địa phương.", "conference"),
    ("location", "n.", "vị trí", "A downtown location is convenient for clients.", "Vị trí trung tâm tiện cho khách.", "headquarters"),
    ("overcrowded", "adj.", "quá đông", "The lobby was overcrowded during check-in.", "Sảnh quá đông trong giờ nhận phòng.", "occupancy"),
    ("register", "v.", "đăng ký", "Please register for the workshop online.", "Vui lòng đăng ký hội thảo trực tuyến.", "conference"),
    ("select", "v.", "chọn", "Select a seat near the aisle if you prefer.", "Chọn ghế gần lối đi nếu bạn thích.", "itinerary"),
    ("session", "n.", "phiên họp / buổi", "The afternoon session starts at 1:30.", "Phiên chiều bắt đầu lúc 1:30.", "conference"),
    ("access", "n.", "quyền truy cập", "Staff need a badge for access to the warehouse.", "Nhân viên cần thẻ để vào kho.", "authorize"),
    ("compatible", "adj.", "tương thích", "This cable is compatible with the new laptop.", "Cáp này tương thích với laptop mới.", "inventory"),
    ("delete", "v.", "xóa", "Do not delete files from the shared folder.", "Không xóa tệp trong thư mục dùng chung.", "memo"),
    ("display", "v.", "trưng bày", "Please display the new prices in the window.", "Vui lòng trưng bày giá mới ở cửa sổ.", "brochure"),
    ("duplicate", "n.", "bản sao", "Keep a duplicate of every signed form.", "Giữ bản sao của mọi mẫu đã ký.", "memo"),
    ("fail", "v.", "thất bại / hỏng", "If the printer fails, use the one on floor two.", "Nếu máy in hỏng, dùng máy ở tầng hai.", "inventory"),
    ("ignore", "v.", "bỏ qua", "Do not ignore the safety alarm.", "Không bỏ qua chuông báo an toàn.", "authorize"),
    ("search", "v.", "tìm kiếm", "You can search the catalog by product code.", "Bạn có thể tìm trong danh mục theo mã sản phẩm.", "brochure"),
    ("warning", "n.", "cảnh báo", "A warning light came on in the elevator.", "Đèn cảnh báo sáng trong thang máy.", "inventory"),
    ("disk", "n.", "đĩa (lưu trữ)", "Save a copy of the file on a backup disk.", "Lưu bản sao tệp trên đĩa dự phòng.", "memo"),
    ("keyboard", "n.", "bàn phím", "A spare keyboard is in the supply closet.", "Bàn phím dự phòng ở tủ đồ dùng.", "inventory"),
    ("software", "n.", "phần mềm", "The accounting software will be updated tonight.", "Phần mềm kế toán sẽ được cập nhật tối nay.", "memo"),
    ("virus", "n.", "vi-rút (máy tính)", "Do not open attachments that may contain a virus.", "Không mở tệp đính kèm có thể chứa vi-rút.", "memo"),
    ("attire", "n.", "trang phục", "Business attire is required at the dinner.", "Bữa tối yêu cầu trang phục công sở.", "conference"),
    ("behavior", "n.", "hành vi", "Polite behavior is expected at the front desk.", "Hành vi lịch sự được mong đợi ở quầy lễ tân.", "reservation"),
    ("etiquette", "n.", "nghi thức", "Email etiquette includes a clear subject line.", "Nghi thức email gồm dòng chủ đề rõ.", "memo"),
    ("formal", "adj.", "trang trọng", "A formal invitation will be mailed next week.", "Thiệp mời trang trọng sẽ được gửi tuần tới.", "conference"),
    ("informal", "adj.", "không trang trọng", "Friday is an informal dress day in this office.", "Thứ Sáu là ngày ăn mặc thoải mái ở văn phòng này.", "employee"),
    ("manners", "n.", "phép lịch sự", "Good manners help during client visits.", "Phép lịch sự giúp ích khi khách đến thăm.", "conference"),
    ("inappropriate", "adj.", "không phù hợp", "Jeans are inappropriate for the interview.", "Quần jeans không phù hợp cho buổi phỏng vấn.", "applicant"),
    ("condition", "n.", "tình trạng / điều kiện", "The used copier is in excellent condition.", "Máy photocopy cũ còn tình trạng rất tốt.", "inventory"),
    ("dissatisfaction", "n.", "sự không hài lòng", "The survey showed dissatisfaction with wait times.", "Khảo sát cho thấy không hài lòng về thời gian chờ.", "brochure"),
    ("item", "n.", "mặt hàng", "Each item on the invoice has a product code.", "Mỗi mặt hàng trên hóa đơn có mã sản phẩm.", "invoice"),
    ("pleasant", "adj.", "dễ chịu", "The hotel has a pleasant garden for breakfast.", "Khách sạn có vườn dễ chịu cho bữa sáng.", "complimentary"),
    ("prefer", "v.", "thích hơn", "Most guests prefer a room with a city view.", "Hầu hết khách thích phòng nhìn ra thành phố.", "reservation"),
    ("product", "n.", "sản phẩm", "This product is made in the local factory.", "Sản phẩm này được làm tại nhà máy địa phương.", "inventory"),
    ("return", "v.", "trả lại", "You may return unused goods within 14 days.", "Bạn có thể trả hàng chưa dùng trong 14 ngày.", "invoice"),
    ("receive", "v.", "nhận", "Did you receive the package this morning?", "Bạn đã nhận kiện hàng sáng nay chưa?", "shipment"),
    ("service", "n.", "dịch vụ", "Room service is available until midnight.", "Dịch vụ phòng có đến nửa đêm.", "reservation"),
    ("appointment", "n.", "cuộc hẹn", "I have an appointment with the dentist at 3.", "Tôi có hẹn nha sĩ lúc 3 giờ.", "deadline"),
    ("provider", "n.", "nhà cung cấp dịch vụ", "Our internet provider will visit on Tuesday.", "Nhà cung cấp internet sẽ đến vào thứ Ba.", "headquarters"),
    ("directory", "n.", "danh bạ", "The staff directory is posted near the elevator.", "Danh bạ nhân viên được dán gần thang máy.", "headquarters"),
    ("inexpensive", "adj.", "rẻ", "The inn offers inexpensive rooms near the station.", "Nhà trọ có phòng rẻ gần ga.", "reservation"),
    ("install", "v.", "lắp đặt", "Technicians will install the new phones tomorrow.", "Kỹ thuật viên sẽ lắp điện thoại mới vào ngày mai.", "inventory"),
    ("necessary", "adj.", "cần thiết", "A visitor badge is necessary after 6 p.m.", "Thẻ khách là cần thiết sau 6 giờ tối.", "authorize"),
    ("periodical", "n.", "tạp chí định kỳ", "The library keeps every periodical for two years.", "Thư viện giữ mỗi tạp chí định kỳ trong hai năm.", "memo"),
    ("subscribe", "v.", "đặt mua định kỳ", "You can subscribe to the newsletter by email.", "Bạn có thể đặt nhận bản tin qua email.", "brochure"),
    ("subscription", "n.", "gói đặt mua", "The magazine subscription includes digital access.", "Gói tạp chí gồm quyền xem bản điện tử.", "brochure"),
    ("densely", "adv.", "dày đặc", "The factory is in a densely populated area.", "Nhà máy nằm ở khu dân cư dày đặc.", "headquarters"),
    ("congested", "adj.", "ùn tắc", "Avoid the congested bridge during rush hour.", "Tránh cây cầu ùn tắc giờ cao điểm.", "itinerary"),
    ("haul", "v.", "vận chuyển (hàng nặng)", "Trucks haul steel from the port to the plant.", "Xe tải vận chuyển thép từ cảng tới nhà máy.", "shipment"),
    ("parking", "n.", "chỗ đỗ xe", "Parking is free for hotel guests.", "Khách khách sạn được đỗ xe miễn phí.", "reservation"),
    ("pedestrian", "n.", "người đi bộ", "Pedestrians should use the marked crossing.", "Người đi bộ nên đi qua vạch dành cho họ.", "itinerary"),
    ("proceed", "v.", "tiếp tục / đi tiếp", "Please proceed to gate 9 after security.", "Vui lòng đi tiếp tới cổng 9 sau an ninh.", "itinerary"),
    ("remainder", "n.", "phần còn lại", "Pay a deposit now and the remainder on delivery.", "Trả cọc ngay và phần còn lại khi giao hàng.", "invoice"),
    ("construction", "n.", "xây dựng", "The lobby is closed during construction.", "Sảnh đóng trong thời gian xây dựng.", "headquarters"),
    ("scanner", "n.", "máy quét", "Place the form face down on the scanner.", "Đặt mẫu đơn úp xuống máy quét.", "memo"),
    ("printer", "n.", "máy in", "The color printer is next to the copy room.", "Máy in màu ở cạnh phòng photocopy.", "inventory"),
    ("network", "n.", "mạng", "The office network will restart at noon.", "Mạng văn phòng sẽ khởi động lại lúc trưa.", "memo"),
    ("password", "n.", "mật khẩu", "Do not share your password with anyone.", "Không chia sẻ mật khẩu với ai.", "authorize"),
    ("download", "v.", "tải xuống", "You can download the form from our website.", "Bạn có thể tải mẫu đơn từ trang web.", "memo"),
    ("upload", "v.", "tải lên", "Please upload the photos to the shared drive.", "Vui lòng tải ảnh lên ổ dùng chung.", "memo"),
    ("laptop", "n.", "máy tính xách tay", "Bring your laptop to the training room.", "Mang laptop tới phòng đào tạo.", "conference"),
    ("desktop", "n.", "máy tính để bàn", "A new desktop will be placed on each desk.", "Mỗi bàn sẽ có một máy tính để bàn mới.", "headquarters"),
    ("wireless", "adj.", "không dây", "Free wireless internet is available in the lobby.", "Internet không dây miễn phí có ở sảnh.", "reservation"),
    ("broadband", "n.", "mạng băng thông rộng", "The hotel upgraded to faster broadband.", "Khách sạn đã nâng mạng băng thông rộng nhanh hơn.", "reservation"),
    ("backup", "n.", "bản sao lưu", "Make a backup of the files before you leave.", "Tạo bản sao lưu tệp trước khi bạn về.", "memo"),
    ("crash", "v.", "sập (máy/hệ thống)", "If the system crashes, call the help desk.", "Nếu hệ thống sập, gọi bộ phận hỗ trợ.", "memo"),
    ("server", "n.", "máy chủ", "The mail server is down until 4 p.m.", "Máy chủ thư dừng đến 4 giờ chiều.", "headquarters"),
    ("database", "n.", "cơ sở dữ liệu", "Customer records are stored in a secure database.", "Hồ sơ khách được lưu trong cơ sở dữ liệu an toàn.", "memo"),
    ("spreadsheet", "n.", "bảng tính", "Enter the hours in this spreadsheet.", "Nhập số giờ vào bảng tính này.", "memo"),
    ("presentation", "n.", "bài thuyết trình", "Her presentation on sales lasted 20 minutes.", "Bài thuyết trình về doanh số của cô ấy dài 20 phút.", "conference"),
    ("projector", "n.", "máy chiếu", "Please turn off the projector after the talk.", "Vui lòng tắt máy chiếu sau bài nói.", "conference"),
    ("photocopier", "n.", "máy photocopy", "The photocopier needs more paper.", "Máy photocopy cần thêm giấy.", "inventory"),
    ("stapler", "n.", "dập ghim", "A stapler is in the top drawer.", "Dập ghim ở ngăn kéo trên.", "memo"),
    ("envelope", "n.", "phong bì", "Put the contract in a large envelope.", "Cho hợp đồng vào phong bì lớn.", "memo"),
    ("postage", "n.", "cước tem", "Postage to overseas offices is higher.", "Cước gửi ra văn phòng nước ngoài cao hơn.", "shipment"),
    ("mailbox", "n.", "hòm thư", "Drop the keys in the mailbox if we are out.", "Bỏ chìa vào hòm thư nếu chúng tôi vắng.", "headquarters"),
    ("outgoing", "adj.", "đi ra / gửi đi", "Outgoing mail leaves the office at 4 p.m.", "Thư gửi đi rời văn phòng lúc 4 giờ chiều.", "memo"),
    ("incoming", "adj.", "đến / gửi tới", "Incoming calls are answered at the front desk.", "Cuộc gọi đến được lễ tân trả lời.", "reservation"),
    ("recipient", "n.", "người nhận", "Check the recipient's name before you send.", "Kiểm tra tên người nhận trước khi gửi.", "memo"),
    ("sender", "n.", "người gửi", "The sender must include a return address.", "Người gửi phải ghi địa chỉ trả lại.", "memo"),
    ("confidential", "adj.", "mật", "This file is confidential and must stay locked.", "Tệp này là mật và phải khóa.", "authorize"),
    ("priority", "n.", "mức ưu tiên", "Safety is our first priority on the factory floor.", "An toàn là ưu tiên hàng đầu trong nhà máy.", "inventory"),
    ("contract", "n.", "hợp đồng", "Please read the contract before you sign it.", "Vui lòng đọc hợp đồng trước khi ký.", "authorize"),
    ("legal", "adj.", "hợp pháp / pháp lý", "Ask the legal team about this clause.", "Hỏi nhóm pháp chế về điều khoản này.", "authorize"),
    ("illegal", "adj.", "bất hợp pháp", "It is illegal to copy this software.", "Sao chép phần mềm này là bất hợp pháp.", "authorize"),
    ("binding", "adj.", "ràng buộc", "The offer is binding once both sides sign.", "Đề nghị trở nên ràng buộc khi cả hai bên ký.", "authorize"),
    ("breach", "n.", "vi phạm (hợp đồng)", "Late payment is a breach of the agreement.", "Thanh toán muộn là vi phạm thỏa thuận.", "authorize"),
    ("disclose", "v.", "công bố / tiết lộ", "We cannot disclose client names.", "Chúng tôi không thể tiết lộ tên khách.", "authorize"),
    ("disclosure", "n.", "sự công bố", "Full disclosure of fees is required by law.", "Luật yêu cầu công bố đầy đủ các khoản phí.", "authorize"),
    ("patent", "n.", "bằng sáng chế", "The company filed a patent for the new design.", "Công ty nộp bằng sáng chế cho thiết kế mới.", "brochure"),
    ("copyright", "n.", "bản quyền", "Do not use photos without copyright permission.", "Không dùng ảnh khi chưa có phép bản quyền.", "brochure"),
    ("landlord", "n.", "chủ nhà", "The landlord will paint the office in May.", "Chủ nhà sẽ sơn văn phòng vào tháng Năm.", "headquarters"),
    ("tenant", "n.", "người thuê", "Each tenant must pay rent by the fifth.", "Mỗi người thuê phải trả tiền nhà trước ngày mùng 5.", "budget"),
    ("lease", "n.", "hợp đồng thuê", "The lease on this floor ends in December.", "Hợp đồng thuê tầng này hết vào tháng 12.", "authorize"),
    ("rent", "n.", "tiền thuê", "Rent includes water but not electricity.", "Tiền thuê gồm nước nhưng không gồm điện.", "budget"),
    ("premises", "n.", "mặt bằng / cơ sở", "No smoking is allowed on the premises.", "Cấm hút thuốc trong mặt bằng.", "headquarters"),
    ("penalty", "n.", "tiền phạt", "There is a penalty for returning the car late.", "Có tiền phạt nếu trả xe muộn.", "authorize"),
    ("liable", "adj.", "chịu trách nhiệm pháp lý", "The carrier is liable for lost cargo.", "Hãng vận chuyển chịu trách nhiệm hàng mất.", "shipment"),
    ("exempt", "adj.", "được miễn", "Food products are exempt from this tax.", "Sản phẩm thực phẩm được miễn thuế này.", "invoice"),
    ("enforce", "v.", "thực thi", "Guards enforce the visitor rules at the gate.", "Bảo vệ thực thi nội quy khách ở cổng.", "authorize"),
    ("suspend", "v.", "tạm dừng", "The city will suspend night buses this week.", "Thành phố sẽ tạm dừng xe buýt đêm tuần này.", "itinerary"),
    ("commence", "v.", "bắt đầu", "Boarding will commence at 8:40.", "Việc lên máy bay bắt đầu lúc 8:40.", "itinerary"),
    ("cease", "v.", "chấm dứt", "Please cease using the old letterhead.", "Vui lòng ngừng dùng tiêu đề thư cũ.", "memo"),
    ("attorney", "n.", "luật sư", "An attorney reviewed the lease yesterday.", "Luật sư đã xem hợp đồng thuê hôm qua.", "authorize"),
    ("witness", "n.", "nhân chứng / người làm chứng", "A witness must sign the last page.", "Người làm chứng phải ký trang cuối.", "authorize"),
    ("evidence", "n.", "bằng chứng", "Keep the photos as evidence of the damage.", "Giữ ảnh làm bằng chứng thiệt hại.", "authorize"),
    ("property", "n.", "tài sản / bất động sản", "Personal property should not be left in the lobby.", "Không để tài sản cá nhân ở sảnh.", "headquarters"),
    ("secure", "adj.", "an toàn / bảo mật", "Keep passwords in a secure place.", "Giữ mật khẩu ở nơi an toàn.", "authorize"),
    ("security", "n.", "an ninh", "Security will check bags at the entrance.", "An ninh sẽ kiểm tra túi ở cửa vào.", "authorize"),
]
